{
  "hash": "e39ee83e1d4b48f12e22ccc6343bb966",
  "result": {
    "markdown": "# Inferenzstatistik & Zusammenhangsmaße\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\netb18 <- haven::read_dta(\"./data/BIBBBAuA_2018_suf1.0.dta\")\n```\n:::\n\n\nNeue Pakete:\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"broom\") # Ergebnisse in data.frame umwandeln\ninstall.packages(\"effectsize\") # u.a. Cohen's D berechnen \ninstall.packages(\"survey\") # Gewichtung\n```\n:::\n\n\nBisher haben wir die Angaben aus unserem Datensatz immer als fix angesehen. \nZiel einer statistischen Auswertung ist aber meistens, Aussagen über die *Grundgesamtheit* oder *Population* zu treffen. \nIm Fall der ETB 2018 wären das also alle Erwerbstätigen in Deutschland.\n\n\n## t-Tests\n\nEines der zentralen Werkzeuge der grundlegenden Inferenzstatistik ist der t-Test [Details im Anhang](#tdist).\n\nEin typischer Anwendungsfall für t-Tests ist der Gruppenvergleich, dazu geben wir in `t.test()` die zu testende Variable und und nach einer `~`[^tilde2] die Gruppenvariable an. \nWir testen hier also auf Altersunterschiede zwischen Männern (`S1`=1, daher group1) und Frauen (`S1`=2, daher group2).\n\n[^tilde2]: Tastaturbefehle: `Alt Gr` + `*` auf Windows. Auf macOS `Alt` + `N` und anschließend ein Leerzeichen, damit die Tilde erscheint.\n\n::: {.cell}\n\n```{.r .cell-code}\netb18$zpalter[etb18$zpalter>100] <- NA\nt.test(etb18$zpalter~etb18$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  etb18$zpalter by etb18$S1\nt = -8.801, df = 19681, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -1.727972 -1.098490\nsample estimates:\nmean in group 1 mean in group 2 \n       46.49079        47.90402 \n```\n:::\n:::\n\n\nEs hat sich als Konvention etabliert, von einem signifikanten Unterschied zu sprechen wenn die Irrtumswahrscheinlichkeit unter 5% liegt. Das bedeutet:\n\n> *Assuming that the null hypothesis is true and the study is repeated an infinite number times by drawing random samples from the same populations(s), less than 5% of these results will be more extreme than the current result.*[^1]\n\n[^1]: [Failing Grade: 89% of Introduction-to-Psychology Textbooks That Define or Explain Statistical Significance Do So Incorrectly. Advances in Methods and Practices in Psychological Science, 2515245919858072.](https://doi.org/10.1177/2515245919858072)\n\nDa hier der p-Wert sehr viel kleiner ist als 0.05 ist (`p-value < 2.2e-16`)[^ehoch], können wir von einen statistisch signifikanten Unterschied sprechen.  \n\n[^ehoch]: `2.2e-16` steht für 2.2 aber mit 16 Nullen vorweg. Das ist Rs Art zu sagen, dass der Wert sehr sehr klein ist.\n\nStandardmäßig bekommen wir einen beidseitigen Test (`\"two.sided\"`), wir können aber auch einen links- (`\"less\"`) oder rechtsseitigen (`\"greater\"`) Test anfordern [mehr dazu](#hypt):\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(etb18$zpalter~etb18$S1,alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  etb18$zpalter by etb18$S1\nt = -8.801, df = 19681, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0\n95 percent confidence interval:\n -1.727972 -1.098490\nsample estimates:\nmean in group 1 mean in group 2 \n       46.49079        47.90402 \n```\n:::\n\n```{.r .cell-code}\nt.test(etb18$zpalter~etb18$S1,alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  etb18$zpalter by etb18$S1\nt = -8.801, df = 19681, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 1 and group 2 is less than 0\n95 percent confidence interval:\n      -Inf -1.149096\nsample estimates:\nmean in group 1 mean in group 2 \n       46.49079        47.90402 \n```\n:::\n\n```{.r .cell-code}\nt.test(etb18$zpalter~etb18$S1,alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  etb18$zpalter by etb18$S1\nt = -8.801, df = 19681, p-value = 1\nalternative hypothesis: true difference in means between group 1 and group 2 is greater than 0\n95 percent confidence interval:\n -1.677367       Inf\nsample estimates:\nmean in group 1 mean in group 2 \n       46.49079        47.90402 \n```\n:::\n:::\n\n\nFür Effektgrößen wie Cohen's D empfiehlt sich das Paket [{effectsize}](https://easystats.github.io/effectsize/index.html):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\ncohens_d(etb18$zpalter~etb18$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohen's d |         95% CI\n--------------------------\n-0.12     | [-0.15, -0.10]\n\n- Estimated using pooled SD.\n```\n:::\n:::\n\n\n\n<!-- https://github.com/gergness/srvyr/ -->\n<!-- https://federicovegetti.github.io/teaching/heidelberg_2018/lab/sst_lab_day2.html -->\n<!-- http://people.ku.edu/~chkim/soc910/note/Soc910_Note_04_Weight.pdf -->\n\n\n### [Übung](#ttestue)\n\n## Korrelation {#pearson}\n\nZur Bestimmung eines Zusammenhangs zwischen zwei metrischen Variablen empfiehlt sich der Pearson-Korrelationskoeffizient:\n\n$$r = \\frac{\\frac{1}{n}\\Sigma_{i}^{n}(x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\frac{1}{n}\\Sigma_{i}^{n}(x_i-\\bar{x})^2} \\times \\sqrt{\\frac{1}{n}\\Sigma_{i}^{n} (y_i-\\bar{y})^2}} = \\frac{cov_{xy}}{s_x \\times s_y}$$\n\nIn R können wir den Korrelationskoeffizienten mit `cor.test()` berechnen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattributes(etb18$F231)$label\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Wie viele Stunden arbeiten Sie i.d.R. im Durchschnitt pro Woche von zu Hause aus\"\n```\n:::\n\n```{.r .cell-code}\netb18$F231[etb18$F231>990] <- NA\n\ncor.test(etb18$zpalter,etb18$F231,method = \"pearson\", use = \"pairwise.complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  etb18$zpalter and etb18$F231\nt = 3.6513, df = 4427, p-value = 0.0002639\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.02538399 0.08411155\nsample estimates:\n       cor \n0.05479515 \n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\nEs handelt sich mit 0.05480 also um einen geringen Zusammenhang. Der p-Wert gibt uns auch hier wieder Auskunft über die stat. Signifikanz: mit 0.00026 liegt der p-Wert deutlich unter 0,05 $\\Rightarrow$ wir würden hier die Nullhypothese verwerfen, dass die Korrelation in der Grundpopulation gleich Null ist. \n\nUm eine  Korrelationsmatrix zu erhalten hilft das Paket [{correlation}](https://github.com/easystats/correlation): \n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"correlation\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(correlation)\netb18 %>% select(zpalter,F231,az) %>% \n  correlation() %>% \n  summary(.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Correlation Matrix (pearson-method)\n\nParameter |       az |    F231\n------------------------------\nzpalter   | -0.03*** | 0.05***\nF231      |  0.22*** |        \n\np-value adjustment method: Holm (1979)\n```\n:::\n:::\n\n\n\n## Ordinale Merkmale: Rangkorrelation & Kendall's $\\tau$\n   \nEin klassisches ordinales Merkmal ist die Schulbildung, die wir aus `S3` zusammenfassen können (Details im Code-Fenster unten). \nWir sehen uns den (möglichen) Zusammenhang zwischen der Schulbildung und `F600_12` an:\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-condensed\" style=\"font-size: 10px; width: auto !important; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;color: white !important;\"> v </th>\n   <th style=\"text-align:left;color: white !important;\"> l </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;font-weight: bold;background-color: rgba(242, 242, 242, 1) !important;\"> educ </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(242, 242, 242, 1) !important;\"> höchster Schulabschluss </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 1 </td>\n   <td style=\"text-align:left;\"> max. Hauptschulabschluss </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 2 </td>\n   <td style=\"text-align:left;\"> max. mittlere Reife </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 3 </td>\n   <td style=\"text-align:left;\"> (Fach-)Abitur </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;font-weight: bold;background-color: rgba(242, 242, 242, 1) !important;\"> F600_12 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(242, 242, 242, 1) !important;\"> Häufigkeit: unter Lärm arbeiten </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 1 </td>\n   <td style=\"text-align:left;\"> häufig </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 2 </td>\n   <td style=\"text-align:left;\"> manchmal </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 3 </td>\n   <td style=\"text-align:left;\"> selten </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-family: monospace;\"> 4 </td>\n   <td style=\"text-align:left;\"> nie </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\netb18 <- \n  etb18 %>% \n  mutate(educ = case_when(S3 %in% 2:4 ~ 1,\n                          S3 %in% 5:6 ~ 2,\n                          S3 %in% 7:8 ~ 3),\n         F600_12 = ifelse(F600_12 > 4,NA,F600_12))\n```\n:::\n\n\nFür den Spearman-Rangkorrelationskoeffizienten kännen wir `method = \"spearman\"` nutzen. Da die Berechnung etwas dauert, verwende ich hier nur die ersten 200 Beobachtungen (`[1:200]`);\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(etb18$educ,etb18$F600_12,method = \"spearman\", use = \"pairwise.complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  etb18$educ and etb18$F600_12\nS = 1.048e+12, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.1717745 \n```\n:::\n:::\n\n\nEin weiteres Zusammenhangsmaß für ordinale Variablen sind Konkordanzmaße wie Kendall's $\\tau$.\nHierfür die Werteverhältnisse gezählt, zur Berechnung in R können wir wieder `cor.test()` verwenden, diesmal mit der Option `method = \"kendall\"`. Falls es Bindungen gibt wird hier Kendall's $\\tau_b$ berechnet, welches Bindungen ausschließt.\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(etb18$educ,etb18$F600_12, method = \"kendall\", use = \"pairwise.complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tKendall's rank correlation tau\n\ndata:  etb18$educ and etb18$F600_12\nz = 24.087, p-value < 2.2e-16\nalternative hypothesis: true tau is not equal to 0\nsample estimates:\n      tau \n0.1521478 \n```\n:::\n:::\n\n\n\n## $\\chi^2$ & Cramér's V {#chi2}\n\n$\\chi^2$  basiert auf dem Vergleich der beobachteten Häufigkeit mit einer (theoretischen) Verteilung, welche statistische Unabhängigkeit abbildet (Indifferenztabelle - [mehr dazu](#indiff)). \nWir sehen uns `F204` (Mehrarbeitsvergütung) und `S1` (Geschlecht) an. \n\n\n::: {.cell}\n\n```{.r .cell-code}\netb18$F204[etb18$F204>4] <- NA\netb18 %>% filter(!is.na(F204)) %>% count(F204,S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 8 × 3\n  F204                        S1               n\n  <dbl+lbl>                   <dbl+lbl>    <int>\n1 1 [durch Auszahlung]        1 [männlich]   536\n2 1 [durch Auszahlung]        2 [weiblich]   400\n3 2 [durch Freizeitausgleich] 1 [männlich]  1924\n4 2 [durch Freizeitausgleich] 2 [weiblich]  2308\n5 3 [durch beides]            1 [männlich]  1458\n6 3 [durch beides]            2 [weiblich]   873\n7 4 [keine Abgeltung]         1 [männlich]  1120\n8 4 [keine Abgeltung]         2 [weiblich]   740\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nattributes(etb18$F204)$label\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Wie wird Ihre Mehrarbeit bzw. wie werden Ihre Überstunden abgegolten?\"\n```\n:::\n:::\n\n\n\n\nMit `chisq.test()` bekommen wir $\\chi^2$ ausgegeben, diese müssen wir jedoch auf ein `xtabs()`-Objekt anwenden:\n\n::: {.cell}\n\n```{.r .cell-code}\nxtabs(~ F204 + S1, data = etb18)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    S1\nF204    1    2\n   1  536  400\n   2 1924 2308\n   3 1458  873\n   4 1120  740\n```\n:::\n\n```{.r .cell-code}\ntab1 <- xtabs(~ F204 + S1, data = etb18)\nchisq.test(tab1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  tab1\nX-squared = 225.45, df = 3, p-value < 2.2e-16\n```\n:::\n:::\n\n\nFür Cramér's $v$ können wir wieder auf `{effectsize}` zurückgreifen:\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cramers_v(etb18$F204,etb18$S1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCramer's V |       95% CI\n-------------------------\n0.16       | [0.14, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n:::\n:::\n\n\n[Weitere Maße](#corrs)\n\n### [Übung](#corr)\n\n## Ergebnisse weiterverarbeiten\n\nDie Kennzahlen aus dem Output können wir auch separat aufrufen:\n\n::: {.cell}\n\n```{.r .cell-code}\nttest1 <- t.test(etb18$zpalter~etb18$S1,alternative = \"two.sided\")\nttest1$statistic # t-Wert\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        t \n-8.801045 \n```\n:::\n\n```{.r .cell-code}\nttest1$p.value # p-Wert\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.465385e-18\n```\n:::\n:::\n\nMit `str()` können wir alle Werte ansehen:\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ttest1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"htmlwidget-043ea63e6f089da5ed44\" style=\"width:100%;height:10%;\" class=\"jsonedit html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-043ea63e6f089da5ed44\">{\"x\":{\"data\":{\"statistic\":{\"t\":-8.80104533220738},\"parameter\":{\"df\":19681.2726528126},\"p.value\":1.46538453882347e-18,\"conf.int\":[-1.72797245320593,-1.09848984089805],\"estimate\":{\"mean in group 1\":46.4907907907908,\"mean in group 2\":47.9040219378428},\"null.value\":{\"difference in means between group 1 and group 2\":0},\"stderr\":0.160575374141101,\"alternative\":\"two.sided\",\"method\":\"Welch Two Sample t-test\",\"data.name\":\"etb18$zpalter by etb18$S1\"},\"options\":{\"mode\":\"view\",\"modes\":[\"code\",\"form\",\"text\",\"tree\",\"view\"]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nMit dem `tidy()` aus [{broom}](https://broom.tidymodels.org/) können wir einen `data.frame()` erstellen, der die wesentlichen Parameter enthält:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\ntidy(ttest1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 10\n  estimate estimate1 estimate2 statistic  p.value param…¹ conf.…² conf.…³ method\n     <dbl>     <dbl>     <dbl>     <dbl>    <dbl>   <dbl>   <dbl>   <dbl> <chr> \n1    -1.41      46.5      47.9     -8.80 1.47e-18  19681.   -1.73   -1.10 Welch…\n# … with 1 more variable: alternative <chr>, and abbreviated variable names\n#   ¹​parameter, ²​conf.low, ³​conf.high\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr1 <- cor.test(etb18$zpalter,etb18$F231,method = \"pearson\", use = \"pairwise.complete.obs\")\ntidy(corr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 8\n  estimate statistic  p.value parameter conf.low conf.high method        alter…¹\n     <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>         <chr>  \n1   0.0548      3.65 0.000264      4427   0.0254    0.0841 Pearson's pr… two.si…\n# … with abbreviated variable name ¹​alternative\n```\n:::\n:::\n\n\nWas hilft uns das? \n\nWir können diesen `data.frame()` mit `{ggplot}` visualisieren, indem wir die Konfidenzintervallgrenzen in `geom_pointrange()` angeben:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nttest_df <- tidy(corr1)\nggplot(ttest_df,aes(y=\"t.test\",x=estimate)) +\n  geom_vline(aes(xintercept = 0),linetype = \"dashed\") +\n  geom_pointrange(aes(xmin = conf.low,xmax = conf.high), color = \"navy\")\n```\n\n::: {.cell-output-display}\n![](07_inferenz_files/figure-html/unnamed-chunk-19-1.png){width=80%}\n:::\n:::\n\n\nWir können mit `bind_rows()` auch mehrere Tests zu einem `data.frame` zusammenfügen:\n\n::: {.cell}\n\n```{.r .cell-code}\nttest_m <- \n  cor.test(etb18$zpalter[etb18$S1==1],\n           etb18$F231[etb18$S1==1],method = \"pearson\", use = \"pairwise.complete.obs\")\n\nttest_w <- \n  cor.test(etb18$zpalter[etb18$S1==2],\n           etb18$F231[etb18$S1==2],method = \"pearson\", use = \"pairwise.complete.obs\")\n\ntest_df2 <- bind_rows(tidy(ttest_m),\n                      tidy(ttest_w), \n                      .id = \"S1\") # Variable S1 erstellen als Identifikator\n\ntest_df2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 9\n  S1    estimate statistic  p.value parameter conf.low conf.high method  alter…¹\n  <chr>    <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>   <chr>  \n1 1       0.0715      3.56 0.000376      2465   0.0322    0.111  Pearso… two.si…\n2 2       0.0332      1.47 0.142         1960  -0.0111    0.0773 Pearso… two.si…\n# … with abbreviated variable name ¹​alternative\n```\n:::\n:::\n\n\nDas können wir jetzt wieder plotten:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(test_df2,aes(y=S1,x=estimate)) +\n  geom_vline(aes(xintercept = 0),linetype = \"dashed\") +\n  geom_pointrange(aes(xmin = conf.low,xmax = conf.high), color = \"navy\")\n```\n\n::: {.cell-output-display}\n![](07_inferenz_files/figure-html/unnamed-chunk-21-1.png){width=80%}\n:::\n:::\n\n\n\n\n## Gewichtung \n\n\n> Bei der Datenanalyse ist man oft mit einer Stichprobe aus einer größeren Population konfrontiert und man möchte aus dieser Stichprobe Rückschlüsse auf die größere Population ziehen. Die meisten statistischen Verfahren für diese sog. „Inferenzstatistik“ beruhen dabei auf der Annahme, dass die Stichprobe eine einfache Zufallsstichprobe ist. Bei einer solchen Stichprobe gelangen alle Elemente der Grundgesamtheit mit der gleichen Wahrscheinlichkeit in die Stichprobe. In der Praxis sind solche Stichproben aber die große Ausnahme. Häufig haben bestimmte Gruppen von Personen höhere Auswahlwahrscheinlichkeiten als andere. [Kohler/Kreuter, S.81](https://doi.org/10.1515/9783110469509)\n\n\n\nGewichte sind ein häufig verwendetes Gegenmittel. \nDie einfachste Variante für eine Gewichtung ist die Option  `wt=` in `count()`:\n\n::: {.cell}\n\n```{.r .cell-code}\netb18 %>% \n  count(S1,m1202,wt = gew2018_hr17)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 3\n   S1           m1202                                                          n\n   <dbl+lbl>    <dbl+lbl>                                                  <dbl>\n 1 1 [männlich] -1 [keine Angabe]                                         4.00e4\n 2 1 [männlich]  1 [Ohne Berufsabschluss]                                 1.87e6\n 3 1 [männlich]  2 [duale o. schulische Berufsausbildung/einf.,mittl. Be… 1.08e7\n 4 1 [männlich]  3 [Aufstiegsfortbildung (Meister, Techniker, kfm. AFB u… 2.15e6\n 5 1 [männlich]  4 [Fachhochschule, Universität/ geh., höhere Beamte]     5.61e6\n 6 2 [weiblich] -1 [keine Angabe]                                         4.43e4\n 7 2 [weiblich]  1 [Ohne Berufsabschluss]                                 1.45e6\n 8 2 [weiblich]  2 [duale o. schulische Berufsausbildung/einf.,mittl. Be… 9.35e6\n 9 2 [weiblich]  3 [Aufstiegsfortbildung (Meister, Techniker, kfm. AFB u… 9.90e5\n10 2 [weiblich]  4 [Fachhochschule, Universität/ geh., höhere Beamte]     5.13e6\n```\n:::\n:::\n\n\nFür umfangreichere Anwendungen stehen in R stehen die Pakete [`{survey}`](https://stylizeddata.com/how-to-use-survey-weights-in-r/) und das darauf aufbauende [`{srvyr}`](https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html) zur Verfügung.\nZunächst verwenden wir `svydesign()`, um die Gewichtung festzulegen. \nIm weiteren stellt [`{survey}`](https://stylizeddata.com/how-to-use-survey-weights-in-r/) dann zahlreiche Funktionen zur Verfügung, die eine gewichtete Variante der basis-Befehle sind - bspw. `svymean()` und `svytable()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survey)\netb18_weighted <- svydesign(id      = ~intnr,\n                            weights = ~gew2018,\n                            data    = etb18)\nsvytable(~S1+m1202,etb18_weighted) # syntax wie xtabs()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   m1202\nS1        -1        1        2        3        4\n  1   21.388 1000.524 5770.737 1149.563 2999.676\n  2   23.685  774.785 5000.538  529.435 2741.686\n```\n:::\n\n```{.r .cell-code}\nxtabs(~S1+m1202,etb18)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   m1202\nS1    -1    1    2    3    4\n  1   21  594 4371 1073 4015\n  2   24  497 4926  652 3839\n```\n:::\n\n```{.r .cell-code}\nsvymean(~zpalter, etb18_weighted, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          mean     SE\nzpalter 43.986 0.1281\n```\n:::\n\n```{.r .cell-code}\nmean(etb18$zpalter, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 47.19228\n```\n:::\n:::\n\n\nFür [Regressionsmodelle](#reg) gibt es bspw. `survey::svyglm()`\n\nLektüre: [Kiesl, H. (2014). Gewichtung. In N. Baur & J. Blasius (Eds.), Handbuch Methoden der empirischen Sozialforschung (pp. 349–356). Springer Fachmedien Wiesbaden.](https://doi.org/10.1007/978-3-531-18939-0_24)\n\n\n\n## Übungen\n\n### Übung 1 {#ttestue}\nTesten Sie die Hypothese, dass ein signifikanter Unterschied in der Arbeitszeit (`az`) zwischen Männern und Frauen besteht (`S1`). Beide Variablen haben keine Missings - Sie können direkt los legen\n\nBerechnen Sie das Cohen's d für diesen Zusammenhang.\n\n\n\n### Übung 2 {#corr}\n\n+ Untersuchen Sie die Korrelation zwischen der Wochenarbeitszeit (`az`) und dem Einkommen (`F518_SUF`) der Befragten.\n\n+ Denken Sie daran, die Missings in `F518_SUF` auszuschließen: `etb18$F518_SUF[etb18$F518_SUF>99990] <- NA`, `az` hat keine Missings.\n\n\n+ Untersuchen Sie den Zusammenhang zwischen der Häufigkeit von starkem Termin- oder Leistungsdruck `F411_01` und der dreistufigen Schulbildungsvariable `educ`.\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"jzwvupqnpy\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#jzwvupqnpy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jzwvupqnpy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jzwvupqnpy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jzwvupqnpy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jzwvupqnpy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jzwvupqnpy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jzwvupqnpy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jzwvupqnpy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jzwvupqnpy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jzwvupqnpy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jzwvupqnpy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jzwvupqnpy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jzwvupqnpy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzwvupqnpy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jzwvupqnpy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jzwvupqnpy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzwvupqnpy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jzwvupqnpy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzwvupqnpy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jzwvupqnpy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzwvupqnpy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzwvupqnpy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzwvupqnpy .gt_left {\n  text-align: left;\n}\n\n#jzwvupqnpy .gt_center {\n  text-align: center;\n}\n\n#jzwvupqnpy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jzwvupqnpy .gt_font_normal {\n  font-weight: normal;\n}\n\n#jzwvupqnpy .gt_font_bold {\n  font-weight: bold;\n}\n\n#jzwvupqnpy .gt_font_italic {\n  font-style: italic;\n}\n\n#jzwvupqnpy .gt_super {\n  font-size: 65%;\n}\n\n#jzwvupqnpy .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#jzwvupqnpy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jzwvupqnpy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jzwvupqnpy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jzwvupqnpy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jzwvupqnpy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jzwvupqnpy .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">var</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">.</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">9</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">F411_01</td>\n<td class=\"gt_row gt_left\">Wie häufig kommt es vor, dass Sie unter starkem Termin- oder Leistungsdruck arbe</td>\n<td class=\"gt_row gt_left\">häufig</td>\n<td class=\"gt_row gt_left\">manchmal</td>\n<td class=\"gt_row gt_left\">selten</td>\n<td class=\"gt_row gt_left\">nie</td>\n<td class=\"gt_row gt_left\">keine Angabe</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n  + So können Sie `educ` in `etb18` erstellen und die Missings in `F411_01` überschreiben und Erstellen Sie einen kleineren Datensatz, indem Sie die ersten 300 Zeilen auswählen:\n\n::: {.cell}\n\n```{.r .cell-code}\netb18_small <- \n  etb18 %>% \n  mutate(educ = case_when(S3 %in% 2:4 ~ 1,\n                          S3 %in% 5:6 ~ 2,\n                          S3 %in% 7:8 ~ 3),\n         F411_01 = ifelse(F411_01 > 4,NA,F411_01)) %>% \n  slice(1:300)\n```\n:::\n\n  + Erstellen Sie eine Kreuztabelle aus `educ` und `F411_01`\n  + Berechnen Sie Spearman's $\\rho$, Kendall's $\\tau$ und Cramér's $v$ auf Basis von `etb18_small`.\n\n\n### Übung 3 {#weight}\n\n+ Legen Sie die Gewichtung auf Basis von `gew2018` an.\n+ Erstellen Sie eine Kontingenztabelle für `gkpol` und `Mig` - einmal gewichtet und einmal ohne Gewichte. Sehen Sie die Unterschiede?\n\n\n::: {.cell}\n\n:::\n\n\n+ Berechnen Sie den Mittelwert für den Bruttoverdienst `F518_SUF` (Schließen Sie die Missings ggf. mit `etb18$F518_SUF[etb18$F518_SUF>99990] <- NA` - sie können mit `max(etb18$F518_SUF,na.rm = T)` überprüfen ob das Maximum bei 72000 liegt)\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"tqqpsmzchj\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#tqqpsmzchj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tqqpsmzchj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tqqpsmzchj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tqqpsmzchj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tqqpsmzchj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tqqpsmzchj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tqqpsmzchj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tqqpsmzchj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tqqpsmzchj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tqqpsmzchj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tqqpsmzchj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tqqpsmzchj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tqqpsmzchj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqqpsmzchj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tqqpsmzchj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tqqpsmzchj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqqpsmzchj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tqqpsmzchj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqqpsmzchj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tqqpsmzchj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqqpsmzchj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tqqpsmzchj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tqqpsmzchj .gt_left {\n  text-align: left;\n}\n\n#tqqpsmzchj .gt_center {\n  text-align: center;\n}\n\n#tqqpsmzchj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tqqpsmzchj .gt_font_normal {\n  font-weight: normal;\n}\n\n#tqqpsmzchj .gt_font_bold {\n  font-weight: bold;\n}\n\n#tqqpsmzchj .gt_font_italic {\n  font-style: italic;\n}\n\n#tqqpsmzchj .gt_super {\n  font-size: 65%;\n}\n\n#tqqpsmzchj .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#tqqpsmzchj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tqqpsmzchj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tqqpsmzchj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tqqpsmzchj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tqqpsmzchj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tqqpsmzchj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">var</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">name</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">unter 2.000 Einwohner</td>\n<td class=\"gt_row gt_right\">1</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">2.000 bis unter 5.000 Einwohner</td>\n<td class=\"gt_row gt_right\">2</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">5.000 bis unter 20.000 Einwohner</td>\n<td class=\"gt_row gt_right\">3</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">20.000 bis unter 50.000 Einwohner</td>\n<td class=\"gt_row gt_right\">4</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">50.000 bis unter 100.000 Einwohner</td>\n<td class=\"gt_row gt_right\">5</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">100.000 bis unter 500.000 Einwohner</td>\n<td class=\"gt_row gt_right\">6</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">gkpol</td>\n<td class=\"gt_row gt_left\">500.000 und mehr Einwohner</td>\n<td class=\"gt_row gt_right\">7</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">Mig</td>\n<td class=\"gt_row gt_left\">nicht zuordenbar</td>\n<td class=\"gt_row gt_right\">-4</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">Mig</td>\n<td class=\"gt_row gt_left\">nein</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">Mig</td>\n<td class=\"gt_row gt_left\">ja</td>\n<td class=\"gt_row gt_right\">1</td></tr>\n    <tr><td class=\"gt_row gt_left\" style=\"font-family: Roboto;\">Mig</td>\n<td class=\"gt_row gt_left\">Ausländer</td>\n<td class=\"gt_row gt_right\">2</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n## Anhang\n\n### t-Verteilung {#tdist}\nDas $t$ kommt dabei aus der Student-t-Verteilung bzw. als $z$-Wert aus der Standard-Normalverteilung, die wir in der vergangenen Session kennengelernt haben. $t$ wählen wir dabei so, dass bei wiederholter Stichprobenziehung 95% der resultierenden KI den wahren Wert aus der Grundgesamtheit beinhalten würden:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07_inferenz_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=60% height=60%}\n:::\n:::\n\nAufgrund der Symmetrie teilen wir die Irrtumswahrscheinlichkeit also auf jeweils 2,5% auf und können mit `qt()` den entsprechenden $t$-Wert nachsehen. Die gezeigte Verteilung unterstellt dabei eine Stichprobe von $n=10.000$:\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p=.025,df = 9999) # bei welchem t-Wert liegen 2.5% links davon?\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.960201\n```\n:::\n\n```{.r .cell-code}\nqt(p=.975,df = 9999) # bei welchem t-Wert liegen 2.5% rechts davon?\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.960201\n```\n:::\n:::\n\n\nFür kleine Stichproben ist der t-Wert deutlich größer, um die zusätzliche Unsicherheit der Stichprobengröße zu berücksichtigen. Mit steigendem $n$ bzw. $df$ nähert sich der t-Wert dem z-Wert der Standard-NV an:\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p = .025) # z-Wert aus Standard-NV\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.959964\n```\n:::\n\n```{.r .cell-code}\nqt(p = .025, df = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3.182446\n```\n:::\n\n```{.r .cell-code}\nqt(p = .025, df = 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.042272\n```\n:::\n\n```{.r .cell-code}\nqt(p = .025, df = 300)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.967903\n```\n:::\n\n```{.r .cell-code}\nqt(p = .025, df = 3000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.960755\n```\n:::\n:::\n\n\n\nEs gibt auch andere Varianten, zB. 90% oder 99%:\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(p = .05, df = 9999)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.645006\n```\n:::\n\n```{.r .cell-code}\nqt(p = .005, df = 9999)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.576321\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07_inferenz_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n### Hypothesen {#hypt}\n\nDie grundlegende Idee des Hypothesentests ist, dass wir uns nur dann für die Alternativhypothese entscheiden, wenn wir eine ausreichend große Abweichung von dem in der $H_0$ postulierten Wert feststellen. \nDazu berechnen wir den $t$-Wert für die Differenz der Mittelwerte und gleichen diesen dann mit der t-Verteilung ab.\nEin t-Wert, der außerhalb der 95% weniger extremen Werte liegt, wird als statistisch signifikant bezeichnet.\nLetztlich dreht sich alles darum, welche Alternativhypothese getestet wird:\n\n+ Für einen beidseitigen Test ist die **Alternativ**hypothese, dass es *keinen* Gruppenunterschied gibt:  \n\n    $H_0: \\mu_1 - \\mu_2 = 0$; $H_A: \\mu_1 - \\mu_2 \\neq 0$\n \n+ Ein linksseitiger Test hätte entsprechend die **Alternativ**hypothese, dass der Gruppenunterschied *kleiner* 0 ist:  \n\n    $H_0: \\mu_1 - \\mu_2 \\geqslant 0$; $H_A: \\mu_1 - \\mu_2 < 0$\n\n+ Ein rechtssseitiger Test hätte entsprechend die **Alternativ**hypothese, dass der Gruppenunterschied *größer* 0 ist:  \n\n    $H_0: \\mu_1 - \\mu_2 \\leqslant 0$; $H_A: \\mu_1 - \\mu_2 > 0$\n\n### Weitere Korrelationsmaße {#corrs}\n\nKendall's $\\tau_a$, welches im Nenner alle Paarvergleiche berücksichtigt, können wir mit `KendallTauA()` aus dem Paket `DescTools` berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"DescTools\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\nKendallTauA(etb18$educ,etb18$F600_12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.09681707\n```\n:::\n:::\n\nDer Wert ist deutlich niedriger als von Kendall's $\\tau_b$, da hier der Nenner durch die Berücksichtigung *aller* möglichen Paarvergleiche größer wird, der Zähler aber für beide Varianten von Kendall's $\\tau$ gleich definiert ist. \n\n\nEine andere Alternative, welche auch beim Vorliegen von Bindungen den vollen Wertebereich [-1,1] erreichen kann ist Goodman & Kruskal's $\\gamma$. Dieses können wir mit dem Befehl `GoodmanKruskalGamma` aus dem Paket `{DescTools}` berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DescTools)\nGoodmanKruskalGamma(etb18$educ,etb18$F600_12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2342228\n```\n:::\n:::\n\nAuch Goodman & Kruskal's $\\gamma$ deutet auf einen negativen Zusammenhang hin, hier ist die Stärke aber deutlich höher. Dies ist auf die Berücksichtigung der Bindungen zurückzuführen: hier werden alle Bindungen ausgeschlossen, also auch Paarvgleiche mit Bindungen nur auf  einer Variable. Es reduziert sich also der Nenner, somit ergibt sich im Ergebnis ein höherer Koeffizient für Goodman & Kruskal's $\\gamma$ als für Kendall's $\\tau_b$. \n\n\n::: {.cell}\n\n```{.r .cell-code}\netb18 %>% \n  select(educ,F600_12) %>% \n  correlation(method = \"kendall\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Correlation Matrix (kendall-method)\n\nParameter1 | Parameter2 |  tau |       95% CI |     z |         p\n-----------------------------------------------------------------\neduc       |    F600_12 | 0.15 | [0.14, 0.16] | 24.09 | < .001***\n\np-value adjustment method: Holm (1979)\nObservations: 19654\n```\n:::\n:::\n\n[Hier findet sich eine Liste weiterer Kennzahlen, die sich mit {correlate}](https://easystats.github.io/correlation/articles/types.html) berechnen lassen.\n",
    "supporting": [
      "07_inferenz_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/htmlwidgets-1.5.4/htmlwidgets.js\"></script>\r\n<link href=\"site_libs/jsoneditor-5.25.6/jsoneditor.min.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/jsoneditor-5.25.6/jsoneditor.min.js\"></script>\r\n<script src=\"site_libs/jsonedit-binding-3.0.0/jsonedit.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}