project:
  type: book
  output-dir: docs
  output-file: docs
  
book:
  title: "R am BIBB"
  author: "Andreas Filser"
  date: last-modified
  chapters:
    - index.qmd
    - 01_intro.qmd
    # - 02_intro.Rmd
    # - 03_desc.qmd
    # - 04_viz.qmd
    # - 09_reg.qmd
    # - summary.qmd
    # - references.qmd
  language: de-DE
  always_allow_html: true
  downloads: [pdf]
  page-footer:
    left: |
      Inhalt by [Andreas Filser](https://afilser.netlify.app/)<br>
      Erstellt mit R und [Quarto](https://quarto.org/)<br>
      [View the source at GitHub](https://github.com/filius23/BIBB_R)<br>
    right: |
      All content licensed under [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)

bibliography: references.bib

format:
  html:
    theme: flatly
    page-layout: full
  # pdf:
  #   documentclass: scrreprt # kapitel02 kable

execute:
  freeze: auto
