{
  "hash": "2eef9216b1f70261a6a34f1d8b575d40",
  "result": {
    "markdown": "# Logistische Regressionsmodelle \n\n\n\n\n\n[Ableitungen grafisch erstellt](https://twitter.com/allison_horst/status/1554921698742468625?s=11&t=Ac_YizlsYkOfUIkuWmaaWQ)\n\n[Intro von A Heiss](https://www.andrewheiss.com/blog/2022/05/20/marginalia/)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm()\nmarginaleffects::marginaleffects()\n```\n:::\n\n\n[`{marginaleffects}`](https://vincentarelbundock.github.io/marginaleffects/)\n\n\nBisher hatten wir immer Regressionsmodelle betrachtet, die eine metrisch skalierte abhängige Variable hatten.[^1]\nAber gerade Individualmerkmale sind nur selten metrisch skaliert, z.B. Erwerbstatus, Familienstand, Geschlecht, Elternstand, ... Ein lineares OLS-Regressionsmodell wie wir es bisher kennen gelernt haben, hilft uns hier nicht weiter. \nSchauen wir uns beispielsweise die Arbeitsplatzsituation der männlichen Befragten in der ETB 2018 an (`F605`)[^3] :\n\n[^1]: Leseempfehlung: [\"Handbuch der sozialwissenschaftlichen Datenanalyse\" zu logist. Regression](https://link.springer.com/chapter/10.1007/978-3-531-92038-2_24)\n[^3]: Die Einschränkung auf männliche Befragte hat hier den einfachen Grund, dass so der Koeffizient größer ist \n\nArbeiten Sie mehr als die Hälfte Ihrer Arbeitszeit im Freien?\n   \nDie 1 steht dabei jeweils für \"ja\", die `2` für \"nein\". Wir verändern die Codierung aber so, dass die \"nein\"-Antworten mit \\texttt{0} versehen werden. Die neue Variable nennen wir `outside`. Außerdem teilen wir `F518_SUF` durch 100 und legen die so erstellte Variable \"Einkommen in 100EUR\" in `inc100` ab, um die Nachkommastellen des Koeffizienten zu reduzieren:\n\n\n::: {.cell}\n\n```{.r .cell-code}\netb18 <- haven::read_dta(\"./data/BIBBBAuA_2018_suf1.0.dta\",col_select = c(\"S1\",\"F605\",\"F518_SUF\")) %>% \n  filter(F605 < 9, F518_SUF < 99998, S1==1) %>% \n  mutate(inc100 = F518_SUF/100,\n         outside = 2-F605)\n\netb18 %>% count(outside,F605)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  outside      F605     n\n    <dbl> <dbl+lbl> <int>\n1       0  2 [nein]  7340\n2       1  1 [ja]    1136\n```\n:::\n\n```{.r .cell-code}\nsummary(etb18$inc100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.01   25.00   35.00   42.36   50.00  720.00 \n```\n:::\n:::\n\n\n\nWenn wir uns jetzt fragen, ob sich Befragte mit höherem Einkommen seltener im Freien arbeiten, hilft uns die OLS-Vorgehensweise nicht so richtig weiter. Die \"Punktewolke\" zur Optimierung der Abweichung zwischen tatsächlichen und vorhergesagten Werten (Residuen) sieht hier anders aus als bisher:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_log_reg_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=336}\n:::\n:::\n\nUm in R trotzdem ein \\texttt{lm}-Modell zu berechnen, könnten wir die abhängige Variable uminterpretieren. $\\hat{y}$ wird dann nicht mehr dichotom, sondern als metrische Wahrscheinlichkeit interpretiert, dass der Befragte mehr als die Hälfte der Arbeitszeit im Freien arbeitet (also die Wahrscheinlichkeit für outside = 1). Das können wir dann wie gehabt in eine Regressionsgleichung aufnehmen, zB. mit dem Einkommen als unabhängiger Variable:   \n\n\\begin{equation*}\n\\widehat{y_i} = P(outside\\texttt{\\small{=}}1) = \\hat\\beta0 + \\hat\\beta1 * \\texttt{inc100}_i\n\\end{equation*}\n\nAllerdings führt das zwangsläufig zu Verstößen gegen die Annahmen bzgl. der Residuen - die Fehler werden immer heteroskedastisch und nicht normalverteilt sein. Zudem wird es vorhergesagte Werte geben, die nicht sinnvoll interpretiert werden können, weil es mit 0 und 1 Grenzen gibt, jenseits derer Wahrscheinlichkeiten nicht existieren (zB gibt es keine negativen Wahrscheinlichkeiten).\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_log_reg_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=403.2}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggfortify)\nautoplot(m1,which = 1:2) # Homosk. & NV \n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](10_log_reg_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n## Logistische Linkfunktion\nUm diese Probleme zu umgehen, sind für dichotome abhängige Variablen logistische Regressionsmodelle ein sehr verbreitetes Vorgehen. Dafür werden neben dem bereits angesprochenen Schritt der Betrachtung von $\\hat{y}$ als Wahrscheinlichkeit zwei weitere Transformationen der abhängigen Variable vorgenommen:\n\n- *Odds statt Wahrscheinlichkeiten*: Um die obere Grenze des Wertebereichs der abhängigen Variablen auf $+\\infty$ auszudehnen, werden statt Wahrscheinlichkeiten Odds betrachtet. Odds sind definiert als der Quotient aus Wahrscheinlichkeit und der Gegenwahrscheinlichkeit für ein gegebenes Ereignis. In unserem Beispiel sind also die Odds dafür, dass ein*e Befragte*r angibt, sich nachts outside zu fühlen: $$Odds(outside=1) = \\frac{P(outside=1)}{P(outside=0)}= \\frac{P(outside=1)}{1-P(outside=1)} $$ \nDie Odds gehen gegen 0, je unwahrscheinlicher das betrachtete Ereignis ist. Für sehr wahrscheinliche Ereignisse nehmen die Odds Werte an, die gegen $+\\infty$ gehen, das Verhältnis zwischen Dividend (\"Zähler\") und Divisor (\"Nenner\") wird immer größer.\n\n- *Logits statt Odds*: Damit bleibt aber noch das Problem der negativen Werte bestehen: Auch Odds sind nur für [0;$+\\infty$] definiert. Um auch den negativen Wertebereich sinnvoll interpretierbar zu machen, werden die Odds logarithmiert, wir erhalten die sogenannten Logits: $$Logit(outside=1) = log(Odds(outside=1)) = log\\left(\\frac{P(outside=1)}{1-P(outside=1)}\\right)$$ \nDie Logarithmierung führt für Werte zwischen 0 und 1 zu negativen Werten, für Werte größer als 1 zu positiven Werten. \n\nDementsprechend gibt es bei logistischen Regressionen drei Einheiten:\n\n + Wahrscheinlichkeiten $P = \\frac{\\text{Anzahl Treffer}}{\\text{Anzahl aller Möglichkeiten}}$\n \n + $\\text{Odds} = \\frac{P}{1-P} = \\frac{\\text{Anzahl Treffer}}{\\text{Anzahl Nicht-Treffer}}$\n \n + $\\text{log-Odds/Logits} = log(Odds) = log( \\frac{\\text{Anzahl Treffer}}{\\text{Anzahl Nicht-Treffer}})$\n\n  \n  \n<br>  \n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ophurlgtxr\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ophurlgtxr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: hidden;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: hidden;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_title {\n  color: #333333;\n  font-size: small;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ophurlgtxr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ophurlgtxr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ophurlgtxr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ophurlgtxr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ophurlgtxr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ophurlgtxr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ophurlgtxr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ophurlgtxr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ophurlgtxr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ophurlgtxr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ophurlgtxr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ophurlgtxr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ophurlgtxr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ophurlgtxr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ophurlgtxr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ophurlgtxr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ophurlgtxr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ophurlgtxr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ophurlgtxr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ophurlgtxr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ophurlgtxr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ophurlgtxr .gt_left {\n  text-align: left;\n}\n\n#ophurlgtxr .gt_center {\n  text-align: center;\n}\n\n#ophurlgtxr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ophurlgtxr .gt_font_normal {\n  font-weight: normal;\n}\n\n#ophurlgtxr .gt_font_bold {\n  font-weight: bold;\n}\n\n#ophurlgtxr .gt_font_italic {\n  font-style: italic;\n}\n\n#ophurlgtxr .gt_super {\n  font-size: 65%;\n}\n\n#ophurlgtxr .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#ophurlgtxr .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ophurlgtxr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ophurlgtxr .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#ophurlgtxr .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#ophurlgtxr .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout: fixed;; width: 0px\">\n  <colgroup>\n    <col style=\"width:120px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:100px;\"/>\n    <col style=\"width:200px;\"/>\n  </colgroup>\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">$$P$$</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">$$Odds = \\frac{P}{1-P}$$</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">$$Logits = log(Odds)$$</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{1}{2}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$1$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 1:1</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>0</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{1}{3}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$0.5$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 1:2</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>-0.6931</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{1}{4}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$0.33$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 1:3</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>-1.0986</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{1}{5}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$0.25$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 1:5</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>-1.3863</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{2}{3}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$2$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 2:1</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>0.6931</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{3}{4}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$3$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>oder 3:1</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>1.0986</p>\n</div></td></tr>\n    <tr><td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$1$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>$$\\frac{1}{0}$$</p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p><em>sicher</em></p>\n</div></td>\n<td class=\"gt_row gt_left\"><div class='gt_from_md'><p>Inf</p>\n</div></td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n## Das logistische Regressionsmodell {#logmod}\n\nSomit sieht unser logistisches Regressionsmodell in der allgemeinen Schreibweise wie folgt aus:\n\n\\begin{equation*}\n\\widehat{Logit(outside=1)} = \\widehat{ln\\left(\\frac{P(outside=1)}{1-P(outside=1)}\\right)} = \\hat\\beta0 + \\hat{\\beta1}\\times \\texttt{inc100}\n\\end{equation*}\n\nIn R können wir ein solches Modell mit `glm()` und der Option `family=\"binomial\"` berechnen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- glm(outside ~ inc100, family = \"binomial\", data = etb18)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = outside ~ inc100, family = \"binomial\", data = etb18)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.9587  -0.6004  -0.4838  -0.3037   5.5210  \n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.538565   0.072672  -7.411 1.25e-13 ***\ninc100      -0.038690   0.002176 -17.781  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 6678.5  on 8475  degrees of freedom\nResidual deviance: 6241.5  on 8474  degrees of freedom\nAIC: 6245.5\n\nNumber of Fisher Scoring iterations: 6\n```\n:::\n:::\n\n\nDie Interpretation der $\\beta$ aus einem logistischen Regressionsmodell bezieht sich also auf die Logits (die logarithmierten Odds):  \n\n::: inter\n\nEs besteht ein am 0,001-Niveau signifikanter Zusammenhang zwischen dem Einkommen und der Wahrscheinlichkeit, im Freien zu arbeiten. Mit einem um 100 Euro höheren Einkommen gehen um 0.038690 niedrigere *Logits* einher, mehr als die Hälfte Ihrer Arbeitszeit im Freien zu arbeiten.\n:::\n\n## average marginal effects\n\nLogits sind aber sehr unhandlich - wie verändert sich jetzt aber die *Wahrscheinlichkeit* für $\\texttt{outside} = 1$ mit `inc100`? Hier haben wir das Problem, dass die Ableitung der \"rücktransformierten Funktion\" nicht so einfach ist wie im Fall der OLS. Verändern wir nämlich auch die [Regressionsgleichung von oben[^2]](#logmod) mit `exp()` und $p=\\frac{Odds}{1+Odds}$, so landen wir bei \n\n\\begin{equation*}\n\\widehat{P(outside=1)} = \\frac{e^{\\hat\\beta0+\\hat\\beta1 \\times \\texttt{inc100}}}{1+e^{\\hat\\beta0+\\hat{\\beta1}\\times \\texttt{inc100}}}\n\\end{equation*}\n\n[^2]: $\\widehat{Logit(outside=1)} = \\widehat{ln\\left(\\frac{P(outside=1)}{1-P(outside=1)}\\right)} = \\hat\\beta0 + \\hat{\\beta1}\\times \\texttt{inc100}$\n\n\nDiesen Ausdruck müssten wir nach `inc100` ableiten, um eine Antwort zu bekommen um wieviel sich die vorhergesagte Wahrscheinlichkeit für $\\texttt{outside} = 1$ mit einem um einen Euro höheren Befragteneinkommen verändert. Durch die Tatsache dass inc hier im Exponenten der e-Funktion und sowohl im Dividenden als auch Divisor (\"oben und unten\") steht, wird die Ableitung hier aber deutlich komplizierter als das in den bisherigen `lm()`-Modellen der Fall war. Für uns ist an dieser Stelle aber nur wichtig, dass wir für die Berechnung der Veränderung der vorhergesagten Wahrscheinlichkeiten die sog. marginalen Effekte aus dem Paket `{marginaleffects}` brauchen. Darin findet sich der Befehl , welcher uns erlaubt ein $\\beta$ zwischen dem Einkommen und der Wahrscheinlichkeit, dass der\\*die Befragte sich outside fühlt, zu berechnen. Dieses wird auch als average marginal effect bezeichnet, da sie den *durchschnittlichen marginalen Effekt* der betrachteten unabhängigen Variable auf die abhängige Variable wiedergeben. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"marginaleffects\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmfx <- marginaleffects::marginaleffects(m2)\nsummary(mfx)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAverage marginal effects \n    Term    Effect Std. Error z value   Pr(>|z|)     2.5 %    97.5 %\n1 inc100 -0.004275  0.0002404  -17.78 < 2.22e-16 -0.004747 -0.003804\n\nModel type:  glm \nPrediction type:  response \n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n::: inter\n\nMit einem um 100 Euro (`inc100` ist in 100 EUR gemessen) höheren Einkommen geht im Durchschnitt eine um 0.0043 (0.43 Prozentpunkte)  geringere Wahrscheinlichkeit einher,  mehr als die Hälfte Ihrer Arbeitszeit im Freien zu arbeiten.\n\n:::\n\n\n## Hintergrund zu average marginal effects\n\n### Vorhergesagte Werte\n\nZunächst stellt sich die Frage, was Logits denn bedeuten. Eigentlich möchten wir ja Wahrscheinlichkeiten im Wertebereich zwischen 0 und 1 (bzw. 0% und 100%) als Interpretationseinheit haben. Die Berechnung eines vorhergesagten Werts für einen Befragten mit einem Einkommen von 1000 Euro (`inc100`=10) ergibt durch einsetzen bzw. `predict()` natürlich auch die Logits:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Estimate  Std. Error    z value     Pr(>|z|)\n(Intercept) -0.53856546 0.072671654  -7.410943 1.254049e-13\ninc100      -0.03868975 0.002175903 -17.781005 9.918525e-71\n```\n:::\n\n```{.r .cell-code}\n-0.53856546   + -0.03868975 * 10\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.925463\n```\n:::\n\n```{.r .cell-code}\npredict(m2, data.frame(inc100 = 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         1 \n-0.9254629 \n```\n:::\n:::\n\n\n    \n::: inter\n\nBefragte mit einem Einkommen von 1000EUR haben dem Modell zu Folge Logits von -0.92546, mehr als die Hälfte der Arbeitszeit im Freien zu arbeiten.\n\n:::\n\nUm an die Wahrscheinlichkeit für `outside` = 1 zu bekommen, müssen wir die Transformationsschritte sozusagen \"rückabwickeln\"! Dafür müssen wir zunächst mit `exp` den `ln()` vor den Odds heraus rechnen und können dann durch die die Formel $p=\\frac{Odds}{1+Odds}$ die Wahrscheinlichkeit aus den odds berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\nlogits <- -0.9254629 \nexp(logits) # Odds statt Logits\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3963479\n```\n:::\n\n```{.r .cell-code}\nodds <- exp(logits) \nodds/(1+odds) # Wahrscheinlichkeit statt Odds \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2838461\n```\n:::\n\n```{.r .cell-code}\nexp(logits)/(1+exp(logits)) # beide Schritte auf einmal\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2838461\n```\n:::\n:::\n\n\n    \n::: inter\n\nDie Wahrscheinlichkeit, dass ein Befragter mit einem Einkommen von 1000 Euro angibt, mehr als die Hälfte Ihrer Arbeitszeit im Freien zu arbeiten, liegt also unserem Modell zu Folge bei 28.385\\%.   \n\n::: \n\nMit der Option `type=\"response\"` können wir das auch mit `predict()` direkt berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(m2, data.frame(inc100 = 10), type=\"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1 \n0.2838461 \n```\n:::\n:::\n\n\n### Die Idee von average marginal effects\n\nWie verändern sich dann die vorhergesagten Werte, wenn wir `inc100` um eine Einheit (also 100€) erhöhen? Die Logits verändern sich pro Einheit `inc100` natürlich genau um $\\hat\\beta1$, also hier -0.03869. Um sich die Steigung an einigen Werten anzusehen, berechnen wir jeweils die Abstände der vorhergesagten Werte für $x-0.5$ und $x+0.5$:\n\n\n*Um die Werte jeweils mit dem eingesetzten Wert zu beschriften, stellen wir den Wert mit * `\"\"=` *voran:*\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(m2, data.frame(inc100=c(\"54.5\"=54.5,\"55.5\"=55.5,\"64.5\"=64.5,\"65.5\"=65.5,\n                                \"74.5\"=74.5,\"75.5\"=75.5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     54.5      55.5      64.5      65.5      74.5      75.5 \n-2.647157 -2.685846 -3.034054 -3.072744 -3.420952 -3.459641 \n```\n:::\n:::\n\n\nDie Differenzen sind immer gleich - entsprechend der Interpretation gehen mit einem um eine Einheit höheren `inc100` um 0.03869 höhere Logits einher, dass die Befragten mehr als die Hälfte Ihrer Arbeitszeit im Freien arbeiten:\n\n+ Steigung bei `inc100` = 55: -2.68585 $-$ -2.64716 = -0.03869  \\quad\\textsf{\\small{Vorhersage bei 55.5 - Vorhersage bei 54.5}}\n\n+ Steigung bei `inc100` = 65: -3.07274 $-$ -3.03405 = -0.03869  \\quad\\textsf{\\small{Vorhersage bei 56.5 - Vorhersage bei 64.5}}\n\n+ Steigung bei `inc100` = 75: -3.45964 $-$ -3.42095 = -0.03869  \\quad\\textsf{\\small{Vorhersage bei 75.5 - Vorhersage bei 74.5}}\n\nWenn wir uns diese Schritte aber jeweils für die vorhergesagten Wahrscheinlichkeiten ansehen, sieht das aber anders aus:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(m2, data.frame(inc100=c(\"54.5\"=54.5,\"55.5\"=55.5,\"64.5\"=64.5,\"65.5\"=65.5,\n                                \"74.5\"=74.5,\"75.5\"=75.5)), type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      54.5       55.5       64.5       65.5       74.5       75.5 \n0.06616447 0.06381371 0.04591091 0.04424565 0.03164705 0.03048263 \n```\n:::\n:::\n\n\nHier werden die Differenzen mit zunehmendem `inc100` immer kleiner:\n\n+ Steigung bei `inc100` = 55: 0.06381 $-$ 0.06616 = -0.00235  \\quad\\textsf{\\small{Vorhersage bei 55.5 - Vorhersage bei 54.5}}\n\n+ Steigung bei `inc100` = 65: 0.04425 $-$ 0.04591 = -0.00167  \\quad\\textsf{\\small{Vorhersage bei 65.5 - Vorhersage bei 64.5}}\n\n+ Steigung bei `inc100` = 75: 0.03048 $-$ 0.03165 = -0.00116  \\quad\\textsf{\\small{Vorhersage bei 75.5 - Vorhersage bei 74.5}}\n\n\n\n\n\n::: {.cell layout-align=\"center\" fig.caption='true'}\n::: {.cell-output-display}\n![](10_log_reg_files/figure-html/AME1-1.png){fig-align='center' width=672}\n:::\n:::\n\n::: {.cell layout-align=\"center\" fig.caption='true'}\n::: {.cell-output-display}\n![](10_log_reg_files/figure-html/AME2-1.png){fig-align='center' width=672}\n:::\n:::\n\nDiese Steigungen werden für alle Beobachtungen aus dem zu Grunde liegenden Datensatz aufsummiert und dann der Durchschnitt gebildet ($\\rightarrow$ *average* marginal effects)\n",
    "supporting": [
      "10_log_reg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}