<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.520">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R am BIBB - 3&nbsp; Überblick erhalten: Tabellen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04_viz.html" rel="next">
<link href="./02_intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Überblick erhalten: Tabellen</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R am BIBB</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Herzlich Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einstieg in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Arbeiten mit Datensätzen in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_desc.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Überblick erhalten: Tabellen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_viz.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Kontingenztabellen &amp; Visualisierung</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_reg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Regressionsmodelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#kategoriale-merkmale" id="toc-kategoriale-merkmale" class="nav-link active" data-scroll-target="#kategoriale-merkmale"> <span class="header-section-number">3.1</span> Kategoriale Merkmale</a>
  <ul class="collapse">
  <li><a href="#absolute-häufigkeiten" id="toc-absolute-häufigkeiten" class="nav-link" data-scroll-target="#absolute-häufigkeiten"> <span class="header-section-number">3.1.1</span> Absolute Häufigkeiten</a></li>
  <li><a href="#NA_w103" id="toc-NA_w103" class="nav-link" data-scroll-target="#NA_w103"> <span class="header-section-number">3.1.2</span> fehlende Werte mit NA überschreiben</a></li>
  <li><a href="#kumulierte-häufigkeiten" id="toc-kumulierte-häufigkeiten" class="nav-link" data-scroll-target="#kumulierte-häufigkeiten"> <span class="header-section-number">3.1.3</span> Kumulierte Häufigkeiten</a></li>
  <li><a href="#relative-häufigkeiten-anteile" id="toc-relative-häufigkeiten-anteile" class="nav-link" data-scroll-target="#relative-häufigkeiten-anteile"> <span class="header-section-number">3.1.4</span> Relative Häufigkeiten (Anteile)</a></li>
  <li><a href="#übersichtstabelle-mit-allen-kennzahlen" id="toc-übersichtstabelle-mit-allen-kennzahlen" class="nav-link" data-scroll-target="#übersichtstabelle-mit-allen-kennzahlen"> <span class="header-section-number">3.1.5</span> Übersichtstabelle mit allen Kennzahlen</a></li>
  </ul></li>
  <li><a href="#metrische-variablen" id="toc-metrische-variablen" class="nav-link" data-scroll-target="#metrische-variablen"> <span class="header-section-number">3.2</span> Metrische Variablen</a></li>
  <li><a href="#aufgaben" id="toc-aufgaben" class="nav-link" data-scroll-target="#aufgaben"> <span class="header-section-number">3.3</span> Aufgaben</a></li>
  <li><a href="#profi-aufgaben" id="toc-profi-aufgaben" class="nav-link" data-scroll-target="#profi-aufgaben"> <span class="header-section-number">3.4</span> Profi-Aufgaben</a></li>
  <li><a href="#hinweise" id="toc-hinweise" class="nav-link" data-scroll-target="#hinweise"> <span class="header-section-number">3.5</span> Hinweise</a>
  <ul class="collapse">
  <li><a href="#hinweis_cut_w103" id="toc-hinweis_cut_w103" class="nav-link" data-scroll-target="#hinweis_cut_w103"> <span class="header-section-number">3.5.1</span> cut wählt ein ungünstiges Zahlenformat</a></li>
  <li><a href="#relative-häufigkeiten-runden" id="toc-relative-häufigkeiten-runden" class="nav-link" data-scroll-target="#relative-häufigkeiten-runden"> <span class="header-section-number">3.5.2</span> Relative Häufigkeiten runden</a></li>
  <li><a href="#wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" id="toc-wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" class="nav-link" data-scroll-target="#wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen"> <span class="header-section-number">3.5.3</span> Wie kann ich mir in R automatisch die häufigste/seltenste Ausprägung ausgeben lassen?</a></li>
  <li><a href="#labels-als-neue-spalte-hinzufügen" id="toc-labels-als-neue-spalte-hinzufügen" class="nav-link" data-scroll-target="#labels-als-neue-spalte-hinzufügen"> <span class="header-section-number">3.5.4</span> Labels als neue Spalte hinzufügen</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="tab" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Überblick erhalten: Tabellen</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>In der vorherigen Sitzung hatten wir gesehen, wie wir Datensätze importieren und damit arbeiten. In dieser Session werden wir sehen, wie wir uns mit Tabellen einen Überblick über die Informationen in einem Datensatz verschaffen können. Wir werden auch in dieser Session mit dem Allbus 2016 arbeiten. Zunächst müssen wir dazu die Daten wieder wie vergangene Woche einlesen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"..."</span>) <span class="co"># wo liegt der Datensatz?</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>a16 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"allbus2016_kompakt.csv"</span>,<span class="at">sep =</span> <span class="st">";"</span>,<span class="at">header =</span> T,<span class="at">stringsAsFactors =</span> F) <span class="co"># einlesen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="kategoriale-merkmale" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="kategoriale-merkmale"><span class="header-section-number">3.1</span> Kategoriale Merkmale</h2>
<section id="absolute-häufigkeiten" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="absolute-häufigkeiten"><span class="header-section-number">3.1.1</span> Absolute Häufigkeiten</h3>
<p>Zentraler Befehl für die Auszählung von Häufigkeiten ist der <code>table()</code> Befehl. Beispielsweise mit der Variable <code>german</code> (Details im Codebuch).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>Wir bekommen hier also die absoluten Häufigkeiten angezeigt. In der ersten Zeile werden die verschiedenen Ausprägungen aufgelistet, in der zweiten Zeile stehen dann die Häufigkeiten. Aus dem Codebuch erfahren wir, für welche inhaltlichen Kategorien die Zahlencodes jeweils stehen. Bspw. steht <code>1</code> dafür, dass der*die Befragte die deutsche Staatsbürgerschaft besitzt. Wir können auch Tabellen unter einem frei wählbaren Namen ablegen und später wieder aufrufen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>t1 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>3238 Befragte haben also nur die deutsche Staatsbürgerschaft, 33 Befragte haben die deutsche und noch eine weitere Staatsbürgerschaft. Außerdem enthält der Datensatz 216 Befragte ohne deutsche Staatsbürgerschaft.</p>
<p>Etwas störend ist aber noch die <code>-32</code>. Aus dem Codebuch erfahren wir, dass <code>-32</code> für fehlende Angabe steht:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in knitr::include_graphics("D:/oCloud/RFS/images/
103_german_codebuch.png"): It is highly recommended to use relative paths for
images. You had absolute paths: "D:/oCloud/RFS/images/103_german_codebuch.png"</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="D:/oCloud/RFS/images/103_german_codebuch.png" style="width:53.0%;height:53.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="NA_w103" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="NA_w103"><span class="header-section-number">3.1.2</span> fehlende Werte mit NA überschreiben</h3>
<p>Um die Werte mit <code>-32</code> auch in R als fehlende Angabe zu kennzeichnen, müssen wir sie auf <code>NA</code> setzen. Dazu rufen wir <code>a16$german</code> auf und filtern mit <code>[]</code> nur die Werte für <code>german</code> gleich <code>-32</code> heraus. Vergangene Woche haben wir kennengelernt, dass wir so spezifische Werte aufrufen können:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="co"># nur german = -32 aufrufen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -32 -32 -32</code></pre>
</div>
</div>
<p>Wenn wir daran mit <code>&lt;-</code> einen neuen Wert angeben, werden die aufgerufenen Werte damit überschrieben - hier überschreiben wir also alle Werte für <code>german == -32</code> mit <code>NA</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Wir könnten auch einfach alle Werte kleiner 0 auswählen:</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>NA</code> ist in der R der Code für fehlende Angaben, sie werden dann in <code>table()</code> nicht aufgeführt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
3238   33  216 </code></pre>
</div>
</div>
<p>Wir können aber mit der Option <code>exclude = NULL</code> die Auszählung von <code>NA</code> explizit anfordern:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german, <span class="at">exclude =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 &lt;NA&gt; 
3238   33  216    3 </code></pre>
</div>
</div>
<p><strong>Achtung!</strong> Die vor dem Ausschluss von <code>-32</code> abgespeicherte Tabelle <code>t1</code> ändert sich dadurch nicht:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>t1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>Das liegt daran, dass bei Aufruf von <code>t1</code> die abgelegten Werte, so wie sie gespeichert wurden, wieder aufgerufen werden. Es wird <strong>keine neue Auszählung</strong> vorgenommen! Möchten wir die aktualisierte Tabelle ohne die <code>NA</code> in <code>t1</code> ablegen, dann müssen wir <code>t1</code> mit den neuen Werten überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>t1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
3238   33  216 </code></pre>
</div>
</div>
</section>
<section id="kumulierte-häufigkeiten" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="kumulierte-häufigkeiten"><span class="header-section-number">3.1.3</span> Kumulierte Häufigkeiten</h3>
<p>Mit <code>cumsum()</code> können wir uns die <em>kumulierten</em> Häufigkeiten ausgeben lassen. Dazu wenden wir <code>cumsum</code> auf die Häufigkeitstabelle an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2    3 
3238 3271 3487 </code></pre>
</div>
</div>
<p><em>Was sagen die Zahlen jetzt aus? 3271 Befragte haben die deutsche und evtl. noch eine weitere Staatsbürgerschaft. Für 3487 Befragte liegt eine Angabe zur Staatsbürgerschaft vor.</em></p>
<p>Die Befehlsschachtel aus <code>table()</code> und <code>cumsum()</code> können wir durch ein schrittweises Vorgehen auflösen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german) <span class="co"># ablegen wie oben</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(t1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2    3 
3238 3271 3487 </code></pre>
</div>
</div>
</section>
<section id="relative-häufigkeiten-anteile" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="relative-häufigkeiten-anteile"><span class="header-section-number">3.1.4</span> Relative Häufigkeiten (Anteile)</h3>
<p>Neben den absoluten Häufigkeiten können wir uns auch relative Häufigkeitstabellen anzeigen lassen. Dazu nutzen wir den <code>prop.table()</code> Befehl und wenden diesen wiederum entweder auf <code>table()</code> oder direkt auf <code>t1</code> an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
0.928591913 0.009463722 0.061944365 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(t1) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
0.928591913 0.009463722 0.061944365 </code></pre>
</div>
</div>
<p><em>Wir sehen hier also, dass 92.859% aller Befragten nur die deutsche Staatsbürgerschaft haben.</em></p>
<p>Auch die relativen Häufigkeiten können wir uns als kumulierte Werte ausgeben lassen, dazu kombinieren wir <code>prop.table()</code> mit <code>cumsum()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.9285919 0.9380556 1.0000000 </code></pre>
</div>
</div>
<p>Diese Befehlsschachtel können wir wieder vermeiden indem wir die absoluten Häufigkeiten aus <code>t1</code> aufrufen und dann die relativen Häufigkeiten unter <code>t2</code> ablegen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(t1) <span class="co"># relative Häufigkeiten unter t2 ablegen</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(t2) <span class="co"># relative kumulierte Häufigkeiten </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.9285919 0.9380556 1.0000000 </code></pre>
</div>
</div>
<p><em>Wir sehen hier also, dass 93.806% aller Befragten die deutsche und evtl. eine weitere Staatsbürgerschaft haben.</em></p>
</section>
<section id="übersichtstabelle-mit-allen-kennzahlen" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="übersichtstabelle-mit-allen-kennzahlen"><span class="header-section-number">3.1.5</span> Übersichtstabelle mit allen Kennzahlen</h3>
<p>Dies alles lässt sich zu einer Gesamttabelle im Format eines Datensatzes zusammenfassen. Dazu legen wir zunächst die absoluten Häufigkeiten in einem <code>data.frame</code> unter <code>t3</code> ab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german) <span class="co"># wie bereits oben</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(t1) <span class="co"># t1 in einen Datensatz umformatieren</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq
1    1 3238
2    2   33
3    3  216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(t3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>Diesem <code>data.frame</code> fügen wir dann mit <code>t3$...</code> neue Variablen/Spalten hinzu. Während wir uns oben jeweils auf <code>t1</code> für die absoluten Häufigkeiten bezogen hatten, finden wir diese jetzt innerhalb von <code>t3</code> in der Spalte <code>Freq</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>H <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(t3<span class="sc">$</span>Freq) <span class="co"># kum. absolute Häufigkeiten</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H
1    1 3238 3238
2    2   33 3271
3    3  216 3487</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>f <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(t3<span class="sc">$</span>Freq) <span class="co"># rel. Häufigkeiten</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H           f
1    1 3238 3238 0.928591913
2    2   33 3271 0.009463722
3    3  216 3487 0.061944365</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>F <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(t3<span class="sc">$</span>f) <span class="co"># kum. rel. Häufigkeiten</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H           f         F
1    1 3238 3238 0.928591913 0.9285919
2    2   33 3271 0.009463722 0.9380556
3    3  216 3487 0.061944365 1.0000000</code></pre>
</div>
</div>
<p>Zum Schluss können wir mit <code>colnames</code> die Spalten klar benennen. Dazu rufen wir mit <code>colnames(t3)</code> die Spaltennamen von <code>t3</code> auf und überschreiben diese dann mit einer Folge an Werten, die wir mit <code>c()</code> angeben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(t3) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Werte"</span>, <span class="st">"h"</span>, <span class="st">"H"</span>, <span class="st">"f"</span>, <span class="st">"F"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>t3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H           f         F
1     1 3238 3238 0.928591913 0.9285919
2     2   33 3271 0.009463722 0.9380556
3     3  216 3487 0.061944365 1.0000000</code></pre>
</div>
</div>
</section>
</section>
<section id="metrische-variablen" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="metrische-variablen"><span class="header-section-number">3.2</span> Metrische Variablen</h2>
<p>Das bisherige Beispiel Staatsbürgerschaft (<code>german</code>) bezog sich auf ein kategoriales Merkmal. Für ein metrisches Merkmal, wie zum Beispiel das Geburtsjahr macht eine Häufigkeitstabelle wenig Sinn, da das Geburtsjahr sehr viele Ausprägungen hat und eine Tabelle unübersichtlich wäre - hier nur als Beispiel die ersten 20 Ausprägungen (es gibt insgesamt 77!):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
-32  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
  4  29  41  43  43  41  45  34  40  48  36  49  43  58  49  47  51  65  54  42 </code></pre>
</div>
</div>
<p>Um eine Häufigkeitstabelle zu erstellen müssen wir bei metrischen Merkmalen Klassen bilden. So könnten wir das Alter in Lebensjahrzehnte unterteilen. Zuvor müssen wir wieder die fehlenden Angaben<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age[a16<span class="sc">$</span>age <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Um die Klassen zu bilden, nutzen wir <code>cut()</code> und geben neben der zu unterteilenden Variable mit <code>breaks</code> die Klassengrenzen an. Für die Grenzen können wir <code>seq()</code> verwenden. Darin geben wir zunächst die obere und untere Grenze an und dann die Schrittbreiten. Diese Werte legen wir in einer neuen Variable in <code>a16</code> ab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age_zehner <span class="ot">&lt;-</span> <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">90</span>,<span class="dv">100</span>) )</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age_zehner <span class="ot">&lt;-</span> <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">10</span>,<span class="dv">100</span>,<span class="dv">10</span>) ) <span class="co"># kürzer mit seq()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für diese neue Variable können wir mit <code>table()</code> eine Häufigkeitstabelle anfordern:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>age_zehner)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 (10,20]  (20,30]  (30,40]  (40,50]  (50,60]  (60,70]  (70,80]  (80,90] 
     113      437      491      605      710      579      419      127 
(90,100] 
       5 </code></pre>
</div>
</div>
<p><code>(</code> bedeutet dabei ausgeschlossen, <code>]</code> inklusive. Es gibt also 437 Befragte, die über 20 bis inklusive 30 Jahre alt sind.<br>
Wir haben also durch Klassierung aus dem metrischen Merkmal <code>age</code> ein kategoriales Merkmal <code>age_zehner</code> erstellt. Damit können wir dann genauso arbeiten wie oben - zB für die kumulierten relativen Häufigkeiten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>age_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>age_zehner) <span class="co"># abs Häufigkeiten</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>age_tab2 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(age_tab) <span class="co"># rel Häufigkeiten</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(age_tab2) <span class="co"># kumulieren</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] 
0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 
   (80,90]   (90,100] 
0.99856569 1.00000000 </code></pre>
</div>
</div>
<p><em>Wir sehen hier so, dass 47.217% aller Befragten 50 Jahre oder jünger sind.</em></p>
<p>Wir könnten alles auch in einem Befehl zusammen durchführen, das wird aber schnell unübersichtlich:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>( <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">10</span>,<span class="dv">100</span>,<span class="dv">10</span>) ) )))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] 
0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 
   (80,90]   (90,100] 
0.99856569 1.00000000 </code></pre>
</div>
</div>
</section>
<section id="aufgaben" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="aufgaben"><span class="header-section-number">3.3</span> Aufgaben</h2>
<ol type="1">
<li>Laden Sie den Allbusdatensatz <code>allbus_kompakt.csv</code> mit dem csv-Import in R:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"..."</span>) <span class="co"># wo liegt der Datensatz?</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>a16 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"allbus2016_kompakt.csv"</span>,<span class="at">sep =</span> <span class="st">";"</span>,<span class="at">header =</span> T,<span class="at">stringsAsFactors =</span> F) <span class="co"># einlesen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Wir interessieren uns für die Variable <code>gkpol</code>.</li>
</ol>
<ul>
<li>Suchen Sie die Variable im Codebuch: welche Information können Sie dieser Variable entnehmen?</li>
<li>Welches Skalenniveau hat die Variable? (inhaltliche Frage, keine R-Frage)</li>
<li>Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten?</li>
<li>Lassen Sie sich eine Tabelle mit den absoluten Häufigkeiten anzeigen. Welche ist die häufigste Ausprägung, wofür steht die Kategorie? (Sehen Sie im Codebuch nach)</li>
<li>Hat die Variable fehlende Werte, die Sie ausschließen sollten? Falls ja, ersetzen Sie diese Werte mit <code>NA</code> und lassen Sie sich die Tabelle erneut ausgeben.</li>
</ul>
<ol start="3" type="1">
<li>Erstellen Sie eine vollständige Häufigkeitstabelle für die Variable <code>gkpol</code>, welche folgende Informationen enthält:</li>
</ol>
<ul>
<li>absolute Häufigkeiten</li>
<li>relative Häufigkeiten</li>
<li>kumulierte absolute Häufigkeiten</li>
<li>kumulierte relative Häufigkeiten</li>
<li>Wie viele Befragte leben in einem Ort mit höchstens 49.999 Einwohnern?</li>
<li>Wie groß ist der Anteil der Befragten, die in einem Ort mit höchstens 99.999 Einwohnern leben?</li>
<li>Wie groß ist der Anteil der Befragten, die in einem Ort mit <em>mindestens</em> 100.000 Einwohnern leben?</li>
</ul>
<ol start="4" type="1">
<li>Erstellen Sie eine Häufigkeitstabelle für das Geburtsjahr der Befragten (<code>yborn</code>)!</li>
</ol>
<ul>
<li>Welches Skalenniveau hat die Variable? (inhaltliche Frage, keine R-Frage)</li>
<li>Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten? Beachten Sie dazu auch die <a href="#hinweis_cut_w103">Hinweise</a> am Ende dieses Dokuments. Verwenden Sie die Jahrzehntgrenzen ab 1910.</li>
<li>Erstellen Sie eine Tabelle welche die absoluten Häufigkeiten anzeigt</li>
<li>Gibt es fehlende Werte, die Sie mit <code>NA</code> überschreiben sollten?</li>
<li>Erstellen Sie eine zweite Version dieser Tabelle mit relativen Häufigkeiten</li>
<li>Wie groß ist der Anteil der Befragten, die bis 1970 geboren wurden?</li>
<li>Wie groß ist der Anteil der Befragten, die nach 1980 geboren wurden?</li>
</ul>
</section>
<section id="profi-aufgaben" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="profi-aufgaben"><span class="header-section-number">3.4</span> Profi-Aufgaben</h2>
<p>Für alle, die noch etwas mehr machen möchten:</p>
<ul>
<li>Runden Sie die Angaben zur relativen Häufigkeit auf 3 Nachkommastellen!</li>
<li>Lassen Sie sich von R die häufigste Ausprägung für <code>yborn</code> ausgeben</li>
<li>Fügen Sie der vollständigen Häufigkeitstabelle für die Variable <code>gkpol</code> eine neue Spalte hinzu, welche die Bedeutung der Zahlencodes wiedergibt!</li>
</ul>
<p>Tipps dazu finden Sie in den Hinweisen am Ende! (Wissen aus diesen Aufgaben wird nicht vorausgesetzt in den kommenden Wochen, aber es hilft natürlich)</p>
</section>
<section id="hinweise" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="hinweise"><span class="header-section-number">3.5</span> Hinweise</h2>
<section id="hinweis_cut_w103" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="hinweis_cut_w103"><span class="header-section-number">3.5.1</span> cut wählt ein ungünstiges Zahlenformat</h3>
<p><code>cut</code> verwendet für Klassengrenzen mit mehr als 3 Stellen eine wenig intuitive Darstellung. Mit <code>dig.lab</code> können Labels mit mehr als 3 Stellen angefordert werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1212</span>,<span class="dv">2121</span>,<span class="dv">1212</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( <span class="fu">cut</span>(x1, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1500</span>,<span class="dv">2500</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      (0,1.5e+03] (1.5e+03,2.5e+03] 
                2                 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( <span class="fu">cut</span>(x1, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1500</span>,<span class="dv">2500</span>), <span class="at">dig.lab =</span> <span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   (0,1500] (1500,2500] 
          2           1 </code></pre>
</div>
</div>
</section>
<section id="relative-häufigkeiten-runden" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="relative-häufigkeiten-runden"><span class="header-section-number">3.5.2</span> Relative Häufigkeiten runden</h3>
<p>Erläuterung: Sie können mit <code>round(x , 3)</code> Werte auf eine gewisse Zahl von Ziffern runden. Die zweite Zahl in der Klammer (nach dem Komma) gibt an, wieviele Dezimalstellen wir möchten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.12121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21</code></pre>
</div>
</div>
<p>Wir können also die relativen Häufigkeiten runden und so die Tabelle von oben übersichtlicher machen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H           f         F
1     1 3238 3238 0.928591913 0.9285919
2     2   33 3271 0.009463722 0.9380556
3     3  216 3487 0.061944365 1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>f <span class="ot">&lt;-</span> <span class="fu">round</span>(t3<span class="sc">$</span>f,<span class="dv">3</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>F <span class="ot">&lt;-</span> <span class="fu">round</span>(t3<span class="sc">$</span>F,<span class="dv">3</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F
1     1 3238 3238 0.929 0.929
2     2   33 3271 0.009 0.938
3     3  216 3487 0.062 1.000</code></pre>
</div>
</div>
</section>
<section id="wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen"><span class="header-section-number">3.5.3</span> Wie kann ich mir in R automatisch die häufigste/seltenste Ausprägung ausgeben lassen?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>age)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>t1[<span class="fu">which</span>(t1 <span class="sc">==</span> <span class="fu">max</span>(t1))] <span class="co"># Modus</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>48 
87 </code></pre>
</div>
</div>
<p><code>age=48</code> ist mit <code>87</code> Befragten die häufigste Ausprägung.</p>
</section>
<section id="labels-als-neue-spalte-hinzufügen" class="level3" data-number="3.5.4">
<h3 data-number="3.5.4" class="anchored" data-anchor-id="labels-als-neue-spalte-hinzufügen"><span class="header-section-number">3.5.4</span> Labels als neue Spalte hinzufügen</h3>
<p>Wir können die Übersichtstabelle auch noch beschriften, indem wir eine Textvariable hinzufügen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>t3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F
1     1 3238 3238 0.929 0.929
2     2   33 3271 0.009 0.938
3     3  216 3487 0.062 1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dt Staatsbürgerschaft"</span>,<span class="st">"dt und andere Staatsbürgerschaft"</span>,</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"andere Staatsbürgerschaft"</span>)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F                           labels
1     1 3238 3238 0.929 0.929            dt Staatsbürgerschaft
2     2   33 3271 0.009 0.938 dt und andere Staatsbürgerschaft
3     3  216 3487 0.062 1.000        andere Staatsbürgerschaft</code></pre>
</div>
</div>


</section>
</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1" role="doc-endnote"><p>Die Werte für fehlende Angaben finden wir Codebuch: auch hier ist <code>-32</code> wieder ein Code für fehlende Werte.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./02_intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Arbeiten mit Datensätzen in R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04_viz.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Kontingenztabellen &amp; Visualisierung</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>