{
  "hash": "7b4b8d49324232096860385c89c9e950",
  "result": {
    "markdown": "# Einen Überblick erhalten {#tab}\n\n\n\n\n\nIn der vorherigen Sitzung hatten wir gesehen, wie wir Datensätze importieren und damit arbeiten. Jede statistische Auswertung eines Datensatzes startet mit einer Beschreibung der Variablen. In dieser Session werden wir sehen, wie wir uns mit Tabellen einen Überblick über die Informationen in einem Datensatz verschaffen können. Wir werden auch in dieser Session mit dem Allbus 2016 arbeiten. Zunächst müssen wir dazu die Daten wieder wie vergangene Woche einlesen:\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"...\") # wo liegt der Datensatz?\na16 <- read.table(\"allbus2016_kompakt.csv\",sep = \";\",header = T,stringsAsFactors = F) # einlesen\n```\n:::\n\n\n## Kategoriale Merkmale\n### Absolute Häufigkeiten\nZentraler Befehl für die Auszählung von Häufigkeiten ist der `table()` Befehl. Beispielsweise mit der Variable `german` (Details im Codebuch).\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$german)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n -32    1    2    3 \n   3 3238   33  216 \n```\n:::\n:::\n\nWir bekommen hier also die absoluten Häufigkeiten angezeigt. In der ersten Zeile werden die verschiedenen Ausprägungen aufgelistet, in der zweiten Zeile stehen dann die Häufigkeiten. Aus dem Codebuch erfahren wir, für welche inhaltlichen Kategorien die Zahlencodes jeweils stehen. Bspw. steht `1` dafür, dass der*die Befragte die deutsche Staatsbürgerschaft besitzt.\nWir können auch Tabellen unter einem frei wählbaren Namen ablegen und später wieder aufrufen:\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- table(a16$german)\nt1 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n -32    1    2    3 \n   3 3238   33  216 \n```\n:::\n:::\n\n\n3238 Befragte haben also nur die deutsche Staatsbürgerschaft, 33 Befragte haben die deutsche und noch eine weitere Staatsbürgerschaft. Außerdem enthält der Datensatz 216 Befragte ohne deutsche Staatsbürgerschaft.   \n\nEtwas störend ist aber noch die `-32`. Aus dem Codebuch erfahren wir, dass `-32` für fehlende Angabe steht:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../../../../RFS/images/103_german_codebuch.png){fig-align='center' width=53% height=53%}\n:::\n:::\n\n\n## Fehlende Werte in R: `NA` {#NA_w103}\n\nUm die Werte mit `-32` auch in R als fehlende Angabe zu kennzeichnen, müssen wir sie auf `NA` setzen. Dazu rufen wir `a16$german` auf und filtern mit `[]` nur die Werte für `german` gleich `-32` heraus. Vergangene Woche haben wir kennengelernt, dass wir so spezifische Werte aufrufen können:\n\n::: {.cell}\n\n```{.r .cell-code}\na16$german[a16$german == -32] # nur german = -32 aufrufen\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -32 -32 -32\n```\n:::\n:::\n\nWenn wir daran mit `<-` einen neuen Wert angeben, werden die aufgerufenen Werte damit überschrieben - hier überschreiben wir also alle Werte für `german == -32` mit `NA`: \n\n::: {.cell}\n\n```{.r .cell-code}\na16$german[a16$german == -32] <- NA\n# Wir könnten auch einfach alle Werte kleiner 0 auswählen:\na16$german[a16$german < 0] <- NA\n```\n:::\n\n\n`NA` ist in der R der Code für fehlende Angaben, sie werden dann in `table()` nicht aufgeführt:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$german)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3 \n3238   33  216 \n```\n:::\n:::\n\nWir können aber mit der Option `exclude = NULL` die Auszählung von `NA` explizit anfordern:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$german, exclude = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3 <NA> \n3238   33  216    3 \n```\n:::\n:::\n\n**Achtung!** Die vor dem Ausschluss von `-32` abgespeicherte Tabelle `t1` ändert sich dadurch nicht:\n\n::: {.cell}\n\n```{.r .cell-code}\nt1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n -32    1    2    3 \n   3 3238   33  216 \n```\n:::\n:::\n\nDas liegt daran, dass bei Aufruf von `t1` die abgelegten Werte, so wie sie gespeichert wurden, wieder aufgerufen werden. Es wird **keine neue Auszählung** vorgenommen! Möchten wir die aktualisierte Tabelle ohne die `NA` in `t1` ablegen, dann müssen wir `t1` mit den neuen Werten überschreiben:\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- table(a16$german)\nt1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3 \n3238   33  216 \n```\n:::\n:::\n\n\n[*The missing book*](https://tmb.njtierney.com/)\n\n### Kumulierte Häufigkeiten\nMit `cumsum()` können wir uns die *kumulierten* Häufigkeiten ausgeben lassen. Dazu wenden wir `cumsum` auf die Häufigkeitstabelle an:\n\n::: {.cell}\n\n```{.r .cell-code}\ncumsum(table(a16$german))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1    2    3 \n3238 3271 3487 \n```\n:::\n:::\n\n*Was sagen die Zahlen jetzt aus? 3271 Befragte haben die deutsche und evtl. noch eine weitere Staatsbürgerschaft. Für 3487 Befragte liegt eine Angabe zur Staatsbürgerschaft vor.*\n\nDie Befehlsschachtel aus `table()` und `cumsum()` können wir durch ein schrittweises Vorgehen auflösen:\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- table(a16$german) # ablegen wie oben\ncumsum(t1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1    2    3 \n3238 3271 3487 \n```\n:::\n:::\n\n\n\n### Relative Häufigkeiten (Anteile)\nNeben den absoluten Häufigkeiten können wir uns auch relative Häufigkeitstabellen anzeigen lassen. Dazu nutzen wir den `prop.table()` Befehl und wenden diesen wiederum entweder auf `table()` oder direkt auf `t1` an:\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(a16$german)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n          1           2           3 \n0.928591913 0.009463722 0.061944365 \n```\n:::\n\n```{.r .cell-code}\nprop.table(t1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n          1           2           3 \n0.928591913 0.009463722 0.061944365 \n```\n:::\n:::\n\n*Wir sehen hier also, dass 92.859% aller Befragten nur die deutsche Staatsbürgerschaft haben.*\n\nAuch die relativen Häufigkeiten können wir uns als kumulierte Werte ausgeben lassen, dazu kombinieren wir `prop.table()` mit `cumsum()`:\n\n::: {.cell}\n\n```{.r .cell-code}\ncumsum(prop.table(table(a16$german)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1         2         3 \n0.9285919 0.9380556 1.0000000 \n```\n:::\n:::\n\nDiese Befehlsschachtel können wir wieder vermeiden indem wir die absoluten Häufigkeiten aus `t1` aufrufen und dann die relativen Häufigkeiten unter  `t2` ablegen:\n\n::: {.cell}\n\n```{.r .cell-code}\nt2 <- prop.table(t1) # relative Häufigkeiten unter t2 ablegen\ncumsum(t2) # relative kumulierte Häufigkeiten \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1         2         3 \n0.9285919 0.9380556 1.0000000 \n```\n:::\n:::\n\n*Wir sehen hier also, dass 93.806% aller Befragten die deutsche und evtl. eine weitere Staatsbürgerschaft haben.*\n\n\n\n### Übersichtstabelle mit allen Kennzahlen\nDies alles lässt sich zu einer Gesamttabelle im Format eines Datensatzes zusammenfassen. Dazu legen wir zunächst die absoluten Häufigkeiten in einem `data.frame` unter `t3` ab:\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- table(a16$german) # wie bereits oben\nt3 <- data.frame(t1) # t1 in einen Datensatz umformatieren\nt3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1 Freq\n1    1 3238\n2    2   33\n3    3  216\n```\n:::\n\n```{.r .cell-code}\nclass(t3) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n:::\n\nDiesem `data.frame` fügen wir dann mit `t3$...` neue Variablen/Spalten hinzu. Während wir uns oben jeweils auf `t1` für die absoluten Häufigkeiten bezogen hatten, finden wir diese jetzt innerhalb von  `t3` in der Spalte `Freq`:\n\n::: {.cell}\n\n```{.r .cell-code}\nt3$H <- cumsum(t3$Freq) # kum. absolute Häufigkeiten\nt3 # kontrolle\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1 Freq    H\n1    1 3238 3238\n2    2   33 3271\n3    3  216 3487\n```\n:::\n\n```{.r .cell-code}\nt3$f <- prop.table(t3$Freq) # rel. Häufigkeiten\nt3 # kontrolle\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1 Freq    H           f\n1    1 3238 3238 0.928591913\n2    2   33 3271 0.009463722\n3    3  216 3487 0.061944365\n```\n:::\n\n```{.r .cell-code}\nt3$F <- cumsum(t3$f) # kum. rel. Häufigkeiten\nt3 # kontrolle\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1 Freq    H           f         F\n1    1 3238 3238 0.928591913 0.9285919\n2    2   33 3271 0.009463722 0.9380556\n3    3  216 3487 0.061944365 1.0000000\n```\n:::\n:::\n\n\nZum Schluss können wir mit `colnames` die Spalten klar benennen. Dazu rufen wir mit `colnames(t3)` die Spaltennamen von `t3` auf und überschreiben diese dann mit einer Folge an Werten, die wir mit `c()` angeben:\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(t3) <- c(\"Werte\", \"h\", \"H\", \"f\", \"F\")\nt3 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Werte    h    H           f         F\n1     1 3238 3238 0.928591913 0.9285919\n2     2   33 3271 0.009463722 0.9380556\n3     3  216 3487 0.061944365 1.0000000\n```\n:::\n:::\n\n\n## Kontingenztabellen\n\nIn dieser Session beschäftigten wir uns mit den Familienstandsangaben aus der Variable `mstat`. Wie vergangene Woche müssen wir vorab die negativen Werte (`-9`, siehe Codebuch) mit `NA` überschreiben: \n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$mstat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  -9    1    2    3    4    5    6    9 \n   2 1919   60  236  316  949    7    1 \n```\n:::\n\n```{.r .cell-code}\na16$mstat[a16$mstat < 0] <- NA\ntable(a16$mstat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4    5    6    9 \n1919   60  236  316  949    7    1 \n```\n:::\n:::\n\n\n\nAus Kontingenztabellen erfahren wir, wie häufig Merkmalskombinationen auftreten. Auch für Kontingenztabellen können wir `table()` verwenden. Zum Beispiel können wir uns eine Tabelle anzeigen lassen, die uns die Häufigkeiten des Familienstatus getrennt nach Geschlechtern zeigt:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$sex, a16$mstat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n       1    2    3    4    5    6    9\n  1 1011   33   56  133  534    2    0\n  2  908   27  180  183  415    5    1\n```\n:::\n:::\n\n\nWir erkennen aus dieser Tabelle beispielsweise, dass 415 Befragte weiblich (`sex=2`) und ledig (`mstat = 5`) sind.\n\n<!-- [^5]: Hier ist das Geschlechts als binäres Merkmal codiert. Die Einführung der dritten Option im Dez 2018 wird aber in künftigen Erhebungen auch im Allbus berücksichtigt werden. Bis dahin müssen wir mit den Kategorien arbeiten, die uns hier vorgegeben sind.  -->\n\n\n\nEine Alternative zu `table()` ist `xtabs()`. Hier werden die Spalten und Zeilen beschriftet. Der Übersichtlichkeit halber verwenden wir diese Darstellung, alle Operationen sind aber genauso auch mit `table` möglich. Da wir mit dieser Kontingenztabelle noch etwas weiter arbeiten werden, legen wir sie unter `kt` ab:\n\n::: {.cell}\n\n```{.r .cell-code}\nxtabs(~sex+mstat, data = a16)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex    1    2    3    4    5    6    9\n  1 1011   33   56  133  534    2    0\n  2  908   27  180  183  415    5    1\n```\n:::\n\n```{.r .cell-code}\nkt <- xtabs(~sex+mstat, data = a16) \nkt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex    1    2    3    4    5    6    9\n  1 1011   33   56  133  534    2    0\n  2  908   27  180  183  415    5    1\n```\n:::\n:::\n\n### Relative Häufigkeiten\n\nAuch hier können wir uns die relativen Häufigkeiten anzeigen lassen, indem wir `prop.table()` anwenden:\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(kt) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex            1            2            3            4            5\n  1 0.2898509174 0.0094610092 0.0160550459 0.0381307339 0.1530963303\n  2 0.2603211009 0.0077408257 0.0516055046 0.0524655963 0.1189793578\n   mstat\nsex            6            9\n  1 0.0005733945 0.0000000000\n  2 0.0014334862 0.0002866972\n```\n:::\n:::\n\nDie hier dargestellten relativen Häufigkeiten beziehen sich jeweils auf die Gesamtzahl der Befragten. Formal dargestellt wird also für die Kombination weiblich (`sex=2`) und ledig (`mstat = 5`) die Anzahl ledigen Frauen durch die Anzahl **aller Befragten** geteilt: $\\frac{Anzahl\\,lediger\\,Frauen}{Gesamtzahl\\,der\\,Befragten}$ - Wir können also aus dieser Tabelle ablesen dass `11,9%` der Befragten *weiblich und ledig* sind. \n\n\n\n### Zeilen- und Spaltenprozente\nWir können diese Tabelle auch mit *Zeilen- und Spaltenprozenten* anzeigen lassen, indem wir die Option `margin` verwenden. `margin=1` liefert die **Zeilenprozente**, `margin=2` die **Spaltenprozente**.[^1]  \n\n[^1]: Der Übersichtlichkeit halber wurden die Darstellungen hier gerundet - siehe [Hinweise](#hinweise_w04).\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(kt,margin = 1)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex      1      2      3      4      5      6      9\n  1 0.5715 0.0187 0.0317 0.0752 0.3019 0.0011 0.0000\n  2 0.5282 0.0157 0.1047 0.1065 0.2414 0.0029 0.0006\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(kt,margin = 2) \n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex      1      2      3      4      5      6      9\n  1 0.5268 0.5500 0.2373 0.4209 0.5627 0.2857 0.0000\n  2 0.4732 0.4500 0.7627 0.5791 0.4373 0.7143 1.0000\n```\n:::\n:::\n\n*Achtung!* Damit ändert sich jeweils die Interpretation der Tabelle! Wir ändern durch `margin` die Bezugsgröße oder formal ausgedrückt den Nenner:  \n\n+ Für die Zeilenprozente werden die Werte in Bezug zu den Zeilensummen gesetzt. Also wird die Anzahl der ledigen Frauen ins Verhältnis zur Zahl der befragten Frauen gesetzt: $\\frac{Anzahl\\,lediger\\,Frauen}{Gesamtzahl\\,der\\,befragten\\,Frauen}$ - Interpretation: \"`24,14%` der befragten Frauen sind ledig\"  \n+ Für die Spaltenprozente werden die Werte in Bezug zu den Spaltensummen gesetzt. Also wird die Anzahl der ledigen Frauen ins Verhältnis zur Zahl der ledigen Befragten gesetzt: $\\frac{Anzahl\\,lediger\\,Frauen}{Gesamtzahl\\,der\\,ledigen\\,Befragten}$ - Interpretation: \"`43,73%` der ledigen Befragten sind Frauen\" \n\n\n \n\n## Arbeiten mit der Pipe\n\nUnter `kt` hatten wir das Ergebnis des `xtabs`-Befehls abgelegt: `xtabs(~sex+mstat, data = a16)`.\nWenn wir also alles \"ausschreiben\", dann ergibt sich folgender, verschachtelter Befehl:\n\n::: {.cell}\n\n```{.r .cell-code}\nround(   prop.table( xtabs(~sex+mstat, data = a16), margin = 1)   ,2) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex    1    2    3    4    5    6    9\n  1 0.57 0.02 0.03 0.08 0.30 0.00 0.00\n  2 0.53 0.02 0.10 0.11 0.24 0.00 0.00\n```\n:::\n:::\n\n\nDiese Befehlsschachtel können wir mit der sog. Pipe `%>%` auflösen und besser darstellen. `%>%` steht dabei einfach für \"und dann\". Die Pipe ist unter anderem Teil des Pakets `dplyr`, welches wir in Zukunft häufiger verwenden werden:\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"dplyr\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n:::\n\n\nMit der Pipe sieht die Befehlsschachtel dann so aus und wir können sie von links nach rechts lesen:\n\n::: {.cell}\n\n```{.r .cell-code}\n xtabs(~sex+mstat, data = a16) %>% prop.table(., margin = 1) %>% round(.,2) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   mstat\nsex    1    2    3    4    5    6    9\n  1 0.57 0.02 0.03 0.08 0.30 0.00 0.00\n  2 0.53 0.02 0.10 0.11 0.24 0.00 0.00\n```\n:::\n:::\n\nDer Punkt `.` steht jeweils für das Ergebnis des vorherigen Schritts. Hier also:\n\n   1. erstelle die Kontingenztabelle *und dann (`%>%`)*\n   2. berechne daraus die relativen Häufigkeiten mit `margin = 1` *und dann (`%>%`)*\n   3. runde das Ergebnis auf 2 Nachkommastellen\n\n> Tipp:` %>%` kann mit STRG+SHIFT+m (cmd+shift+m für Mac) eingefügt werden.\n\n\n## Metrische Variablen\n\nDas bisherige Beispiel Staatsbürgerschaft (`german`) bezog sich auf ein kategoriales Merkmal. Für ein metrisches Merkmal, wie zum Beispiel das Geburtsjahr macht eine Häufigkeitstabelle wenig Sinn, da das Geburtsjahr sehr viele Ausprägungen hat und eine Tabelle  unübersichtlich wäre - hier nur als Beispiel die ersten 20 Ausprägungen (es gibt insgesamt 77!):\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$age)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n\n-32  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 \n  4  29  41  43  43  41  45  34  40  48  36  49  43  58  49  47  51  65  54  42 \n```\n:::\n:::\n\n\nUm eine Häufigkeitstabelle zu erstellen müssen wir bei metrischen Merkmalen Klassen bilden. So könnten wir das Alter in Lebensjahrzehnte unterteilen. Zuvor müssen wir wieder die fehlenden Angaben[^1] überschreiben:\n\n::: {.cell}\n\n```{.r .cell-code}\na16$age[a16$age == -32] <- NA\n```\n:::\n\nUm die Klassen zu bilden, nutzen wir `cut()` und geben neben der zu unterteilenden Variable mit `breaks` die Klassengrenzen an. Für die Grenzen können wir `seq()` verwenden. Darin geben wir zunächst die obere und untere Grenze an und dann die Schrittbreiten. Diese Werte legen wir in einer neuen Variable in `a16` ab: \n\n::: {.cell}\n\n```{.r .cell-code}\na16$age_zehner <- cut(a16$age, breaks = c(10,20,30,40,50,60,70,80,90,100) )\na16$age_zehner <- cut(a16$age, breaks = seq(10,100,10) ) # kürzer mit seq()\n```\n:::\n\nFür diese neue Variable können wir mit `table()` eine Häufigkeitstabelle anfordern:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(a16$age_zehner)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n (10,20]  (20,30]  (30,40]  (40,50]  (50,60]  (60,70]  (70,80]  (80,90] \n     113      437      491      605      710      579      419      127 \n(90,100] \n       5 \n```\n:::\n:::\n\n`(` bedeutet dabei ausgeschlossen, `]` inklusive. Es gibt also 437 Befragte, die über 20 bis inklusive 30 Jahre alt sind.  \nWir haben also durch Klassierung aus dem metrischen Merkmal `age` ein kategoriales Merkmal `age_zehner` erstellt. Damit können wir dann genauso arbeiten wie oben - zB für die kumulierten relativen Häufigkeiten:\n\n::: {.cell}\n\n```{.r .cell-code}\nage_tab <- table(a16$age_zehner) # abs Häufigkeiten\nage_tab2 <- prop.table(age_tab) # rel Häufigkeiten\ncumsum(age_tab2) # kumulieren\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] \n0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 \n   (80,90]   (90,100] \n0.99856569 1.00000000 \n```\n:::\n:::\n\n*Wir sehen hier so, dass 47.217% aller Befragten 50 Jahre oder jünger sind.*\n\nWir könnten alles auch in einem Befehl zusammen durchführen, das wird aber schnell unübersichtlich:\n\n::: {.cell}\n\n```{.r .cell-code}\ncumsum(prop.table(table( cut(a16$age, breaks = seq(10,100,10) ) )))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] \n0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 \n   (80,90]   (90,100] \n0.99856569 1.00000000 \n```\n:::\n:::\n\n\n\n\n[^1]: Die Werte für fehlende Angaben finden wir Codebuch: auch hier ist `-32` wieder ein Code für fehlende Werte.\n\n##  Lage- & Konzentrationsmaße \n\n\nFür die Beispiele verwenden wir die Angaben aus dem Jahr 2014. Diese Auswahl können wir mit `[]` treffen:\n\n::: {.cell}\n\n```{.r .cell-code}\na14 <- ak[ak$year == 2014,] # basis R\n```\n:::\n\n\n### Lagemaße\n\nLagemaße sind statische Kennzahlen zur Beschreibung von metrischen Variablen. Einen Überblick bietet `summary()`:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(a14$di05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    -50      -7    1800    2051    3000   80400 \n```\n:::\n:::\n\n\nNatürlich gibt es keine Haushalte, die ein Einkommen von `-50` Euro pro Monat haben. Um aussagekräftige Werte zu bekommen, müssen wir diese Werte mit `NA` überschreiben:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na14$di05[a14$di05 < 0] <- NA # missings überschreiben\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(a14$di05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n     50    1500    2400    2739    3500   80400     869 \n```\n:::\n:::\n\n\n\nWir können aber auch bestimmte Kennzahlen anfordern sehen uns die Haushaltseinkommen der Befragten (`di05`) im Allbus 2014 mit Hilfe folgender Befehle an:\n\n+ Minimum und Maximum: `min()`, `max()`\n+ arithm. Mittel: `mean()`\n+ Median: `median()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmin(a14$di05) # kleinster Wert\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\nWenn eine Variable `NA` enthält, müssen diese explizit ignoriert werden - ansonsten wird nur `NA` ausgegeben:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmin(a14$di05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\nDeshalb müssen wir die Option `na.rm = T` angeben:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmin(a14$di05,na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 50\n```\n:::\n\n```{.r .cell-code}\nmax(a14$di05,na.rm = T) #größter Wert\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80400\n```\n:::\n\n```{.r .cell-code}\nmean(a14$di05, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2739.063\n```\n:::\n\n```{.r .cell-code}\nmedian(a14$di05, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2400\n```\n:::\n:::\n\n\n### Streuungsmaße\n#### Quantile   \nEin Quantil einer Verteilung trennt die Daten so in zwei Teile, dass `x`\\% der Daten darunter und 100-`x`\\% darüber liegen.  Gebräuchlich sind die Quartile, welche die Grenzen für 25\\%, 50\\% und 75\\% angeben. Diese werden auch standardmäßig von `quantile()` ausgegeben:\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(a14$di05,na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   0%   25%   50%   75%  100% \n   50  1500  2400  3500 80400 \n```\n:::\n:::\n\nMusterinterpretation: \n\n  + *25% der Befragten haben ein HH-Einkommen von 1500€ oder weniger*\n  + *75% der Befragten haben ein HH-Einkommen von 3500€ oder weniger*\n  \nDaraus ergibt sich auch:\n\n  + *75% der Befragten haben ein HH-Einkommen von 1500€ oder mehr* \n  \nWir können aber durch Angabe in den Optionen beliebige Quantilgrenzen anfordern, zB. für die 40%-Quantilgrenze:  \n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(a14$di05,probs = .4, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 40% \n2000 \n```\n:::\n:::\n\nIn Kombination mit `seq()` können wir zB. auch die Dezilgrenzen (entlang der Vielfachen von 0,1) anfordern:\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(a14$di05,probs = c(0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1), na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% \n   50  1000  1400  1723  2000  2400  2800  3200  3800  4800 80400 \n```\n:::\n\n```{.r .cell-code}\nquantile(a14$di05,probs = seq(0,1,0.1), na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% \n   50  1000  1400  1723  2000  2400  2800  3200  3800  4800 80400 \n```\n:::\n:::\n\n\n\n#### Interquartilsdistanz und Interdezilsdistanz  \n\nAus den Quantilen leiten sich auch die Inter**quartil**sdistanz und Inter**dezil**sdistanz ab.   \nDie Interquartilsdistanz ist schlicht die Differenz zwischen dem ersten und dritten Quartil. Genauso ist die Interdezilsdistanz die Differenz zwischen dem neunten und ersten Dezil:\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(a14$di05, .75, na.rm = T) - quantile(a14$di05, .25, na.rm = T) # IQR\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 75% \n2000 \n```\n:::\n\n```{.r .cell-code}\nquantile(a14$di05, .9, na.rm = T) - quantile(a14$di05, .1, na.rm = T) # IDR\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 90% \n3800 \n```\n:::\n:::\n\n\\color{red}\n**Achtung**: R zeigt nach der Berechnung der Differenz trotzdem die Beschriftung des Minuenden / des ersten Argumentes an!   \n\\color{black}\n\n#### Varianz, Standardabweichung, Variationskoeffizient\nDie häufigste Kennzahl zur Beschreibung von Streuung ist aber die Varianz. Die Varianz ist definiert als die durchschnittliche quadrierte Abweichung vom arith. Mittel: $$var(x) = \\frac{\\sum_{i=1}^{n} (x_{i}-\\bar{x})^2}{n}$$    \nWas bedeutet diese Formel?    \nSchauen wir erst in den Zähler des Bruchs: $(x_{i}-\\bar{x})^2$\nEs geht also um die Abstände der einzelnen Datenpunkte ($x_{i}$) zum arithmetischen Mittel ($\\bar{x}$) - mathematisch die Differenz zwischen den einzelnen Datenpunkten $x_{i}-\\bar{x}$ - hier eingezeichnet als gestrichelte Linien:\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_desc_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=55% height=55%}\n:::\n:::\n\nFür Punkte, die über dem arith. Mittel liegen, erhalten wir für die Differenz einen positiven Wert (wir ziehen ja jeweils das arith. Mittel vom Wert für den Datenpunkt ab). Für Punkte mit Werten, die kleiner als das arith. Mittel sind, erhalten wir einen negativen Wert.     \nWürden wir die Abstände (gestrichelten Linien) einfach aufsummieren, erhielten wir als Ergebnis immer Null! Das arithmetische Mittel liegt ja per Definition immer genau \"in der Mitte\": die Abstände nach oben sind in der Summe genauso groß wie die Abstände nach unten. Daher wird zunächst jeder Abstand quadriert: $(\\bar{x} - x_{i})^2$   \nDer Rest der Formel gibt dann an, dass alle quadrierten Differenzen aufsummiert ($\\sum_{i=1}^{n}$) und dann durch die Anzahl der Beobachtungen geteilt werden ($\\frac{}{n}$)- zusammengefasst hier nochmal die Formel:  $$var(x) = \\frac{\\sum_{i=1}^{n} (x_{i}-\\bar{x})^2}{n}$$\n\nWir können die Varianz mit `var()` berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(a14$di05, na.rm = T) # Varianz\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6387969\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\nIn unseren Datensatz beträgt der Varianz der Haushaltseinkommen also 6.387.969€². Auf der Varianz beruhen noch zwei weitere Streuungsmaße. Die *Standardabweichung* entspricht der Wurzel der Varianz und hat somit die gleiche Messeinheit wie die Variable (hier EUR). Der *Variationskoeffizient*  entspricht `sd`/`mean` und dient dem Vergleich verschiedener Streuungen relativ zum jeweiligen Mittelwert:\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(var(a14$di05, na.rm = T))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2527.443\n```\n:::\n\n```{.r .cell-code}\nsd(a14$di05, na.rm = T) # Standardabweichung\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2527.443\n```\n:::\n\n```{.r .cell-code}\nsd(a14$di05, na.rm = T) / mean(a14$di05, na.rm = T) # Variationskoeffizient\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9227402\n```\n:::\n:::\n\n\nFür alle Streuungsmaße gilt: je größer, desto mehr Streuung (Unterschiede) gibt es in den Daten.\n\n\n#### Gini-Koeffizient\n\nZur Beschreibung der Verteilung von Einkommens- und Vermögensdaten wird häufig der Gini-Koeffizient verwendet. Der Gini-Koeffizient beruht auf der Fläche zwischen der Lorenzkurve und der Gleichverteilung. Auf der x-Achse werden die kumulierten Perzentile der Befragten abgetragen, auf der y-Achse die Perzentile des HH-Einkommens:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_desc_files/figure-html/gini_plot1-1.png){fig-align='center' width=75% height=75%}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_desc_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=75% height=75%}\n:::\n:::\n\nDen Gini-Koeffizienten können wir mit `Gini()` aus dem Paket `ineq` berechnen:\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"ineq\") # einmal installieren\nlibrary(ineq) # ineq laden\nGini(a14$di05)\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3286304\n```\n:::\n:::\n\n\n### Lage- und Streuungsmaße vergleichen\nHäufig werden diese Kennzahlen erst im Vergleich richtig spannend. zB können wir die Einkommensangaben aus den alten und neuen Bundesländern vergleichen:\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(a14$di05[a14$eastwest == 1], na.rm = T) # alte Bundesländer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2921.727\n```\n:::\n\n```{.r .cell-code}\nmean(a14$di05[a14$eastwest == 2], na.rm = T) # neue Bundesländer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2347.703\n```\n:::\n:::\n\nIn den neuen Bundesländern ist das durchschnittliche HH-Einkommen um 574.024€ niedriger.\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(a14$di05[a14$eastwest == 1], na.rm = T) # alte Bundesländer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2600\n```\n:::\n\n```{.r .cell-code}\nmedian(a14$di05[a14$eastwest == 2], na.rm = T) # neue Bundesländer\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2000\n```\n:::\n:::\n\nIn den neuen Bundesländern ist das Median-HH-Einkommen um 600€ niedriger. Die Variationskoeffizienten zeigen eine größere Streuung im Osten als im Westen:\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(a14$di05[a14$eastwest == 1], na.rm = T) / \n  mean(a14$di05[a14$eastwest == 1], na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8501129\n```\n:::\n\n```{.r .cell-code}\nsd(a14$di05[a14$eastwest == 2], na.rm = T) / \n  mean(a14$di05[a14$eastwest == 2], na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.097566\n```\n:::\n:::\n\nWir können auch für das gesamte `summary` die Differenz zwischen Ost und West bilden:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(a14$di05[a14$eastwest == 1], na.rm = T) -\n  summary(a14$di05[a14$eastwest == 2], na.rm = T) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n     30     400     600     574     800   15400     307 \n```\n:::\n:::\n\nIn den neuen Ländern lag das Median-HH-Einkommen um 600€ niedriger als im Westen. Die 25\\% bzw. 75\\% Quartilsgrenze lag um 400€ bzw 800€ niedriger, das arith. Mittel war um 574€ niedriger als in den alten Bundesländern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGini(a14$di05[a14$eastwest == 1])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3182835\n```\n:::\n\n```{.r .cell-code}\nGini(a14$di05[a14$eastwest == 2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3346088\n```\n:::\n:::\n\nWo ist die Ungleichheit nun höher? In Ost oder West?\n\n\n\n## Aufgaben 2: Lage- & Konzentrationsmaße\n\nForschungsfrage: Wie hat sich die Haushaltseinkommensverteilung zwischen 1994 und 2010 entwickelt?\n\n(1) Laden Sie den **kumulierten** Allbusdatensatz in R (siehe [oben](#einlesen)).\n(2) Erstellen Sie jeweils einen Datensatz für das Befragungsjahr 1994 und 2010 - filtern Sie mit `[]` also den kumulierten Datensatz jeweils einmal nach einem Jahr und legen Sie das Ergebnis in `a94` bzw. `a10` ab\n\n(3) Betrachten Sie zunächst für 1994 die Haushaltseinkommensverteilung (Variable `di05`) \n+ Denken Sie daran, die negativen Werte mit `NA` zu überschreiben!\n+ Berechnen Sie das arithm. Mittel, den Median, das 25%- und 75%-Quartil sowie die Varianz - was sagen Ihnen die Werte jeweils?\n+ Berechnen Sie die Interdezildistanz und die Spannweite!\n+ Berechnen Sie den Gini-Koeffizenten! \n\n(4) Betrachten Sie dann die Haushaltseinkommensverteilung für 2010 (Variable `di05`) \n+ Denken Sie daran, die negativen Werte mit `NA` zu überschreiben!\n+ Berechnen Sie das arithm. Mittel, den Median, das 25%- und 75%-Quartil sowie die Varianz und den Gini-Koeffizienten für alle Fälle im Datensatz für 2010 - was sagen Ihnen die Werte jeweils?\n+ Berechnen Sie die Interdezildistanz und die Spannweite!\n\n(5) Berechnen Sie für 1994 getrennt nach Ost und West (Variable `eastwest`) - welche Werte erhalten Sie jeweils für folgende Kennzahlen in Ost und West? (Denken Sie an `summary()`):\n+ arithm. Mittel, den Median, das 25%- und 75%-Quartil \n+ Variationskoeffizient \n+ Gini-Koeffizient\n\n(6) Vergleichen Sie diese Ost-West-Unterschiede im Jahr 1994 mit denen für das Jahr 2010. Welche Tendenz können Sie für die Ost-West-Unterschiede erkennen?\n\n\n## Aufgaben\n\n1) Laden Sie den Allbusdatensatz `allbus_kompakt.csv` mit dem csv-Import in R:\n\n::: {.cell}\n\n```{.r .cell-code}\nsetwd(\"...\") # wo liegt der Datensatz?\na16 <- read.table(\"allbus2016_kompakt.csv\",sep = \";\",header = T,stringsAsFactors = F) # einlesen\n```\n:::\n\n\n2) Wir interessieren uns für die Variable `gkpol`.\n  + Suchen Sie die Variable im Codebuch: welche Information können Sie dieser Variable entnehmen?\n  + Welches Skalenniveau hat die Variable?  (inhaltliche Frage, keine R-Frage) \n  + Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten?\n  + Lassen Sie sich eine Tabelle mit den absoluten Häufigkeiten anzeigen. Welche ist die häufigste Ausprägung, wofür steht die Kategorie? (Sehen Sie im Codebuch nach)\n  + Hat die Variable fehlende Werte, die Sie ausschließen sollten? Falls ja, ersetzen Sie diese Werte mit `NA` und lassen Sie sich die Tabelle erneut ausgeben.\n  \n3) Erstellen Sie eine vollständige Häufigkeitstabelle für die Variable `gkpol`, welche folgende Informationen enthält:\n  + absolute Häufigkeiten \n  + relative Häufigkeiten\n  + kumulierte absolute Häufigkeiten\n  + kumulierte relative Häufigkeiten \n  + Wie viele Befragte leben in einem Ort mit höchstens 49.999 Einwohnern?\n  + Wie groß ist der Anteil der Befragten, die in einem Ort mit höchstens 99.999 Einwohnern leben?\n  + Wie groß ist der Anteil der Befragten, die in einem Ort mit *mindestens* 100.000 Einwohnern leben?\n  \n4) Erstellen Sie eine Häufigkeitstabelle für das Geburtsjahr der Befragten (`yborn`)!\n  + Welches Skalenniveau hat die Variable? (inhaltliche Frage, keine R-Frage) \n  + Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten? Beachten Sie dazu auch die [Hinweise](#hinweis_cut_w103) am Ende dieses Dokuments. Verwenden Sie die Jahrzehntgrenzen ab 1910.\n  + Erstellen Sie eine Tabelle welche die absoluten Häufigkeiten anzeigt\n  + Gibt es fehlende Werte, die Sie mit `NA` überschreiben sollten?\n  + Erstellen Sie eine zweite Version dieser Tabelle mit relativen Häufigkeiten\n  + Wie groß ist der Anteil der Befragten, die bis 1970 geboren wurden?\n  + Wie groß ist der Anteil der Befragten, die nach 1980 geboren wurden?\n  \n  \n\n## Profi-Aufgaben\n\nFür alle, die noch etwas mehr machen möchten:  \n\n+ Runden Sie die Angaben zur relativen Häufigkeit auf 3 Nachkommastellen!\n+ Lassen Sie sich von R die häufigste Ausprägung für `yborn` ausgeben\n+ Fügen Sie der vollständigen Häufigkeitstabelle für die Variable `gkpol` eine neue Spalte hinzu, welche die Bedeutung der Zahlencodes wiedergibt!\n\nTipps dazu finden Sie in den Hinweisen am Ende!\n(Wissen aus diesen Aufgaben wird nicht vorausgesetzt in den kommenden Wochen, aber es hilft natürlich)\n\n\n## Häufige Fehlermeldungen\n\nDie Arbeit in R ist - wie in jedem Datenanalyseprogramm - ein Hangeln von Fehlermeldung zu Fehlermeldung. \nDas kann gerade zu Beginn frustrierend sein, bis die tiefere Bedeutung von Fehlermeldungen und deren Ursachen etwas deutlicher werden. \nDie folgende Auflistung enthält einige der häufigsten Fehlermeldungen und ihre (wahrscheinlichsten) Ursachen. \nDie Liste lehnt sich stark an die die großartige Zusammenstellung von [Nick C. Huntington-Klein](https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html) an.\n\n:::{.callout-note}\n\n[Fehlerliste](https://twitter.com/emilynordmann/status/1548942198246440962?s=11&t=vemXPmcotIqs4hP5J__XvQ) als Lernhilfe\n\n:::\n\n\n### There is no package called\n\nDie Fehlermeldung `there is no package called 'XXXX'` erscheint, wenn Sie ein Paket bspw. mit `library()` laden, diese Paket allerdings nicht installiert ist.\n\nThe Fix:\n\n1. Did you spell the package name correctly? Maybe you do have the package, but you made a typo\n1. If you spelled it correctly, you may not have installed it. Install it (usually) with `install.packages('packagename')` where `'packagename'` is replaced with the name of the package you actually want.\n\n### Could not find function\n\nDie Fehlermeldung `could not find function \"XXX\"` weist darauf hin, dass R die genannte Funktion nicht finden kann. \n\nThe Fix:\n\n1. Did you spell the function name correctly? Maybe you made a typo.\n1. If the function is in a package, did you load the package? Remember, the package must be re-loaded every time you restart R. If you're working in RMarkdown, you must load the package inside of your RMarkdown script, since RMarkdown starts from a blank slate.\n\n### Object not found\n\nIf you get an error like `object 'objectname' not found`, that means that you've made a reference to an object called `objectname`, but there is no such object to refer to.\n\nThe Fix:\n\n1. Did you spell the object's name correctly? Maybe you made a typo.\n1. Did you remember to create the object before referring to it? For example, the code `mean(x); x <- 1:10` would not work, because you try to take the mean of `x` before it's been created. If you're working in RMarkdown, remember that it will start from a blank slate, so you must create all objects inside of your Rmarkdown script.\n\n### Object of type 'closure' is not subsettable\n\nThis is the most aggravating and least-informative R error. \"Subsettable\" is a hint though - you're trying to take a subset of something (such as picking an element from a vector, or picking a column from a data set), but the thing you're doing it to is a \"closure\" that you can't do that to.\n\nMost commonly, this is a case of accidentally giving the name of a function where you mean to give the name of a vector or data frame. For example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_data <- tibble(person = c('Me','You'), meanness = c(1000,999))\n# Now let's look at that meanness variable, but oops, I'm referring to the function mean() instead of my data mean_data\nmean$meanness\n# Error in mean$meanness : object of type 'closure' is not subsettable\n```\n:::\n\n\nThe Fix:\n\n1. See where it says the error is \"in\" - that's the place where you've referred to the wrong thing. fix it!\n\n\n### Column doesn't exist\n\nIf you get an error like `column 'columnname' doesn't exist`, that means it's trying to refer to a column name that is not actually in your data.\n\nThe Fix:\n\n1. Did you spell the column's name correctly? Maybe you made a typo.\n1. Are you referring to the proper dataset? Maybe you created the variable in `my_data2` but you're trying to access it in `my_data`. \n1. Does your column name have spaces or other strange characters in it like dashes? If so, in many applications (anywhere you're not treating the column name as a string) you have to surround the column name in backticks (`) so it knows where the column name starts and ends.\n1. Did you perhaps drop the column before trying to refer to it? For example, in the below code, the `group_by() %>% summarize()` will only keep columns named in the `group_by()` or in the `summarize()`. So even though the `mpg` column was there at the start, it no longer is by the time we refer to it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmtcars %>%\n  group_by(am) %>%\n  summarize(mean_hp = mean(hp)) %>%\n  mutate(hp_by_mpg = mean_hp/mpg)\n```\n:::\n\n\n### Warning: Package was compiled with R version\n\nIf you load a package and get a warning that looks like `Warning: packagename was compiled with R version...`, that just means that the package was compiled using a slightly newer version of R than yours. It's generally not a problem as long as you have a somewhat-recent version of R.\n\nThe Fix:\n\n1. Ignore it\n1. If you want it to go away, update your R installation.\n\n### Rtools is required to build packages from source\n\nIf you are installing packages, you may be asked whether you'd like to build packages from source. If you say \"Yes\", but you do not have Rtools installed, you will get an error, and the package won't install properly.\n\nThe Fix:\n\n1. When asked whether you want to install packages from source, say \"No.\"\n1. Install Rtools before installing packages. The easiest way to do this is to install the **installr** package, and then run `installr::install.rtools()`.\n\n### File does not exist, or No such file or directory\n\nIf you get an error like `'filename.csv' does not exist`, that means that you're trying to load a file, but the file is not in the location you're telling R to look.\n\nThe Fix:\n\n1. Did you spell the filename correctly? Maybe you made a typo. Or, perhaps, you're trying to open an Excel fie (`.xlsx`) but telling R to look for a CSV (`.csv`). Or you wrote \"file.csv\" but the file is \"file (1).csv\". \n1. Is the file perhaps open in Excel? Sometimes, Microsoft Office will hold files hostage and not let them be opened in other programs while they're open in Office. Close the Excel window that has the file open.\n1. **Most often**, this is a working directory issue. If you tell R to look for `'filename.csv'`, it will look for that file in the *working directory*. Or, if you tell it to look for `'data/filename.csv'`, it will look for a folder called \"data\" in the working directory, and for filename.csv inside of that. In recent versions of RStudio, the current working directory is listed right on top of the Console. Did you check whether the file is actually in that folder? If you're running RMarkdown, it will set the working directory to the folder where the .RMD file is located. Did you put the file in the right spot relative to where the RMD is stored? See my [video on filepaths](https://www.youtube.com/watch?v=NG7Y0kkGR8g) for more help.\n\n### Klammern, Kommata, Punkte\n\nJust in general, a very large percentage of errors students come to me with occur simply because they made a typo, or didn't balance their parentheses (pairing each ( with a )).\n\nThe Fix:\n\n1. If you get an error message of any kind, read the relevant part of the code carefully to make sure you didn't make a typo\n1. Avoid coding where you have lots and lots of nested parentheses (this is something that **tidyverse** piping we learn is intended to avoid). Then, for whatever parentheses you do have, click on each one in RStudio - it will highlight its \"partner\" or show where there is a missing partner.\n\n### Ergebnis `NA`\n\nFehlende Werte sind Teil eines jeden Datensatzes. Wir haben oben kennengelernt, dass in R `NA` für fehlende Angaben steht.\nR geht mit `NA` etwas anders um als bspw. Stata;\nSobald ein Wert `NA` ist, gibt R als Ergebnis `NA` aus:\n\n::: {.cell}\n\n```{.r .cell-code}\nwerte <- c(1,2,NA)\nmean(werte)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n\n```{.r .cell-code}\nmin(werte)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NA\n```\n:::\n:::\n\n\n*Lösung*\nMit der Option `na.rm = TRUE` werden alle `NA` Werte vor der Berechnung ignoriert;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(werte,na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.5\n```\n:::\n\n```{.r .cell-code}\nmin(werte,na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n\n\n### Numerische Variablen und strings\n\nWhen you put something in quotes, like '1', it will treat it as a *string variable* - a set of characters to be read as text.\n\nIf you want a variable to be treated as a number, **do not put it in quotes.** This way lies madness.\n\nR is pretty loose, and will allow you to do things like ask whether `'2' > 1`, and will answer yes. This *feels* like it's okay to put the 2 in quotes. But it's not. What R is doing is saying \"oof... I can't compare a number to a letter, but you're asking me to. I'll just convert this number to a string as well, so I'm really doing `'2' > '1'`, and since '2' is alphabetically after '1', that's true, which is the desired result. Great! Except it also means that `'02' > 1` is false, since '02' is alphabetically before '1'. Same with `'120'>'20'` being false. Oops.\n\nThe Fix:\n\n1. If it's a number, and you want it treated like a numeric value, don't put quotes around it.\n\n\n### `<-`, `=` und `==`\n\n`<-` is for assigning objects. You can say `a <- 1`, and that will create an object `a` with the value `1` inside.\n\n`=` *can also* be for assigning objects, just like `<-`, but is also for assigning arguments and options in functions. In the function `mean()`, which takes the argument `x`, I can say `mean(x = 1:10)` but not `mean(x <- 1:10)`.\n\n`==` is for *checking* whether two things are equal. `a == 1` will check whether the object `a` is equal to `1`, and will return `TRUE` if it is, or `FALSE` otherwise.\n\nCommonly, this will cause problems in cases like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>%\n  filter(state = \"WA\")\n```\n:::\n\n\nwhich we might expect to filter our data to rows that are in the state of Washington, but instead will try to assign a new object `state` to be equal to `\"WA\"`.\n\n### Einige generelle Tipps zur Fehlervermeidung \n\n1. Führen Sie Ihren Code Zeile für Zeile aus. Prüfen Sie zwischen den einzelnen Zeilen die Ausgabe und stellen Sie sicher, dass sie so aussieht, wie Sie es erwarten. Oft treten Fehler auf, weil eine frühere Codezeile nicht das getan hat, was wir beabsichtigt haben. Wenn Sie dort keine Probleme feststellen, machen Sie weiter, bis Sie auf die Fehlermeldung stoßen.\n1. Lesen Sie die Fehlermeldung und schauen Sie, ob Sie sich einen Reim darauf machen können\n1. Selbst wenn du die Meldung nicht verstehst, gibt sie dir oft einen Hinweis auf die Ursache des Problems, so dass du weißt, wo du nachschauen musst, um deinen Code zu überprüfen\n1. Google: oftmals hilft es eine Fehlermeldung oder ein Problem (\"How to .... in R\") zu googeln. Neben stackoverflow gibt es unzählige Blogs, Tutorials und andere Hilfeseiten für R in hervorragender Qualität - und sie sind (fast) immer kostenlos!\n\n\n\n\n\n\n\n\n## Hinweise \n\n### cut wählt ein ungünstiges Zahlenformat {#hinweis_cut_w103}\n\n`cut` verwendet für Klassengrenzen mit mehr als 3 Stellen eine wenig intuitive Darstellung. Mit `dig.lab` können Labels mit mehr als 3 Stellen angefordert werden:\n\n::: {.cell}\n\n```{.r .cell-code}\nx1 <- c(1212,2121,1212)\ntable( cut(x1, breaks = c(0,1500,2500)) )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n      (0,1.5e+03] (1.5e+03,2.5e+03] \n                2                 1 \n```\n:::\n\n```{.r .cell-code}\ntable( cut(x1, breaks = c(0,1500,2500), dig.lab = 4) )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   (0,1500] (1500,2500] \n          2           1 \n```\n:::\n:::\n\n\n### Relative Häufigkeiten runden\n\n\nErläuterung: Sie können mit `round(x , 3)` Werte auf eine gewisse Zahl von Ziffern runden. Die zweite Zahl in der Klammer (nach dem Komma) gibt an, wieviele Dezimalstellen wir möchten:\n\n::: {.cell}\n\n```{.r .cell-code}\nround(21.12121123,digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.121\n```\n:::\n\n```{.r .cell-code}\nround(21.12121123,digits = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.12121\n```\n:::\n\n```{.r .cell-code}\nround(21.12121123,digits = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21\n```\n:::\n:::\n\n\nWir können also die relativen Häufigkeiten runden und so die Tabelle von oben übersichtlicher machen: \n\n::: {.cell}\n\n```{.r .cell-code}\nt3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Werte    h    H           f         F\n1     1 3238 3238 0.928591913 0.9285919\n2     2   33 3271 0.009463722 0.9380556\n3     3  216 3487 0.061944365 1.0000000\n```\n:::\n\n```{.r .cell-code}\nt3$f <- round(t3$f,3)\nt3$F <- round(t3$F,3)\nt3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Werte    h    H     f     F\n1     1 3238 3238 0.929 0.929\n2     2   33 3271 0.009 0.938\n3     3  216 3487 0.062 1.000\n```\n:::\n:::\n\n\n\n\n### Wie kann ich mir in R automatisch die häufigste/seltenste Ausprägung ausgeben lassen?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- table(a16$age)\nt1[which(t1 == max(t1))] # Modus\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n48 \n87 \n```\n:::\n:::\n\n`age=48` ist mit `87` Befragten die häufigste Ausprägung.\n\n### Labels als neue Spalte hinzufügen\n\nWir können die Übersichtstabelle auch noch beschriften, indem wir eine Textvariable hinzufügen:\n\n::: {.cell}\n\n```{.r .cell-code}\nt3 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Werte    h    H     f     F\n1     1 3238 3238 0.929 0.929\n2     2   33 3271 0.009 0.938\n3     3  216 3487 0.062 1.000\n```\n:::\n\n```{.r .cell-code}\nt3$labels <- c(\"dt Staatsbürgerschaft\",\"dt und andere Staatsbürgerschaft\",\n               \"andere Staatsbürgerschaft\")\nt3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Werte    h    H     f     F                           labels\n1     1 3238 3238 0.929 0.929            dt Staatsbürgerschaft\n2     2   33 3271 0.009 0.938 dt und andere Staatsbürgerschaft\n3     3  216 3487 0.062 1.000        andere Staatsbürgerschaft\n```\n:::\n:::\n",
    "supporting": [
      "03_desc_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}