<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.520">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R am BIBB - 3&nbsp; Einen Überblick erhalten</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02_intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einen Überblick erhalten</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R am BIBB</a> 
        <div class="sidebar-tools-main">
    <a href="./R-am-BIBB.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Herzlich Willkommen</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einstieg in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Arbeiten mit Datensätzen in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_desc.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einen Überblick erhalten</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#kategoriale-merkmale" id="toc-kategoriale-merkmale" class="nav-link active" data-scroll-target="#kategoriale-merkmale"> <span class="header-section-number">3.1</span> Kategoriale Merkmale</a>
  <ul class="collapse">
  <li><a href="#absolute-häufigkeiten" id="toc-absolute-häufigkeiten" class="nav-link" data-scroll-target="#absolute-häufigkeiten"> <span class="header-section-number">3.1.1</span> Absolute Häufigkeiten</a></li>
  </ul></li>
  <li><a href="#NA_w103" id="toc-NA_w103" class="nav-link" data-scroll-target="#NA_w103"> <span class="header-section-number">3.2</span> Fehlende Werte in R: <code>NA</code></a>
  <ul class="collapse">
  <li><a href="#kumulierte-häufigkeiten" id="toc-kumulierte-häufigkeiten" class="nav-link" data-scroll-target="#kumulierte-häufigkeiten"> <span class="header-section-number">3.2.1</span> Kumulierte Häufigkeiten</a></li>
  <li><a href="#relative-häufigkeiten-anteile" id="toc-relative-häufigkeiten-anteile" class="nav-link" data-scroll-target="#relative-häufigkeiten-anteile"> <span class="header-section-number">3.2.2</span> Relative Häufigkeiten (Anteile)</a></li>
  <li><a href="#übersichtstabelle-mit-allen-kennzahlen" id="toc-übersichtstabelle-mit-allen-kennzahlen" class="nav-link" data-scroll-target="#übersichtstabelle-mit-allen-kennzahlen"> <span class="header-section-number">3.2.3</span> Übersichtstabelle mit allen Kennzahlen</a></li>
  </ul></li>
  <li><a href="#kontingenztabellen" id="toc-kontingenztabellen" class="nav-link" data-scroll-target="#kontingenztabellen"> <span class="header-section-number">3.3</span> Kontingenztabellen</a>
  <ul class="collapse">
  <li><a href="#relative-häufigkeiten" id="toc-relative-häufigkeiten" class="nav-link" data-scroll-target="#relative-häufigkeiten"> <span class="header-section-number">3.3.1</span> Relative Häufigkeiten</a></li>
  <li><a href="#zeilen--und-spaltenprozente" id="toc-zeilen--und-spaltenprozente" class="nav-link" data-scroll-target="#zeilen--und-spaltenprozente"> <span class="header-section-number">3.3.2</span> Zeilen- und Spaltenprozente</a></li>
  </ul></li>
  <li><a href="#arbeiten-mit-der-pipe" id="toc-arbeiten-mit-der-pipe" class="nav-link" data-scroll-target="#arbeiten-mit-der-pipe"> <span class="header-section-number">3.4</span> Arbeiten mit der Pipe</a></li>
  <li><a href="#metrische-variablen" id="toc-metrische-variablen" class="nav-link" data-scroll-target="#metrische-variablen"> <span class="header-section-number">3.5</span> Metrische Variablen</a></li>
  <li><a href="#lage--konzentrationsmaße" id="toc-lage--konzentrationsmaße" class="nav-link" data-scroll-target="#lage--konzentrationsmaße"> <span class="header-section-number">3.6</span> Lage- &amp; Konzentrationsmaße</a>
  <ul class="collapse">
  <li><a href="#lagemaße" id="toc-lagemaße" class="nav-link" data-scroll-target="#lagemaße"> <span class="header-section-number">3.6.1</span> Lagemaße</a></li>
  <li><a href="#streuungsmaße" id="toc-streuungsmaße" class="nav-link" data-scroll-target="#streuungsmaße"> <span class="header-section-number">3.6.2</span> Streuungsmaße</a></li>
  <li><a href="#lage--und-streuungsmaße-vergleichen" id="toc-lage--und-streuungsmaße-vergleichen" class="nav-link" data-scroll-target="#lage--und-streuungsmaße-vergleichen"> <span class="header-section-number">3.6.3</span> Lage- und Streuungsmaße vergleichen</a></li>
  </ul></li>
  <li><a href="#aufgaben-2-lage--konzentrationsmaße" id="toc-aufgaben-2-lage--konzentrationsmaße" class="nav-link" data-scroll-target="#aufgaben-2-lage--konzentrationsmaße"> <span class="header-section-number">3.7</span> Aufgaben 2: Lage- &amp; Konzentrationsmaße</a></li>
  <li><a href="#aufgaben" id="toc-aufgaben" class="nav-link" data-scroll-target="#aufgaben"> <span class="header-section-number">3.8</span> Aufgaben</a></li>
  <li><a href="#profi-aufgaben" id="toc-profi-aufgaben" class="nav-link" data-scroll-target="#profi-aufgaben"> <span class="header-section-number">3.9</span> Profi-Aufgaben</a></li>
  <li><a href="#häufige-fehlermeldungen" id="toc-häufige-fehlermeldungen" class="nav-link" data-scroll-target="#häufige-fehlermeldungen"> <span class="header-section-number">3.10</span> Häufige Fehlermeldungen</a>
  <ul class="collapse">
  <li><a href="#there-is-no-package-called" id="toc-there-is-no-package-called" class="nav-link" data-scroll-target="#there-is-no-package-called"> <span class="header-section-number">3.10.1</span> There is no package called</a></li>
  <li><a href="#could-not-find-function" id="toc-could-not-find-function" class="nav-link" data-scroll-target="#could-not-find-function"> <span class="header-section-number">3.10.2</span> Could not find function</a></li>
  <li><a href="#object-not-found" id="toc-object-not-found" class="nav-link" data-scroll-target="#object-not-found"> <span class="header-section-number">3.10.3</span> Object not found</a></li>
  <li><a href="#object-of-type-closure-is-not-subsettable" id="toc-object-of-type-closure-is-not-subsettable" class="nav-link" data-scroll-target="#object-of-type-closure-is-not-subsettable"> <span class="header-section-number">3.10.4</span> Object of type ‘closure’ is not subsettable</a></li>
  <li><a href="#column-doesnt-exist" id="toc-column-doesnt-exist" class="nav-link" data-scroll-target="#column-doesnt-exist"> <span class="header-section-number">3.10.5</span> Column doesn’t exist</a></li>
  <li><a href="#warning-package-was-compiled-with-r-version" id="toc-warning-package-was-compiled-with-r-version" class="nav-link" data-scroll-target="#warning-package-was-compiled-with-r-version"> <span class="header-section-number">3.10.6</span> Warning: Package was compiled with R version</a></li>
  <li><a href="#rtools-is-required-to-build-packages-from-source" id="toc-rtools-is-required-to-build-packages-from-source" class="nav-link" data-scroll-target="#rtools-is-required-to-build-packages-from-source"> <span class="header-section-number">3.10.7</span> Rtools is required to build packages from source</a></li>
  <li><a href="#file-does-not-exist-or-no-such-file-or-directory" id="toc-file-does-not-exist-or-no-such-file-or-directory" class="nav-link" data-scroll-target="#file-does-not-exist-or-no-such-file-or-directory"> <span class="header-section-number">3.10.8</span> File does not exist, or No such file or directory</a></li>
  <li><a href="#klammern-kommata-punkte" id="toc-klammern-kommata-punkte" class="nav-link" data-scroll-target="#klammern-kommata-punkte"> <span class="header-section-number">3.10.9</span> Klammern, Kommata, Punkte</a></li>
  <li><a href="#ergebnis-na" id="toc-ergebnis-na" class="nav-link" data-scroll-target="#ergebnis-na"> <span class="header-section-number">3.10.10</span> Ergebnis <code>NA</code></a></li>
  <li><a href="#numerische-variablen-und-strings" id="toc-numerische-variablen-und-strings" class="nav-link" data-scroll-target="#numerische-variablen-und-strings"> <span class="header-section-number">3.10.11</span> Numerische Variablen und strings</a></li>
  <li><a href="#und" id="toc-und" class="nav-link" data-scroll-target="#und"> <span class="header-section-number">3.10.12</span> <code>&lt;-</code>, <code>=</code> und <code>==</code></a></li>
  <li><a href="#einige-generelle-tipps-zur-fehlervermeidung" id="toc-einige-generelle-tipps-zur-fehlervermeidung" class="nav-link" data-scroll-target="#einige-generelle-tipps-zur-fehlervermeidung"> <span class="header-section-number">3.10.13</span> Einige generelle Tipps zur Fehlervermeidung</a></li>
  </ul></li>
  <li><a href="#hinweise" id="toc-hinweise" class="nav-link" data-scroll-target="#hinweise"> <span class="header-section-number">3.11</span> Hinweise</a>
  <ul class="collapse">
  <li><a href="#hinweis_cut_w103" id="toc-hinweis_cut_w103" class="nav-link" data-scroll-target="#hinweis_cut_w103"> <span class="header-section-number">3.11.1</span> cut wählt ein ungünstiges Zahlenformat</a></li>
  <li><a href="#relative-häufigkeiten-runden" id="toc-relative-häufigkeiten-runden" class="nav-link" data-scroll-target="#relative-häufigkeiten-runden"> <span class="header-section-number">3.11.2</span> Relative Häufigkeiten runden</a></li>
  <li><a href="#wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" id="toc-wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" class="nav-link" data-scroll-target="#wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen"> <span class="header-section-number">3.11.3</span> Wie kann ich mir in R automatisch die häufigste/seltenste Ausprägung ausgeben lassen?</a></li>
  <li><a href="#labels-als-neue-spalte-hinzufügen" id="toc-labels-als-neue-spalte-hinzufügen" class="nav-link" data-scroll-target="#labels-als-neue-spalte-hinzufügen"> <span class="header-section-number">3.11.4</span> Labels als neue Spalte hinzufügen</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="tab" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Einen Überblick erhalten</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>In der vorherigen Sitzung hatten wir gesehen, wie wir Datensätze importieren und damit arbeiten. Jede statistische Auswertung eines Datensatzes startet mit einer Beschreibung der Variablen. In dieser Session werden wir sehen, wie wir uns mit Tabellen einen Überblick über die Informationen in einem Datensatz verschaffen können. Wir werden auch in dieser Session mit dem Allbus 2016 arbeiten. Zunächst müssen wir dazu die Daten wieder wie vergangene Woche einlesen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"..."</span>) <span class="co"># wo liegt der Datensatz?</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>a16 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"allbus2016_kompakt.csv"</span>,<span class="at">sep =</span> <span class="st">";"</span>,<span class="at">header =</span> T,<span class="at">stringsAsFactors =</span> F) <span class="co"># einlesen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="kategoriale-merkmale" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="kategoriale-merkmale"><span class="header-section-number">3.1</span> Kategoriale Merkmale</h2>
<section id="absolute-häufigkeiten" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="absolute-häufigkeiten"><span class="header-section-number">3.1.1</span> Absolute Häufigkeiten</h3>
<p>Zentraler Befehl für die Auszählung von Häufigkeiten ist der <code>table()</code> Befehl. Beispielsweise mit der Variable <code>german</code> (Details im Codebuch).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>Wir bekommen hier also die absoluten Häufigkeiten angezeigt. In der ersten Zeile werden die verschiedenen Ausprägungen aufgelistet, in der zweiten Zeile stehen dann die Häufigkeiten. Aus dem Codebuch erfahren wir, für welche inhaltlichen Kategorien die Zahlencodes jeweils stehen. Bspw. steht <code>1</code> dafür, dass der*die Befragte die deutsche Staatsbürgerschaft besitzt. Wir können auch Tabellen unter einem frei wählbaren Namen ablegen und später wieder aufrufen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>t1 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>3238 Befragte haben also nur die deutsche Staatsbürgerschaft, 33 Befragte haben die deutsche und noch eine weitere Staatsbürgerschaft. Außerdem enthält der Datensatz 216 Befragte ohne deutsche Staatsbürgerschaft.</p>
<p>Etwas störend ist aber noch die <code>-32</code>. Aus dem Codebuch erfahren wir, dass <code>-32</code> für fehlende Angabe steht:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../../RFS/images/103_german_codebuch.png" style="width:53.0%;height:53.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="NA_w103" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="NA_w103"><span class="header-section-number">3.2</span> Fehlende Werte in R: <code>NA</code></h2>
<p>Um die Werte mit <code>-32</code> auch in R als fehlende Angabe zu kennzeichnen, müssen wir sie auf <code>NA</code> setzen. Dazu rufen wir <code>a16$german</code> auf und filtern mit <code>[]</code> nur die Werte für <code>german</code> gleich <code>-32</code> heraus. Vergangene Woche haben wir kennengelernt, dass wir so spezifische Werte aufrufen können:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="co"># nur german = -32 aufrufen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -32 -32 -32</code></pre>
</div>
</div>
<p>Wenn wir daran mit <code>&lt;-</code> einen neuen Wert angeben, werden die aufgerufenen Werte damit überschrieben - hier überschreiben wir also alle Werte für <code>german == -32</code> mit <code>NA</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Wir könnten auch einfach alle Werte kleiner 0 auswählen:</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>german[a16<span class="sc">$</span>german <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>NA</code> ist in der R der Code für fehlende Angaben, sie werden dann in <code>table()</code> nicht aufgeführt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
3238   33  216 </code></pre>
</div>
</div>
<p>Wir können aber mit der Option <code>exclude = NULL</code> die Auszählung von <code>NA</code> explizit anfordern:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>german, <span class="at">exclude =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 &lt;NA&gt; 
3238   33  216    3 </code></pre>
</div>
</div>
<p><strong>Achtung!</strong> Die vor dem Ausschluss von <code>-32</code> abgespeicherte Tabelle <code>t1</code> ändert sich dadurch nicht:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 -32    1    2    3 
   3 3238   33  216 </code></pre>
</div>
</div>
<p>Das liegt daran, dass bei Aufruf von <code>t1</code> die abgelegten Werte, so wie sie gespeichert wurden, wieder aufgerufen werden. Es wird <strong>keine neue Auszählung</strong> vorgenommen! Möchten wir die aktualisierte Tabelle ohne die <code>NA</code> in <code>t1</code> ablegen, dann müssen wir <code>t1</code> mit den neuen Werten überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>t1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
3238   33  216 </code></pre>
</div>
</div>
<p><a href="https://tmb.njtierney.com/"><em>The missing book</em></a></p>
<section id="kumulierte-häufigkeiten" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="kumulierte-häufigkeiten"><span class="header-section-number">3.2.1</span> Kumulierte Häufigkeiten</h3>
<p>Mit <code>cumsum()</code> können wir uns die <em>kumulierten</em> Häufigkeiten ausgeben lassen. Dazu wenden wir <code>cumsum</code> auf die Häufigkeitstabelle an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2    3 
3238 3271 3487 </code></pre>
</div>
</div>
<p><em>Was sagen die Zahlen jetzt aus? 3271 Befragte haben die deutsche und evtl. noch eine weitere Staatsbürgerschaft. Für 3487 Befragte liegt eine Angabe zur Staatsbürgerschaft vor.</em></p>
<p>Die Befehlsschachtel aus <code>table()</code> und <code>cumsum()</code> können wir durch ein schrittweises Vorgehen auflösen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german) <span class="co"># ablegen wie oben</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(t1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2    3 
3238 3271 3487 </code></pre>
</div>
</div>
</section>
<section id="relative-häufigkeiten-anteile" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="relative-häufigkeiten-anteile"><span class="header-section-number">3.2.2</span> Relative Häufigkeiten (Anteile)</h3>
<p>Neben den absoluten Häufigkeiten können wir uns auch relative Häufigkeitstabellen anzeigen lassen. Dazu nutzen wir den <code>prop.table()</code> Befehl und wenden diesen wiederum entweder auf <code>table()</code> oder direkt auf <code>t1</code> an:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
0.928591913 0.009463722 0.061944365 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(t1) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
0.928591913 0.009463722 0.061944365 </code></pre>
</div>
</div>
<p><em>Wir sehen hier also, dass 92.859% aller Befragten nur die deutsche Staatsbürgerschaft haben.</em></p>
<p>Auch die relativen Häufigkeiten können wir uns als kumulierte Werte ausgeben lassen, dazu kombinieren wir <code>prop.table()</code> mit <code>cumsum()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(a16<span class="sc">$</span>german)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.9285919 0.9380556 1.0000000 </code></pre>
</div>
</div>
<p>Diese Befehlsschachtel können wir wieder vermeiden indem wir die absoluten Häufigkeiten aus <code>t1</code> aufrufen und dann die relativen Häufigkeiten unter <code>t2</code> ablegen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(t1) <span class="co"># relative Häufigkeiten unter t2 ablegen</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(t2) <span class="co"># relative kumulierte Häufigkeiten </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3 
0.9285919 0.9380556 1.0000000 </code></pre>
</div>
</div>
<p><em>Wir sehen hier also, dass 93.806% aller Befragten die deutsche und evtl. eine weitere Staatsbürgerschaft haben.</em></p>
</section>
<section id="übersichtstabelle-mit-allen-kennzahlen" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="übersichtstabelle-mit-allen-kennzahlen"><span class="header-section-number">3.2.3</span> Übersichtstabelle mit allen Kennzahlen</h3>
<p>Dies alles lässt sich zu einer Gesamttabelle im Format eines Datensatzes zusammenfassen. Dazu legen wir zunächst die absoluten Häufigkeiten in einem <code>data.frame</code> unter <code>t3</code> ab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>german) <span class="co"># wie bereits oben</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(t1) <span class="co"># t1 in einen Datensatz umformatieren</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq
1    1 3238
2    2   33
3    3  216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(t3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>Diesem <code>data.frame</code> fügen wir dann mit <code>t3$...</code> neue Variablen/Spalten hinzu. Während wir uns oben jeweils auf <code>t1</code> für die absoluten Häufigkeiten bezogen hatten, finden wir diese jetzt innerhalb von <code>t3</code> in der Spalte <code>Freq</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>H <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(t3<span class="sc">$</span>Freq) <span class="co"># kum. absolute Häufigkeiten</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H
1    1 3238 3238
2    2   33 3271
3    3  216 3487</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>f <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(t3<span class="sc">$</span>Freq) <span class="co"># rel. Häufigkeiten</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H           f
1    1 3238 3238 0.928591913
2    2   33 3271 0.009463722
3    3  216 3487 0.061944365</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>F <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(t3<span class="sc">$</span>f) <span class="co"># kum. rel. Häufigkeiten</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>t3 <span class="co"># kontrolle</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq    H           f         F
1    1 3238 3238 0.928591913 0.9285919
2    2   33 3271 0.009463722 0.9380556
3    3  216 3487 0.061944365 1.0000000</code></pre>
</div>
</div>
<p>Zum Schluss können wir mit <code>colnames</code> die Spalten klar benennen. Dazu rufen wir mit <code>colnames(t3)</code> die Spaltennamen von <code>t3</code> auf und überschreiben diese dann mit einer Folge an Werten, die wir mit <code>c()</code> angeben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(t3) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Werte"</span>, <span class="st">"h"</span>, <span class="st">"H"</span>, <span class="st">"f"</span>, <span class="st">"F"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>t3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H           f         F
1     1 3238 3238 0.928591913 0.9285919
2     2   33 3271 0.009463722 0.9380556
3     3  216 3487 0.061944365 1.0000000</code></pre>
</div>
</div>
</section>
</section>
<section id="kontingenztabellen" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="kontingenztabellen"><span class="header-section-number">3.3</span> Kontingenztabellen</h2>
<p>In dieser Session beschäftigten wir uns mit den Familienstandsangaben aus der Variable <code>mstat</code>. Wie vergangene Woche müssen wir vorab die negativen Werte (<code>-9</code>, siehe Codebuch) mit <code>NA</code> überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>mstat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  -9    1    2    3    4    5    6    9 
   2 1919   60  236  316  949    7    1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>mstat[a16<span class="sc">$</span>mstat <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>mstat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    9 
1919   60  236  316  949    7    1 </code></pre>
</div>
</div>
<p>Aus Kontingenztabellen erfahren wir, wie häufig Merkmalskombinationen auftreten. Auch für Kontingenztabellen können wir <code>table()</code> verwenden. Zum Beispiel können wir uns eine Tabelle anzeigen lassen, die uns die Häufigkeiten des Familienstatus getrennt nach Geschlechtern zeigt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>sex, a16<span class="sc">$</span>mstat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
       1    2    3    4    5    6    9
  1 1011   33   56  133  534    2    0
  2  908   27  180  183  415    5    1</code></pre>
</div>
</div>
<p>Wir erkennen aus dieser Tabelle beispielsweise, dass 415 Befragte weiblich (<code>sex=2</code>) und ledig (<code>mstat = 5</code>) sind.</p>
<!-- [^5]: Hier ist das Geschlechts als binäres Merkmal codiert. Die Einführung der dritten Option im Dez 2018 wird aber in künftigen Erhebungen auch im Allbus berücksichtigt werden. Bis dahin müssen wir mit den Kategorien arbeiten, die uns hier vorgegeben sind.  -->
<p>Eine Alternative zu <code>table()</code> ist <code>xtabs()</code>. Hier werden die Spalten und Zeilen beschriftet. Der Übersichtlichkeit halber verwenden wir diese Darstellung, alle Operationen sind aber genauso auch mit <code>table</code> möglich. Da wir mit dieser Kontingenztabelle noch etwas weiter arbeiten werden, legen wir sie unter <code>kt</code> ab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span>sex<span class="sc">+</span>mstat, <span class="at">data =</span> a16)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex    1    2    3    4    5    6    9
  1 1011   33   56  133  534    2    0
  2  908   27  180  183  415    5    1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>kt <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span>sex<span class="sc">+</span>mstat, <span class="at">data =</span> a16) </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>kt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex    1    2    3    4    5    6    9
  1 1011   33   56  133  534    2    0
  2  908   27  180  183  415    5    1</code></pre>
</div>
</div>
<section id="relative-häufigkeiten" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="relative-häufigkeiten"><span class="header-section-number">3.3.1</span> Relative Häufigkeiten</h3>
<p>Auch hier können wir uns die relativen Häufigkeiten anzeigen lassen, indem wir <code>prop.table()</code> anwenden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(kt) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex            1            2            3            4            5
  1 0.2898509174 0.0094610092 0.0160550459 0.0381307339 0.1530963303
  2 0.2603211009 0.0077408257 0.0516055046 0.0524655963 0.1189793578
   mstat
sex            6            9
  1 0.0005733945 0.0000000000
  2 0.0014334862 0.0002866972</code></pre>
</div>
</div>
<p>Die hier dargestellten relativen Häufigkeiten beziehen sich jeweils auf die Gesamtzahl der Befragten. Formal dargestellt wird also für die Kombination weiblich (<code>sex=2</code>) und ledig (<code>mstat = 5</code>) die Anzahl ledigen Frauen durch die Anzahl <strong>aller Befragten</strong> geteilt: <span class="math inline">\(\frac{Anzahl\,lediger\,Frauen}{Gesamtzahl\,der\,Befragten}\)</span> - Wir können also aus dieser Tabelle ablesen dass <code>11,9%</code> der Befragten <em>weiblich und ledig</em> sind.</p>
</section>
<section id="zeilen--und-spaltenprozente" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="zeilen--und-spaltenprozente"><span class="header-section-number">3.3.2</span> Zeilen- und Spaltenprozente</h3>
<p>Wir können diese Tabelle auch mit <em>Zeilen- und Spaltenprozenten</em> anzeigen lassen, indem wir die Option <code>margin</code> verwenden. <code>margin=1</code> liefert die <strong>Zeilenprozente</strong>, <code>margin=2</code> die <strong>Spaltenprozente</strong>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(kt,<span class="at">margin =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex      1      2      3      4      5      6      9
  1 0.5715 0.0187 0.0317 0.0752 0.3019 0.0011 0.0000
  2 0.5282 0.0157 0.1047 0.1065 0.2414 0.0029 0.0006</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(kt,<span class="at">margin =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex      1      2      3      4      5      6      9
  1 0.5268 0.5500 0.2373 0.4209 0.5627 0.2857 0.0000
  2 0.4732 0.4500 0.7627 0.5791 0.4373 0.7143 1.0000</code></pre>
</div>
</div>
<p><em>Achtung!</em> Damit ändert sich jeweils die Interpretation der Tabelle! Wir ändern durch <code>margin</code> die Bezugsgröße oder formal ausgedrückt den Nenner:</p>
<ul>
<li>Für die Zeilenprozente werden die Werte in Bezug zu den Zeilensummen gesetzt. Also wird die Anzahl der ledigen Frauen ins Verhältnis zur Zahl der befragten Frauen gesetzt: <span class="math inline">\(\frac{Anzahl\,lediger\,Frauen}{Gesamtzahl\,der\,befragten\,Frauen}\)</span> - Interpretation: “<code>24,14%</code> der befragten Frauen sind ledig”<br>
</li>
<li>Für die Spaltenprozente werden die Werte in Bezug zu den Spaltensummen gesetzt. Also wird die Anzahl der ledigen Frauen ins Verhältnis zur Zahl der ledigen Befragten gesetzt: <span class="math inline">\(\frac{Anzahl\,lediger\,Frauen}{Gesamtzahl\,der\,ledigen\,Befragten}\)</span> - Interpretation: “<code>43,73%</code> der ledigen Befragten sind Frauen”</li>
</ul>
</section>
</section>
<section id="arbeiten-mit-der-pipe" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="arbeiten-mit-der-pipe"><span class="header-section-number">3.4</span> Arbeiten mit der Pipe</h2>
<p>Unter <code>kt</code> hatten wir das Ergebnis des <code>xtabs</code>-Befehls abgelegt: <code>xtabs(~sex+mstat, data = a16)</code>. Wenn wir also alles “ausschreiben”, dann ergibt sich folgender, verschachtelter Befehl:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(   <span class="fu">prop.table</span>( <span class="fu">xtabs</span>(<span class="sc">~</span>sex<span class="sc">+</span>mstat, <span class="at">data =</span> a16), <span class="at">margin =</span> <span class="dv">1</span>)   ,<span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex    1    2    3    4    5    6    9
  1 0.57 0.02 0.03 0.08 0.30 0.00 0.00
  2 0.53 0.02 0.10 0.11 0.24 0.00 0.00</code></pre>
</div>
</div>
<p>Diese Befehlsschachtel können wir mit der sog. Pipe <code>%&gt;%</code> auflösen und besser darstellen. <code>%&gt;%</code> steht dabei einfach für “und dann”. Die Pipe ist unter anderem Teil des Pakets <code>dplyr</code>, welches wir in Zukunft häufiger verwenden werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mit der Pipe sieht die Befehlsschachtel dann so aus und wir können sie von links nach rechts lesen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">xtabs</span>(<span class="sc">~</span>sex<span class="sc">+</span>mstat, <span class="at">data =</span> a16) <span class="sc">%&gt;%</span> <span class="fu">prop.table</span>(., <span class="at">margin =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="fu">round</span>(.,<span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mstat
sex    1    2    3    4    5    6    9
  1 0.57 0.02 0.03 0.08 0.30 0.00 0.00
  2 0.53 0.02 0.10 0.11 0.24 0.00 0.00</code></pre>
</div>
</div>
<p>Der Punkt <code>.</code> steht jeweils für das Ergebnis des vorherigen Schritts. Hier also:</p>
<ol type="1">
<li>erstelle die Kontingenztabelle <em>und dann (<code>%&gt;%</code>)</em></li>
<li>berechne daraus die relativen Häufigkeiten mit <code>margin = 1</code> <em>und dann (<code>%&gt;%</code>)</em></li>
<li>runde das Ergebnis auf 2 Nachkommastellen</li>
</ol>
<blockquote class="blockquote">
<p>Tipp:<code>%&gt;%</code> kann mit STRG+SHIFT+m (cmd+shift+m für Mac) eingefügt werden.</p>
</blockquote>
</section>
<section id="metrische-variablen" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="metrische-variablen"><span class="header-section-number">3.5</span> Metrische Variablen</h2>
<p>Das bisherige Beispiel Staatsbürgerschaft (<code>german</code>) bezog sich auf ein kategoriales Merkmal. Für ein metrisches Merkmal, wie zum Beispiel das Geburtsjahr macht eine Häufigkeitstabelle wenig Sinn, da das Geburtsjahr sehr viele Ausprägungen hat und eine Tabelle unübersichtlich wäre - hier nur als Beispiel die ersten 20 Ausprägungen (es gibt insgesamt 77!):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
-32  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 
  4  29  41  43  43  41  45  34  40  48  36  49  43  58  49  47  51  65  54  42 </code></pre>
</div>
</div>
<p>Um eine Häufigkeitstabelle zu erstellen müssen wir bei metrischen Merkmalen Klassen bilden. So könnten wir das Alter in Lebensjahrzehnte unterteilen. Zuvor müssen wir wieder die fehlenden Angaben<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> überschreiben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age[a16<span class="sc">$</span>age <span class="sc">==</span> <span class="sc">-</span><span class="dv">32</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Um die Klassen zu bilden, nutzen wir <code>cut()</code> und geben neben der zu unterteilenden Variable mit <code>breaks</code> die Klassengrenzen an. Für die Grenzen können wir <code>seq()</code> verwenden. Darin geben wir zunächst die obere und untere Grenze an und dann die Schrittbreiten. Diese Werte legen wir in einer neuen Variable in <code>a16</code> ab:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age_zehner <span class="ot">&lt;-</span> <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">90</span>,<span class="dv">100</span>) )</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>a16<span class="sc">$</span>age_zehner <span class="ot">&lt;-</span> <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">10</span>,<span class="dv">100</span>,<span class="dv">10</span>) ) <span class="co"># kürzer mit seq()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Für diese neue Variable können wir mit <code>table()</code> eine Häufigkeitstabelle anfordern:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(a16<span class="sc">$</span>age_zehner)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 (10,20]  (20,30]  (30,40]  (40,50]  (50,60]  (60,70]  (70,80]  (80,90] 
     113      437      491      605      710      579      419      127 
(90,100] 
       5 </code></pre>
</div>
</div>
<p><code>(</code> bedeutet dabei ausgeschlossen, <code>]</code> inklusive. Es gibt also 437 Befragte, die über 20 bis inklusive 30 Jahre alt sind.<br>
Wir haben also durch Klassierung aus dem metrischen Merkmal <code>age</code> ein kategoriales Merkmal <code>age_zehner</code> erstellt. Damit können wir dann genauso arbeiten wie oben - zB für die kumulierten relativen Häufigkeiten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>age_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>age_zehner) <span class="co"># abs Häufigkeiten</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>age_tab2 <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(age_tab) <span class="co"># rel Häufigkeiten</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(age_tab2) <span class="co"># kumulieren</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] 
0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 
   (80,90]   (90,100] 
0.99856569 1.00000000 </code></pre>
</div>
</div>
<p><em>Wir sehen hier so, dass 47.217% aller Befragten 50 Jahre oder jünger sind.</em></p>
<p>Wir könnten alles auch in einem Befehl zusammen durchführen, das wird aber schnell unübersichtlich:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>( <span class="fu">cut</span>(a16<span class="sc">$</span>age, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">10</span>,<span class="dv">100</span>,<span class="dv">10</span>) ) )))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (10,20]    (20,30]    (30,40]    (40,50]    (50,60]    (60,70]    (70,80] 
0.03241538 0.15777395 0.29862306 0.47217441 0.67584624 0.84193919 0.96213425 
   (80,90]   (90,100] 
0.99856569 1.00000000 </code></pre>
</div>
</div>
</section>
<section id="lage--konzentrationsmaße" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="lage--konzentrationsmaße"><span class="header-section-number">3.6</span> Lage- &amp; Konzentrationsmaße</h2>
<p>Für die Beispiele verwenden wir die Angaben aus dem Jahr 2014. Diese Auswahl können wir mit <code>[]</code> treffen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>a14 <span class="ot">&lt;-</span> ak[ak<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2014</span>,] <span class="co"># basis R</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="lagemaße" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="lagemaße"><span class="header-section-number">3.6.1</span> Lagemaße</h3>
<p>Lagemaße sind statische Kennzahlen zur Beschreibung von metrischen Variablen. Einen Überblick bietet <code>summary()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(a14<span class="sc">$</span>di05)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    -50      -7    1800    2051    3000   80400 </code></pre>
</div>
</div>
<p>Natürlich gibt es keine Haushalte, die ein Einkommen von <code>-50</code> Euro pro Monat haben. Um aussagekräftige Werte zu bekommen, müssen wir diese Werte mit <code>NA</code> überschreiben:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>a14<span class="sc">$</span>di05[a14<span class="sc">$</span>di05 <span class="sc">&lt;</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span> <span class="co"># missings überschreiben</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(a14<span class="sc">$</span>di05)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     50    1500    2400    2739    3500   80400     869 </code></pre>
</div>
</div>
<p>Wir können aber auch bestimmte Kennzahlen anfordern sehen uns die Haushaltseinkommen der Befragten (<code>di05</code>) im Allbus 2014 mit Hilfe folgender Befehle an:</p>
<ul>
<li>Minimum und Maximum: <code>min()</code>, <code>max()</code></li>
<li>arithm. Mittel: <code>mean()</code></li>
<li>Median: <code>median()</code></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(a14<span class="sc">$</span>di05) <span class="co"># kleinster Wert</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>Wenn eine Variable <code>NA</code> enthält, müssen diese explizit ignoriert werden - ansonsten wird nur <code>NA</code> ausgegeben:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(a14<span class="sc">$</span>di05)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>Deshalb müssen wir die Option <code>na.rm = T</code> angeben:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(a14<span class="sc">$</span>di05,<span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(a14<span class="sc">$</span>di05,<span class="at">na.rm =</span> T) <span class="co">#größter Wert</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80400</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2739.063</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2400</code></pre>
</div>
</div>
</section>
<section id="streuungsmaße" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="streuungsmaße"><span class="header-section-number">3.6.2</span> Streuungsmaße</h3>
<section id="quantile" class="level4" data-number="3.6.2.1">
<h4 data-number="3.6.2.1" class="anchored" data-anchor-id="quantile"><span class="header-section-number">3.6.2.1</span> Quantile</h4>
<p>Ein Quantil einer Verteilung trennt die Daten so in zwei Teile, dass <code>x</code>% der Daten darunter und 100-<code>x</code>% darüber liegen. Gebräuchlich sind die Quartile, welche die Grenzen für 25%, 50% und 75% angeben. Diese werden auch standardmäßig von <code>quantile()</code> ausgegeben:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05,<span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   25%   50%   75%  100% 
   50  1500  2400  3500 80400 </code></pre>
</div>
</div>
<p>Musterinterpretation:</p>
<ul>
<li><em>25% der Befragten haben ein HH-Einkommen von 1500€ oder weniger</em></li>
<li><em>75% der Befragten haben ein HH-Einkommen von 3500€ oder weniger</em></li>
</ul>
<p>Daraus ergibt sich auch:</p>
<ul>
<li><em>75% der Befragten haben ein HH-Einkommen von 1500€ oder mehr</em></li>
</ul>
<p>Wir können aber durch Angabe in den Optionen beliebige Quantilgrenzen anfordern, zB. für die 40%-Quantilgrenze:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05,<span class="at">probs =</span> .<span class="dv">4</span>, <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 40% 
2000 </code></pre>
</div>
</div>
<p>In Kombination mit <code>seq()</code> können wir zB. auch die Dezilgrenzen (entlang der Vielfachen von 0,1) anfordern:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05,<span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.1</span>,<span class="fl">0.2</span>,<span class="fl">0.3</span>,<span class="fl">0.4</span>,<span class="fl">0.5</span>,<span class="fl">0.6</span>,<span class="fl">0.7</span>,<span class="fl">0.8</span>,<span class="fl">0.9</span>,<span class="dv">1</span>), <span class="at">na.rm =</span> T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% 
   50  1000  1400  1723  2000  2400  2800  3200  3800  4800 80400 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05,<span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.1</span>), <span class="at">na.rm =</span> T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   10%   20%   30%   40%   50%   60%   70%   80%   90%  100% 
   50  1000  1400  1723  2000  2400  2800  3200  3800  4800 80400 </code></pre>
</div>
</div>
</section>
<section id="interquartilsdistanz-und-interdezilsdistanz" class="level4" data-number="3.6.2.2">
<h4 data-number="3.6.2.2" class="anchored" data-anchor-id="interquartilsdistanz-und-interdezilsdistanz"><span class="header-section-number">3.6.2.2</span> Interquartilsdistanz und Interdezilsdistanz</h4>
<p>Aus den Quantilen leiten sich auch die Inter<strong>quartil</strong>sdistanz und Inter<strong>dezil</strong>sdistanz ab.<br>
Die Interquartilsdistanz ist schlicht die Differenz zwischen dem ersten und dritten Quartil. Genauso ist die Interdezilsdistanz die Differenz zwischen dem neunten und ersten Dezil:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05, .<span class="dv">75</span>, <span class="at">na.rm =</span> T) <span class="sc">-</span> <span class="fu">quantile</span>(a14<span class="sc">$</span>di05, .<span class="dv">25</span>, <span class="at">na.rm =</span> T) <span class="co"># IQR</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 75% 
2000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(a14<span class="sc">$</span>di05, .<span class="dv">9</span>, <span class="at">na.rm =</span> T) <span class="sc">-</span> <span class="fu">quantile</span>(a14<span class="sc">$</span>di05, .<span class="dv">1</span>, <span class="at">na.rm =</span> T) <span class="co"># IDR</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 90% 
3800 </code></pre>
</div>
</div>
<p><strong>Achtung</strong>: R zeigt nach der Berechnung der Differenz trotzdem die Beschriftung des Minuenden / des ersten Argumentes an!<br>
</p>
</section>
<section id="varianz-standardabweichung-variationskoeffizient" class="level4" data-number="3.6.2.3">
<h4 data-number="3.6.2.3" class="anchored" data-anchor-id="varianz-standardabweichung-variationskoeffizient"><span class="header-section-number">3.6.2.3</span> Varianz, Standardabweichung, Variationskoeffizient</h4>
<p>Die häufigste Kennzahl zur Beschreibung von Streuung ist aber die Varianz. Die Varianz ist definiert als die durchschnittliche quadrierte Abweichung vom arith. Mittel: <span class="math display">\[var(x) = \frac{\sum_{i=1}^{n} (x_{i}-\bar{x})^2}{n}\]</span><br>
Was bedeutet diese Formel?<br>
Schauen wir erst in den Zähler des Bruchs: <span class="math inline">\((x_{i}-\bar{x})^2\)</span> Es geht also um die Abstände der einzelnen Datenpunkte (<span class="math inline">\(x_{i}\)</span>) zum arithmetischen Mittel (<span class="math inline">\(\bar{x}\)</span>) - mathematisch die Differenz zwischen den einzelnen Datenpunkten <span class="math inline">\(x_{i}-\bar{x}\)</span> - hier eingezeichnet als gestrichelte Linien:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_desc_files/figure-html/unnamed-chunk-25-1.png" style="width:55.0%;height:55.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Für Punkte, die über dem arith. Mittel liegen, erhalten wir für die Differenz einen positiven Wert (wir ziehen ja jeweils das arith. Mittel vom Wert für den Datenpunkt ab). Für Punkte mit Werten, die kleiner als das arith. Mittel sind, erhalten wir einen negativen Wert.<br>
Würden wir die Abstände (gestrichelten Linien) einfach aufsummieren, erhielten wir als Ergebnis immer Null! Das arithmetische Mittel liegt ja per Definition immer genau “in der Mitte”: die Abstände nach oben sind in der Summe genauso groß wie die Abstände nach unten. Daher wird zunächst jeder Abstand quadriert: <span class="math inline">\((\bar{x} - x_{i})^2\)</span><br>
Der Rest der Formel gibt dann an, dass alle quadrierten Differenzen aufsummiert (<span class="math inline">\(\sum_{i=1}^{n}\)</span>) und dann durch die Anzahl der Beobachtungen geteilt werden (<span class="math inline">\(\frac{}{n}\)</span>)- zusammengefasst hier nochmal die Formel: <span class="math display">\[var(x) = \frac{\sum_{i=1}^{n} (x_{i}-\bar{x})^2}{n}\]</span></p>
<p>Wir können die Varianz mit <code>var()</code> berechnen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T) <span class="co"># Varianz</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6387969</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>In unseren Datensatz beträgt der Varianz der Haushaltseinkommen also 6.387.969€². Auf der Varianz beruhen noch zwei weitere Streuungsmaße. Die <em>Standardabweichung</em> entspricht der Wurzel der Varianz und hat somit die gleiche Messeinheit wie die Variable (hier EUR). Der <em>Variationskoeffizient</em> entspricht <code>sd</code>/<code>mean</code> und dient dem Vergleich verschiedener Streuungen relativ zum jeweiligen Mittelwert:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">var</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2527.443</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T) <span class="co"># Standardabweichung</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2527.443</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T) <span class="sc">/</span> <span class="fu">mean</span>(a14<span class="sc">$</span>di05, <span class="at">na.rm =</span> T) <span class="co"># Variationskoeffizient</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9227402</code></pre>
</div>
</div>
<p>Für alle Streuungsmaße gilt: je größer, desto mehr Streuung (Unterschiede) gibt es in den Daten.</p>
</section>
<section id="gini-koeffizient" class="level4" data-number="3.6.2.4">
<h4 data-number="3.6.2.4" class="anchored" data-anchor-id="gini-koeffizient"><span class="header-section-number">3.6.2.4</span> Gini-Koeffizient</h4>
<p>Zur Beschreibung der Verteilung von Einkommens- und Vermögensdaten wird häufig der Gini-Koeffizient verwendet. Der Gini-Koeffizient beruht auf der Fläche zwischen der Lorenzkurve und der Gleichverteilung. Auf der x-Achse werden die kumulierten Perzentile der Befragten abgetragen, auf der y-Achse die Perzentile des HH-Einkommens:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_desc_files/figure-html/gini_plot1-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_desc_files/figure-html/unnamed-chunk-27-1.png" style="width:75.0%;height:75.0%" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Den Gini-Koeffizienten können wir mit <code>Gini()</code> aus dem Paket <code>ineq</code> berechnen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ineq"</span>) <span class="co"># einmal installieren</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ineq) <span class="co"># ineq laden</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Gini</span>(a14<span class="sc">$</span>di05)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3286304</code></pre>
</div>
</div>
</section>
</section>
<section id="lage--und-streuungsmaße-vergleichen" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="lage--und-streuungsmaße-vergleichen"><span class="header-section-number">3.6.3</span> Lage- und Streuungsmaße vergleichen</h3>
<p>Häufig werden diese Kennzahlen erst im Vergleich richtig spannend. zB können wir die Einkommensangaben aus den alten und neuen Bundesländern vergleichen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> T) <span class="co"># alte Bundesländer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2921.727</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>], <span class="at">na.rm =</span> T) <span class="co"># neue Bundesländer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2347.703</code></pre>
</div>
</div>
<p>In den neuen Bundesländern ist das durchschnittliche HH-Einkommen um 574.024€ niedriger.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> T) <span class="co"># alte Bundesländer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2600</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>], <span class="at">na.rm =</span> T) <span class="co"># neue Bundesländer</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2000</code></pre>
</div>
</div>
<p>In den neuen Bundesländern ist das Median-HH-Einkommen um 600€ niedriger. Die Variationskoeffizienten zeigen eine größere Streuung im Osten als im Westen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> T) <span class="sc">/</span> </span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8501129</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>], <span class="at">na.rm =</span> T) <span class="sc">/</span> </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>], <span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.097566</code></pre>
</div>
</div>
<p>Wir können auch für das gesamte <code>summary</code> die Differenz zwischen Ost und West bilden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>], <span class="at">na.rm =</span> T) <span class="sc">-</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>], <span class="at">na.rm =</span> T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     30     400     600     574     800   15400     307 </code></pre>
</div>
</div>
<p>In den neuen Ländern lag das Median-HH-Einkommen um 600€ niedriger als im Westen. Die 25% bzw. 75% Quartilsgrenze lag um 400€ bzw 800€ niedriger, das arith. Mittel war um 574€ niedriger als in den alten Bundesländern.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Gini</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3182835</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Gini</span>(a14<span class="sc">$</span>di05[a14<span class="sc">$</span>eastwest <span class="sc">==</span> <span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3346088</code></pre>
</div>
</div>
<p>Wo ist die Ungleichheit nun höher? In Ost oder West?</p>
</section>
</section>
<section id="aufgaben-2-lage--konzentrationsmaße" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="aufgaben-2-lage--konzentrationsmaße"><span class="header-section-number">3.7</span> Aufgaben 2: Lage- &amp; Konzentrationsmaße</h2>
<p>Forschungsfrage: Wie hat sich die Haushaltseinkommensverteilung zwischen 1994 und 2010 entwickelt?</p>
<ol type="1">
<li><p>Laden Sie den <strong>kumulierten</strong> Allbusdatensatz in R (siehe <a href="#einlesen">oben</a>).</p></li>
<li><p>Erstellen Sie jeweils einen Datensatz für das Befragungsjahr 1994 und 2010 - filtern Sie mit <code>[]</code> also den kumulierten Datensatz jeweils einmal nach einem Jahr und legen Sie das Ergebnis in <code>a94</code> bzw. <code>a10</code> ab</p></li>
<li><p>Betrachten Sie zunächst für 1994 die Haushaltseinkommensverteilung (Variable <code>di05</code>)</p></li>
</ol>
<ul>
<li>Denken Sie daran, die negativen Werte mit <code>NA</code> zu überschreiben!</li>
<li>Berechnen Sie das arithm. Mittel, den Median, das 25%- und 75%-Quartil sowie die Varianz - was sagen Ihnen die Werte jeweils?</li>
<li>Berechnen Sie die Interdezildistanz und die Spannweite!</li>
<li>Berechnen Sie den Gini-Koeffizenten!</li>
</ul>
<ol start="4" type="1">
<li>Betrachten Sie dann die Haushaltseinkommensverteilung für 2010 (Variable <code>di05</code>)</li>
</ol>
<ul>
<li>Denken Sie daran, die negativen Werte mit <code>NA</code> zu überschreiben!</li>
<li>Berechnen Sie das arithm. Mittel, den Median, das 25%- und 75%-Quartil sowie die Varianz und den Gini-Koeffizienten für alle Fälle im Datensatz für 2010 - was sagen Ihnen die Werte jeweils?</li>
<li>Berechnen Sie die Interdezildistanz und die Spannweite!</li>
</ul>
<ol start="5" type="1">
<li>Berechnen Sie für 1994 getrennt nach Ost und West (Variable <code>eastwest</code>) - welche Werte erhalten Sie jeweils für folgende Kennzahlen in Ost und West? (Denken Sie an <code>summary()</code>):</li>
</ol>
<ul>
<li>arithm. Mittel, den Median, das 25%- und 75%-Quartil</li>
<li>Variationskoeffizient</li>
<li>Gini-Koeffizient</li>
</ul>
<ol start="6" type="1">
<li>Vergleichen Sie diese Ost-West-Unterschiede im Jahr 1994 mit denen für das Jahr 2010. Welche Tendenz können Sie für die Ost-West-Unterschiede erkennen?</li>
</ol>
</section>
<section id="aufgaben" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="aufgaben"><span class="header-section-number">3.8</span> Aufgaben</h2>
<ol type="1">
<li>Laden Sie den Allbusdatensatz <code>allbus_kompakt.csv</code> mit dem csv-Import in R:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"..."</span>) <span class="co"># wo liegt der Datensatz?</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>a16 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"allbus2016_kompakt.csv"</span>,<span class="at">sep =</span> <span class="st">";"</span>,<span class="at">header =</span> T,<span class="at">stringsAsFactors =</span> F) <span class="co"># einlesen</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Wir interessieren uns für die Variable <code>gkpol</code>.</li>
</ol>
<ul>
<li>Suchen Sie die Variable im Codebuch: welche Information können Sie dieser Variable entnehmen?</li>
<li>Welches Skalenniveau hat die Variable? (inhaltliche Frage, keine R-Frage)</li>
<li>Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten?</li>
<li>Lassen Sie sich eine Tabelle mit den absoluten Häufigkeiten anzeigen. Welche ist die häufigste Ausprägung, wofür steht die Kategorie? (Sehen Sie im Codebuch nach)</li>
<li>Hat die Variable fehlende Werte, die Sie ausschließen sollten? Falls ja, ersetzen Sie diese Werte mit <code>NA</code> und lassen Sie sich die Tabelle erneut ausgeben.</li>
</ul>
<ol start="3" type="1">
<li>Erstellen Sie eine vollständige Häufigkeitstabelle für die Variable <code>gkpol</code>, welche folgende Informationen enthält:</li>
</ol>
<ul>
<li>absolute Häufigkeiten</li>
<li>relative Häufigkeiten</li>
<li>kumulierte absolute Häufigkeiten</li>
<li>kumulierte relative Häufigkeiten</li>
<li>Wie viele Befragte leben in einem Ort mit höchstens 49.999 Einwohnern?</li>
<li>Wie groß ist der Anteil der Befragten, die in einem Ort mit höchstens 99.999 Einwohnern leben?</li>
<li>Wie groß ist der Anteil der Befragten, die in einem Ort mit <em>mindestens</em> 100.000 Einwohnern leben?</li>
</ul>
<ol start="4" type="1">
<li>Erstellen Sie eine Häufigkeitstabelle für das Geburtsjahr der Befragten (<code>yborn</code>)!</li>
</ol>
<ul>
<li>Welches Skalenniveau hat die Variable? (inhaltliche Frage, keine R-Frage)</li>
<li>Müssen Sie die Variable erst klassieren um eine sinnvoll interpretierbare Tabelle zu erhalten? Beachten Sie dazu auch die <a href="#hinweis_cut_w103">Hinweise</a> am Ende dieses Dokuments. Verwenden Sie die Jahrzehntgrenzen ab 1910.</li>
<li>Erstellen Sie eine Tabelle welche die absoluten Häufigkeiten anzeigt</li>
<li>Gibt es fehlende Werte, die Sie mit <code>NA</code> überschreiben sollten?</li>
<li>Erstellen Sie eine zweite Version dieser Tabelle mit relativen Häufigkeiten</li>
<li>Wie groß ist der Anteil der Befragten, die bis 1970 geboren wurden?</li>
<li>Wie groß ist der Anteil der Befragten, die nach 1980 geboren wurden?</li>
</ul>
</section>
<section id="profi-aufgaben" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="profi-aufgaben"><span class="header-section-number">3.9</span> Profi-Aufgaben</h2>
<p>Für alle, die noch etwas mehr machen möchten:</p>
<ul>
<li>Runden Sie die Angaben zur relativen Häufigkeit auf 3 Nachkommastellen!</li>
<li>Lassen Sie sich von R die häufigste Ausprägung für <code>yborn</code> ausgeben</li>
<li>Fügen Sie der vollständigen Häufigkeitstabelle für die Variable <code>gkpol</code> eine neue Spalte hinzu, welche die Bedeutung der Zahlencodes wiedergibt!</li>
</ul>
<p>Tipps dazu finden Sie in den Hinweisen am Ende! (Wissen aus diesen Aufgaben wird nicht vorausgesetzt in den kommenden Wochen, aber es hilft natürlich)</p>
</section>
<section id="häufige-fehlermeldungen" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="häufige-fehlermeldungen"><span class="header-section-number">3.10</span> Häufige Fehlermeldungen</h2>
<p>Die Arbeit in R ist - wie in jedem Datenanalyseprogramm - ein Hangeln von Fehlermeldung zu Fehlermeldung. Das kann gerade zu Beginn frustrierend sein, bis die tiefere Bedeutung von Fehlermeldungen und deren Ursachen etwas deutlicher werden. Die folgende Auflistung enthält einige der häufigsten Fehlermeldungen und ihre (wahrscheinlichsten) Ursachen. Die Liste lehnt sich stark an die die großartige Zusammenstellung von <a href="https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html">Nick C. Huntington-Klein</a> an.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://twitter.com/emilynordmann/status/1548942198246440962?s=11&amp;t=vemXPmcotIqs4hP5J__XvQ">Fehlerliste</a> als Lernhilfe</p>
</div>
</div>
<section id="there-is-no-package-called" class="level3" data-number="3.10.1">
<h3 data-number="3.10.1" class="anchored" data-anchor-id="there-is-no-package-called"><span class="header-section-number">3.10.1</span> There is no package called</h3>
<p>Die Fehlermeldung <code>there is no package called 'XXXX'</code> erscheint, wenn Sie ein Paket bspw. mit <code>library()</code> laden, diese Paket allerdings nicht installiert ist.</p>
<p>The Fix:</p>
<ol type="1">
<li>Did you spell the package name correctly? Maybe you do have the package, but you made a typo</li>
<li>If you spelled it correctly, you may not have installed it. Install it (usually) with <code>install.packages('packagename')</code> where <code>'packagename'</code> is replaced with the name of the package you actually want.</li>
</ol>
</section>
<section id="could-not-find-function" class="level3" data-number="3.10.2">
<h3 data-number="3.10.2" class="anchored" data-anchor-id="could-not-find-function"><span class="header-section-number">3.10.2</span> Could not find function</h3>
<p>Die Fehlermeldung <code>could not find function "XXX"</code> weist darauf hin, dass R die genannte Funktion nicht finden kann.</p>
<p>The Fix:</p>
<ol type="1">
<li>Did you spell the function name correctly? Maybe you made a typo.</li>
<li>If the function is in a package, did you load the package? Remember, the package must be re-loaded every time you restart R. If you’re working in RMarkdown, you must load the package inside of your RMarkdown script, since RMarkdown starts from a blank slate.</li>
</ol>
</section>
<section id="object-not-found" class="level3" data-number="3.10.3">
<h3 data-number="3.10.3" class="anchored" data-anchor-id="object-not-found"><span class="header-section-number">3.10.3</span> Object not found</h3>
<p>If you get an error like <code>object 'objectname' not found</code>, that means that you’ve made a reference to an object called <code>objectname</code>, but there is no such object to refer to.</p>
<p>The Fix:</p>
<ol type="1">
<li>Did you spell the object’s name correctly? Maybe you made a typo.</li>
<li>Did you remember to create the object before referring to it? For example, the code <code>mean(x); x &lt;- 1:10</code> would not work, because you try to take the mean of <code>x</code> before it’s been created. If you’re working in RMarkdown, remember that it will start from a blank slate, so you must create all objects inside of your Rmarkdown script.</li>
</ol>
</section>
<section id="object-of-type-closure-is-not-subsettable" class="level3" data-number="3.10.4">
<h3 data-number="3.10.4" class="anchored" data-anchor-id="object-of-type-closure-is-not-subsettable"><span class="header-section-number">3.10.4</span> Object of type ‘closure’ is not subsettable</h3>
<p>This is the most aggravating and least-informative R error. “Subsettable” is a hint though - you’re trying to take a subset of something (such as picking an element from a vector, or picking a column from a data set), but the thing you’re doing it to is a “closure” that you can’t do that to.</p>
<p>Most commonly, this is a case of accidentally giving the name of a function where you mean to give the name of a vector or data frame. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>mean_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">person =</span> <span class="fu">c</span>(<span class="st">'Me'</span>,<span class="st">'You'</span>), <span class="at">meanness =</span> <span class="fu">c</span>(<span class="dv">1000</span>,<span class="dv">999</span>))</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let's look at that meanness variable, but oops, I'm referring to the function mean() instead of my data mean_data</span></span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>mean<span class="sc">$</span>meanness</span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Error in mean$meanness : object of type 'closure' is not subsettable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Fix:</p>
<ol type="1">
<li>See where it says the error is “in” - that’s the place where you’ve referred to the wrong thing. fix it!</li>
</ol>
</section>
<section id="column-doesnt-exist" class="level3" data-number="3.10.5">
<h3 data-number="3.10.5" class="anchored" data-anchor-id="column-doesnt-exist"><span class="header-section-number">3.10.5</span> Column doesn’t exist</h3>
<p>If you get an error like <code>column 'columnname' doesn't exist</code>, that means it’s trying to refer to a column name that is not actually in your data.</p>
<p>The Fix:</p>
<ol type="1">
<li>Did you spell the column’s name correctly? Maybe you made a typo.</li>
<li>Are you referring to the proper dataset? Maybe you created the variable in <code>my_data2</code> but you’re trying to access it in <code>my_data</code>.</li>
<li>Does your column name have spaces or other strange characters in it like dashes? If so, in many applications (anywhere you’re not treating the column name as a string) you have to surround the column name in backticks (`) so it knows where the column name starts and ends.</li>
<li>Did you perhaps drop the column before trying to refer to it? For example, in the below code, the <code>group_by() %&gt;% summarize()</code> will only keep columns named in the <code>group_by()</code> or in the <code>summarize()</code>. So even though the <code>mpg</code> column was there at the start, it no longer is by the time we refer to it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(am) <span class="sc">%&gt;%</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_hp =</span> <span class="fu">mean</span>(hp)) <span class="sc">%&gt;%</span></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hp_by_mpg =</span> mean_hp<span class="sc">/</span>mpg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="warning-package-was-compiled-with-r-version" class="level3" data-number="3.10.6">
<h3 data-number="3.10.6" class="anchored" data-anchor-id="warning-package-was-compiled-with-r-version"><span class="header-section-number">3.10.6</span> Warning: Package was compiled with R version</h3>
<p>If you load a package and get a warning that looks like <code>Warning: packagename was compiled with R version...</code>, that just means that the package was compiled using a slightly newer version of R than yours. It’s generally not a problem as long as you have a somewhat-recent version of R.</p>
<p>The Fix:</p>
<ol type="1">
<li>Ignore it</li>
<li>If you want it to go away, update your R installation.</li>
</ol>
</section>
<section id="rtools-is-required-to-build-packages-from-source" class="level3" data-number="3.10.7">
<h3 data-number="3.10.7" class="anchored" data-anchor-id="rtools-is-required-to-build-packages-from-source"><span class="header-section-number">3.10.7</span> Rtools is required to build packages from source</h3>
<p>If you are installing packages, you may be asked whether you’d like to build packages from source. If you say “Yes”, but you do not have Rtools installed, you will get an error, and the package won’t install properly.</p>
<p>The Fix:</p>
<ol type="1">
<li>When asked whether you want to install packages from source, say “No.”</li>
<li>Install Rtools before installing packages. The easiest way to do this is to install the <strong>installr</strong> package, and then run <code>installr::install.rtools()</code>.</li>
</ol>
</section>
<section id="file-does-not-exist-or-no-such-file-or-directory" class="level3" data-number="3.10.8">
<h3 data-number="3.10.8" class="anchored" data-anchor-id="file-does-not-exist-or-no-such-file-or-directory"><span class="header-section-number">3.10.8</span> File does not exist, or No such file or directory</h3>
<p>If you get an error like <code>'filename.csv' does not exist</code>, that means that you’re trying to load a file, but the file is not in the location you’re telling R to look.</p>
<p>The Fix:</p>
<ol type="1">
<li>Did you spell the filename correctly? Maybe you made a typo. Or, perhaps, you’re trying to open an Excel fie (<code>.xlsx</code>) but telling R to look for a CSV (<code>.csv</code>). Or you wrote “file.csv” but the file is “file (1).csv”.</li>
<li>Is the file perhaps open in Excel? Sometimes, Microsoft Office will hold files hostage and not let them be opened in other programs while they’re open in Office. Close the Excel window that has the file open.</li>
<li><strong>Most often</strong>, this is a working directory issue. If you tell R to look for <code>'filename.csv'</code>, it will look for that file in the <em>working directory</em>. Or, if you tell it to look for <code>'data/filename.csv'</code>, it will look for a folder called “data” in the working directory, and for filename.csv inside of that. In recent versions of RStudio, the current working directory is listed right on top of the Console. Did you check whether the file is actually in that folder? If you’re running RMarkdown, it will set the working directory to the folder where the .RMD file is located. Did you put the file in the right spot relative to where the RMD is stored? See my <a href="https://www.youtube.com/watch?v=NG7Y0kkGR8g">video on filepaths</a> for more help.</li>
</ol>
</section>
<section id="klammern-kommata-punkte" class="level3" data-number="3.10.9">
<h3 data-number="3.10.9" class="anchored" data-anchor-id="klammern-kommata-punkte"><span class="header-section-number">3.10.9</span> Klammern, Kommata, Punkte</h3>
<p>Just in general, a very large percentage of errors students come to me with occur simply because they made a typo, or didn’t balance their parentheses (pairing each ( with a )).</p>
<p>The Fix:</p>
<ol type="1">
<li>If you get an error message of any kind, read the relevant part of the code carefully to make sure you didn’t make a typo</li>
<li>Avoid coding where you have lots and lots of nested parentheses (this is something that <strong>tidyverse</strong> piping we learn is intended to avoid). Then, for whatever parentheses you do have, click on each one in RStudio - it will highlight its “partner” or show where there is a missing partner.</li>
</ol>
</section>
<section id="ergebnis-na" class="level3" data-number="3.10.10">
<h3 data-number="3.10.10" class="anchored" data-anchor-id="ergebnis-na"><span class="header-section-number">3.10.10</span> Ergebnis <code>NA</code></h3>
<p>Fehlende Werte sind Teil eines jeden Datensatzes. Wir haben oben kennengelernt, dass in R <code>NA</code> für fehlende Angaben steht. R geht mit <code>NA</code> etwas anders um als bspw. Stata; Sobald ein Wert <code>NA</code> ist, gibt R als Ergebnis <code>NA</code> aus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>werte <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="cn">NA</span>)</span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(werte)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(werte)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p><em>Lösung</em> Mit der Option <code>na.rm = TRUE</code> werden alle <code>NA</code> Werte vor der Berechnung ignoriert;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(werte,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(werte,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="numerische-variablen-und-strings" class="level3" data-number="3.10.11">
<h3 data-number="3.10.11" class="anchored" data-anchor-id="numerische-variablen-und-strings"><span class="header-section-number">3.10.11</span> Numerische Variablen und strings</h3>
<p>When you put something in quotes, like ‘1’, it will treat it as a <em>string variable</em> - a set of characters to be read as text.</p>
<p>If you want a variable to be treated as a number, <strong>do not put it in quotes.</strong> This way lies madness.</p>
<p>R is pretty loose, and will allow you to do things like ask whether <code>'2' &gt; 1</code>, and will answer yes. This <em>feels</em> like it’s okay to put the 2 in quotes. But it’s not. What R is doing is saying “oof… I can’t compare a number to a letter, but you’re asking me to. I’ll just convert this number to a string as well, so I’m really doing <code>'2' &gt; '1'</code>, and since ‘2’ is alphabetically after ‘1’, that’s true, which is the desired result. Great! Except it also means that <code>'02' &gt; 1</code> is false, since ‘02’ is alphabetically before ‘1’. Same with <code>'120'&gt;'20'</code> being false. Oops.</p>
<p>The Fix:</p>
<ol type="1">
<li>If it’s a number, and you want it treated like a numeric value, don’t put quotes around it.</li>
</ol>
</section>
<section id="und" class="level3" data-number="3.10.12">
<h3 data-number="3.10.12" class="anchored" data-anchor-id="und"><span class="header-section-number">3.10.12</span> <code>&lt;-</code>, <code>=</code> und <code>==</code></h3>
<p><code>&lt;-</code> is for assigning objects. You can say <code>a &lt;- 1</code>, and that will create an object <code>a</code> with the value <code>1</code> inside.</p>
<p><code>=</code> <em>can also</em> be for assigning objects, just like <code>&lt;-</code>, but is also for assigning arguments and options in functions. In the function <code>mean()</code>, which takes the argument <code>x</code>, I can say <code>mean(x = 1:10)</code> but not <code>mean(x &lt;- 1:10)</code>.</p>
<p><code>==</code> is for <em>checking</em> whether two things are equal. <code>a == 1</code> will check whether the object <code>a</code> is equal to <code>1</code>, and will return <code>TRUE</code> if it is, or <code>FALSE</code> otherwise.</p>
<p>Commonly, this will cause problems in cases like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="at">state =</span> <span class="st">"WA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which we might expect to filter our data to rows that are in the state of Washington, but instead will try to assign a new object <code>state</code> to be equal to <code>"WA"</code>.</p>
</section>
<section id="einige-generelle-tipps-zur-fehlervermeidung" class="level3" data-number="3.10.13">
<h3 data-number="3.10.13" class="anchored" data-anchor-id="einige-generelle-tipps-zur-fehlervermeidung"><span class="header-section-number">3.10.13</span> Einige generelle Tipps zur Fehlervermeidung</h3>
<ol type="1">
<li>Führen Sie Ihren Code Zeile für Zeile aus. Prüfen Sie zwischen den einzelnen Zeilen die Ausgabe und stellen Sie sicher, dass sie so aussieht, wie Sie es erwarten. Oft treten Fehler auf, weil eine frühere Codezeile nicht das getan hat, was wir beabsichtigt haben. Wenn Sie dort keine Probleme feststellen, machen Sie weiter, bis Sie auf die Fehlermeldung stoßen.</li>
<li>Lesen Sie die Fehlermeldung und schauen Sie, ob Sie sich einen Reim darauf machen können</li>
<li>Selbst wenn du die Meldung nicht verstehst, gibt sie dir oft einen Hinweis auf die Ursache des Problems, so dass du weißt, wo du nachschauen musst, um deinen Code zu überprüfen</li>
<li>Google: oftmals hilft es eine Fehlermeldung oder ein Problem (“How to …. in R”) zu googeln. Neben stackoverflow gibt es unzählige Blogs, Tutorials und andere Hilfeseiten für R in hervorragender Qualität - und sie sind (fast) immer kostenlos!</li>
</ol>
</section>
</section>
<section id="hinweise" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="hinweise"><span class="header-section-number">3.11</span> Hinweise</h2>
<section id="hinweis_cut_w103" class="level3" data-number="3.11.1">
<h3 data-number="3.11.1" class="anchored" data-anchor-id="hinweis_cut_w103"><span class="header-section-number">3.11.1</span> cut wählt ein ungünstiges Zahlenformat</h3>
<p><code>cut</code> verwendet für Klassengrenzen mit mehr als 3 Stellen eine wenig intuitive Darstellung. Mit <code>dig.lab</code> können Labels mit mehr als 3 Stellen angefordert werden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1212</span>,<span class="dv">2121</span>,<span class="dv">1212</span>)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( <span class="fu">cut</span>(x1, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1500</span>,<span class="dv">2500</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      (0,1.5e+03] (1.5e+03,2.5e+03] 
                2                 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>( <span class="fu">cut</span>(x1, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1500</span>,<span class="dv">2500</span>), <span class="at">dig.lab =</span> <span class="dv">4</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   (0,1500] (1500,2500] 
          2           1 </code></pre>
</div>
</div>
</section>
<section id="relative-häufigkeiten-runden" class="level3" data-number="3.11.2">
<h3 data-number="3.11.2" class="anchored" data-anchor-id="relative-häufigkeiten-runden"><span class="header-section-number">3.11.2</span> Relative Häufigkeiten runden</h3>
<p>Erläuterung: Sie können mit <code>round(x , 3)</code> Werte auf eine gewisse Zahl von Ziffern runden. Die zweite Zahl in der Klammer (nach dem Komma) gibt an, wieviele Dezimalstellen wir möchten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.12121</code></pre>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">21.12121123</span>,<span class="at">digits =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21</code></pre>
</div>
</div>
<p>Wir können also die relativen Häufigkeiten runden und so die Tabelle von oben übersichtlicher machen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H           f         F
1     1 3238 3238 0.928591913 0.9285919
2     2   33 3271 0.009463722 0.9380556
3     3  216 3487 0.061944365 1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>f <span class="ot">&lt;-</span> <span class="fu">round</span>(t3<span class="sc">$</span>f,<span class="dv">3</span>)</span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>F <span class="ot">&lt;-</span> <span class="fu">round</span>(t3<span class="sc">$</span>F,<span class="dv">3</span>)</span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F
1     1 3238 3238 0.929 0.929
2     2   33 3271 0.009 0.938
3     3  216 3487 0.062 1.000</code></pre>
</div>
</div>
</section>
<section id="wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen" class="level3" data-number="3.11.3">
<h3 data-number="3.11.3" class="anchored" data-anchor-id="wie-kann-ich-mir-in-r-automatisch-die-häufigsteseltenste-ausprägung-ausgeben-lassen"><span class="header-section-number">3.11.3</span> Wie kann ich mir in R automatisch die häufigste/seltenste Ausprägung ausgeben lassen?</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>t1 <span class="ot">&lt;-</span> <span class="fu">table</span>(a16<span class="sc">$</span>age)</span>
<span id="cb157-2"><a href="#cb157-2" aria-hidden="true" tabindex="-1"></a>t1[<span class="fu">which</span>(t1 <span class="sc">==</span> <span class="fu">max</span>(t1))] <span class="co"># Modus</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>48 
87 </code></pre>
</div>
</div>
<p><code>age=48</code> ist mit <code>87</code> Befragten die häufigste Ausprägung.</p>
</section>
<section id="labels-als-neue-spalte-hinzufügen" class="level3" data-number="3.11.4">
<h3 data-number="3.11.4" class="anchored" data-anchor-id="labels-als-neue-spalte-hinzufügen"><span class="header-section-number">3.11.4</span> Labels als neue Spalte hinzufügen</h3>
<p>Wir können die Übersichtstabelle auch noch beschriften, indem wir eine Textvariable hinzufügen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>t3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F
1     1 3238 3238 0.929 0.929
2     2   33 3271 0.009 0.938
3     3  216 3487 0.062 1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>t3<span class="sc">$</span>labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dt Staatsbürgerschaft"</span>,<span class="st">"dt und andere Staatsbürgerschaft"</span>,</span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"andere Staatsbürgerschaft"</span>)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a>t3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Werte    h    H     f     F                           labels
1     1 3238 3238 0.929 0.929            dt Staatsbürgerschaft
2     2   33 3271 0.009 0.938 dt und andere Staatsbürgerschaft
3     3  216 3487 0.062 1.000        andere Staatsbürgerschaft</code></pre>
</div>
</div>


</section>
</section>
<section class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1" role="doc-endnote"><p>Die Werte für fehlende Angaben finden wir Codebuch: auch hier ist <code>-32</code> wieder ein Code für fehlende Werte.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Die Werte für fehlende Angaben finden wir Codebuch: auch hier ist <code>-32</code> wieder ein Code für fehlende Werte.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./02_intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Arbeiten mit Datensätzen in R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>