{
  "hash": "a74ce8fc8401b7d9c45a60bf16e584f6",
  "result": {
    "markdown": "# Regressionsmodelle {#reg}\n\n\n\n\n\n## Beispieldatensatz\n\nZum Einstieg betrachten wir zunächst einen (fiktiven) Datensatz mit lediglich vier Fällen. Mit dem `data.frame` Befehl können wir einen Datensatz erstellen. Unserer hat zunächst lediglich zwei Variablen: var1 und var2 \n\n::: {.cell}\n\n```{.r .cell-code}\ndat1 <- data.frame(var1 = c(1,2,7,8),\n                   var2 = c(2,4,7,6))\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  var1 var2\n1    1    2\n2    2    4\n3    7    7\n4    8    6\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n## Regressionsmodelle mit `lm()` {#lm1}\n\n\n::: {.cell}\n\n:::\n\n\nRegressionsmodelle in R lassen sich mit `lm()` erstellen. \nHier geben wir das Merkmal an, dass auf der y-Achse liegt (die *abhängige* Variable) und nach einer `~`  das Merkmal für die x-Achse (*unabhängige* Variable). Die Interpretation des Ergebnisses wird uns die kommenden Wochen beschäftigen. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(var2~ var1, data = dat1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nCoefficients:\n(Intercept)         var1  \n     2.1351       0.5811  \n```\n:::\n:::\n\n\nDer Wert unter `var1` gibt an, um *wieviel sich die Gerade pro \"Schritt nach rechts\" nach oben/unten verändert*. Die Gerade steigt also pro Einheit von `var1` um 0.5810811. Die Ergebnisse können wir unter `m1` ablegen:\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(var2~ var1, data = dat1)  \n```\n:::\n\n\nMit `summary()` bekommen wir dann eine Regressionstabelle:\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nResiduals:\n      1       2       3       4 \n-0.7162  0.7027  0.7973 -0.7838 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)   2.1351     0.9485   2.251   0.1532  \nvar1          0.5811     0.1746   3.327   0.0797 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.062 on 2 degrees of freedom\nMultiple R-squared:  0.847,\tAdjusted R-squared:  0.7705 \nF-statistic: 11.07 on 1 and 2 DF,  p-value: 0.07967\n```\n:::\n:::\n\n\n\n\nMit `geom_smooth(method = \"lm\")` können wir Regressionsgerade auch in `{ggplot2}` darstellen:\nIn unserer Grafik sieht diese Gerade so aus:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 2) + \n  geom_smooth(method = \"lm\", color = \"darkblue\" , se = FALSE, size = .65)  +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) \n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=288}\n:::\n:::\n\n\n### Vorhergesagte Werte {#pred}\n\nIn welcher Hinsicht ist die Gerade nun eine Verbesserung gegenüber dem `mean`? Wir können uns für eine Einschätzung die Residuen ansehen. Für den Punkt ganz links hatte wir vorhin berechnet, dass das Residuum auf Basis des arithm. Mittels (also die Distanz zum orangen Punkt auf der gestrichelten Linie) `2-4.75 = -2.75` beträgt:\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  var1 var2 var2_mean\n1    1    2      4.75\n2    2    4      4.75\n3    7    7      4.75\n4    8    6      4.75\n```\n:::\n:::\n\nDie vorhergesagten Werte von `lm()` finden sich unter `$fitted.values`:\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$fitted.values\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       1        2        3        4 \n2.716216 3.297297 6.202703 6.783784 \n```\n:::\n:::\n\nDiese vorhergesagten Werte entsprechen einfach der Summe aus dem Wert unter `Intercept` und dem Wert unter `var1` multipliziert mit dem jeweiligen Wert für `var1`. \n\n::: {.cell}\n\n```{.r .cell-code}\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nCoefficients:\n(Intercept)         var1  \n     2.1351       0.5811  \n```\n:::\n:::\n\nFür die erste Zeile aus `dat1` ergibt sich also `m1` folgender vorhergesagter Wert: `2.1351+0.5811*1=`2.7162\n\nDie Werte unter `fitted.values` folgen der Reihenfolge im Datensatz, sodass wir sie einfach als neue Spalte in `dat1` ablegen können:\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$lm_vorhersagen <- m1$fitted.values\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  var1 var2 var2_mean lm_vorhersagen\n1    1    2      4.75       2.716216\n2    2    4      4.75       3.297297\n3    7    7      4.75       6.202703\n4    8    6      4.75       6.783784\n```\n:::\n:::\n\nDie Grafik zeigt wie Vorhersagen auf Basis von `m1` aussehen: Sie entsprechen den Werten auf der blauen Geraden (der sog. Regressionsgeraden) an den jeweiligen Stellen für `var1`. \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(dat1, aes(x = var1, y = var2)) + geom_point(size = 3) +      expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) +\n  geom_hline(aes(yintercept = var2_mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = var2_mean), col = \"darkorange\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = var2_mean), color = \"red\", size = .65, linetype = \"dotted\")  +\n  geom_smooth(method = \"lm\", color = \"darkblue\" , se = FALSE,size =.65) +\n  geom_point(aes(x = var1, y = lm_vorhersagen), color = \"dodgerblue3\", size = 3)\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=288}\n:::\n:::\n\n\n### Residuen des Regressionsmodells {#res2}\n\nWir können erkennen, dass die hellblauen Punkte (also die Vorhersagen von `m1`) deutlich näher an den tatsächlichen Punkten liegen als die orangen Vorhersagen auf Basis des `mean`. Trotzdem sind auch die hellblauen Punkte nicht deckungsgleich mit den tatsächlichen Werten. Es gibt also auch hier wieder Residuen. Wir können diese per Hand berechnen als Differenz zwischen dem tatsächlichen und dem vorhergesagten Wert:\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$var2 - m1$fitted.values\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         1          2          3          4 \n-0.7162162  0.7027027  0.7972973 -0.7837838 \n```\n:::\n:::\n\nOder wir können Sie unter `m1$residuals` aufrufen:\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         1          2          3          4 \n-0.7162162  0.7027027  0.7972973 -0.7837838 \n```\n:::\n:::\n\nAuch die Residuen für `lm` können wir in `dat1` ablegen: \n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$lm_residuen <- m1$residuals\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  var1 var2 var2_mean lm_vorhersagen lm_residuen\n1    1    2      4.75       2.716216  -0.7162162\n2    2    4      4.75       3.297297   0.7027027\n3    7    7      4.75       6.202703   0.7972973\n4    8    6      4.75       6.783784  -0.7837838\n```\n:::\n:::\n\n\nHier sind die Residuen für `lm` hellblau eingezeichnet:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(dat1, aes(x = var1, y = var2)) + geom_point(size = 3) + \n    \n  expand_limits(x = c(0,8),y=c(0,8)) +\n  geom_hline(aes(yintercept = var2_mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = var2_mean), col = \"darkorange\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = var2_mean), color = \"red\", size = .65, linetype = \"dotted\")  +\n  geom_smooth(method = \"lm\", color = \"darkblue\" , se = FALSE,size =.65) +\n  geom_point(aes(x = var1, y = lm_vorhersagen), color = \"dodgerblue3\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = lm_vorhersagen), color = \"dodgerblue3\", size = .65, linetype = 1) \n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=264}\n:::\n:::\n\n\n## Modellgüte {#r2}\n\nUm zu beurteilen, um wieviel besser unsere Gerade aus `lm()` die Werte vorhersagen kann als der `mean` können wir die Summe der quadrierten Residuen vergleichen:\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$lm_residuen2 <- dat1$lm_residuen^2\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  var1 var2 var2_mean lm_vorhersagen lm_residuen lm_residuen2\n1    1    2      4.75       2.716216  -0.7162162    0.5129657\n2    2    4      4.75       3.297297   0.7027027    0.4937911\n3    7    7      4.75       6.202703   0.7972973    0.6356830\n4    8    6      4.75       6.783784  -0.7837838    0.6143170\n```\n:::\n\n```{.r .cell-code}\nsum(dat1$m_residuen2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nsum(dat1$lm_residuen2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.256757\n```\n:::\n:::\n\nZum Beispiel können wir uns fragen, um wieviel sich die Summe der quadrierten Residuen verringert wenn wir statt des `mean` unser `lm`-Modell verwenden:\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dat1$m_residuen2)-sum(dat1$lm_residuen2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.256757\n```\n:::\n:::\n\nWenn wir diese Veränderung ins Verhältnis mit dem \"Ausgangswert\", also den Residuen aus der Mittelwertregel setzen, dann erhalten wir das $R^{2}$ für unser `lm()`-Modell. Dieses gibt die prozentuale Verringerung der Residuen durch das `lm()`-Modell im Vergleich zur Mittelwertregel an: \n\n::: {.cell}\n\n```{.r .cell-code}\n( sum(dat1$m_residuen2)-sum(dat1$lm_residuen2) )/sum(dat1$m_residuen2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -Inf\n```\n:::\n:::\n\nUnser `lm`-Modell kann also 84,7\\% der Streuung um den Mittelwert erklären.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\nperformance(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Indices of model performance\n\nAIC    |    BIC |    R2 | R2 (adj.) |  RMSE | Sigma\n---------------------------------------------------\n15.062 | 13.221 | 0.847 |     0.770 | 0.751 | 1.062\n```\n:::\n:::\n\n\n\n## Interaktionen\n\n## Quadratische Terme & Polynome\n\n## Kategoriale unabhängige Variablen\n\n\n\n## Aufgaben\n### Aufgabe 1 \nErstellen Sie wie folgt einen Beispieldatensatz (Sie können aber gerne auch eigene, andere Werte verwenden)\n\n::: {.cell}\n\n```{.r .cell-code}\ndat12 <- data.frame(var1 = c(12,10,24,28,23) ,\n                  var2 = c(17,16, 3, 5, 8))\n```\n:::\n\n+ Berechnen Sie das arithm. Mittel für `var2`!\n+ Legen Sie das arithm. Mittel als neue Variable im Datensatz `dat12` ab (siehe [S.1](#mittelwert))\n+ Berechnen Sie die Residuen für die Mittelwertsregel - wie groß ist die Abweichung vom arith. Mittel für die einzelnen Beobachtungen für `var2`? (Stichwort [Residuen](#res1))\n+ Legen Sie die Residuen der Mittelwertsregel in `dat12` ab.\n+ Wie groß ist die Summe der Resiuden, wenn Sie alle Werte zusammen zählen?\n+ Erstellen Sie ein Objekt `m2` mit einem linearen Regressionsmodell (`lm`) mit `var2` als abhängiger und `var1` als unabhängiger Variable! (siehe [hier](#lm1))\n+ Betrachten Sie Ergebnisse `m2` - was können Sie erkennen? Besteht ein positiver oder negativer Zusammenhang zwischen `var1` und `var2`?\n+ Legen Sie die vorhergesagten Werte und die Residuen aus dem Regressionsmodell `m2` jeweils in einer Spalte in `dat12` ab. \n+ Wie hoch ist die Summe der Residuen aus `m2`? Wie hoch ist die Summe der quadrierten Residuen für `m2`?\n+ Berechnen Sie die Differenz zwischen den quadrierten Residuen der Mittelwertregel und den quadrierten Residuen für `m2`. Berechnen Sie das $R^2$ für `m2`! (siehe [hier](#r2))\n\n### Aufgabe 2\nDieses Prinzip funktioniert natürlich genauso für größere Datensätze, zum Beispiel den Allbus 2016. Untersuchen Sie den Zusammenhang zwischen Alter (`age`) und dem Einkommen (`inc`) der weiblichen, in Vollzeit erwerbstätigen Befragten!\n\n+ Lesen Sie den Allbus-Datensatz wie bekannt ein. Hier nochmal zu Erinnerung das Vorgehen:\n\n::: {.cell}\n\n```{.r .cell-code}\n## Arbeitsverzeichnis in den Ordner mit dem Datensatz setzen:\nsetwd(\"C:/Lehre\") \na16 <- read.csv(\"allbus2016.csv\", sep = \";\", header = T) ## einlesen\nlibrary(dplyr) ## für die Pipe und select/filter\n```\n:::\n\nZunächst müssen wir dann die Missings mit `NA` überschreiben:\n\n::: {.cell}\n\n```{.r .cell-code}\na16$age[a16$age<0] <- NA\na16$inc[a16$inc<0] <- NA\n```\n:::\n\nMit einem `filter`-Befehl können wir dann nur die Beobachtungen auswählen, die für `age` und `inc` nicht Missing sind (also `is.na()` gleich `FALSE` ist):\n\n::: {.cell}\n\n```{.r .cell-code}\na16 <- a16 %>% filter(!is.na(inc), !is.na(age))\n```\n:::\n\n+ Mit folgendem Befehl können Sie ein Teildatenset `a16f` erstellen, das nur in Vollzeit erwerbstätige Frauen enthält:\n\n::: {.cell}\n\n```{.r .cell-code}\na16f <- a16 %>% filter(sex == 2, work == 1) # a16 filtern\n```\n:::\n\nFür die Analyse sind nur die Variablen `age` und `inc` wichtig, also können wir den Datensatz auf diese beiden Variablen reduzieren:\n\n::: {.cell}\n\n```{.r .cell-code}\na16f <- a16f %>% select(age, inc) #nur Spalten inc & sex  \n```\n:::\n\nMit `head` können wir uns die ersten Zeilen des Datensatzes anzeigen lassen oder mit `View()` den gesamten Datensatz ansehen: \n\n::: {.cell}\n\n```{.r .cell-code}\nhead(a16f)\nView(a16f)\n```\n:::\n\n\n\n+ Berechnen Sie das arithm. Mittel für das Einkommen \n+ Legen Sie das arithm. Mittel als neue Variable im Datensatz ab (siehe S.1)\n+ Berechnen Sie die Residuen für die Mittelwertregel!\n+ Wie groß ist die Summe der Residuen, wenn Sie alle Werte zusammen zählen?\n+ Erstellen Sie ein Objekt `m3` mit einem linearen Regressionsmodell (`lm`) mit dem Einkommen (`inc`) als abhängiger und dem Alter (`age`) der Frauen als unabhängiger Variable! \n+ Welche Richtung für die Regressionsgerade können Sie erkennen?\n+ Legen Sie die vorhergesagten Werte und die Residuen aus dem Regressionsmodell `m3` jeweils in einer Spalte in `a16f` ab. `\n+ Wie hoch ist die Summe der quadrierten Residuen aus `m3`?\n+ Berechnen Sie das $R^2$ für `m3`! \n\n\n\n## Für Interessierte: Syntax für Graphiken\n\nDie Abbildungen oben sind mit `ggplot2` erstellt. \n\nFalls nicht bereits geschehen, können wir es so installieren:\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"ggplot2\")\nlibrary(ggplot2)\n```\n:::\n\nDas Prinzip bei `ggplot2` ist, zunächst grundlegende Optionen festzulegen und erst dann schließen wir mit `+` Befehle für die Art der Darstellung an.  \n\nWir geben also zunächst an, dass wir Variablen aus `dat1` darstellen möchten. Auf die x-Achse soll var1, auf der y-Achse soll `var2` abgetragen werden. Diese Daten möchten wir als Punktediagramm/\"Scatterplot\" darstellen, der Befehl dafür ist `geom_point`. Diese beiden Befehle liefern schon eine Darstellung, die wir aber noch anpassen. In den Optionen von `geom_point` können wir mit `size` die Punkte etwas größer machen, außerdem mit können wir mit `theme_minimal()` dar Farbschema auf Schwarz/Weiß setzen. Mit `scale_x_continuous()` und  `scale_y_continuous()` können wir die Intervalle für die x- und y-Achse festlegen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + geom_point()\nggplot(dat1, aes(x = var1, y = var2)) + geom_point(size = 2) + theme_minimal() +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) \n```\n:::\n\n### mean einzeichnen\nFür die `mean`-Linie müssen wir bei `yintercept` den y-Achsenabschnitt angeben, bei dem die horizontale Linie (das h in hline steht für horizontal) eingezeichnet werden soll. Außerdem können wir mit `color` eine Farbe, mit `size` die Breite und mit `linetype` den Linientyp auswählen. Mit `geom_label` können Textfelder eingeblendet werden.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 3) + \n  theme_minimal() +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) +\n  geom_hline(aes(yintercept = mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_label(aes(y = 4, x = 5), label = \"mean = 4.75\", color = \"grey30\")\n```\n:::\n\n\n\n\n### Vorhergesagte Werte aus Mittelwertregel\nUm die vorhergesagten Werte einzuzeichnen geben wir in einem zusätzlichen `geom_point` für die x-Werte weiterhin `var1` an, hier ändert sich ja nichts. Für `y` geben  wir aber `mean` an, also den vorhergesagten Wert.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## vohergesagte Werte einzeichnen\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 3) + \n  theme_minimal() +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  geom_hline(aes(yintercept = mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = mean), color = \"darkorange\", size = 3) \n```\n:::\n\n\n### Residuen einzeichnen\n\nDie Residuen zweichnen wir mit Hilfe von `geom_segment` ein. `geom_segment` benötigt in `aes()` 4 Angaben: jeweils den Start- und Endpunkt der Linie für die x- und y-Achse. `x` und `xend` geben also die Strecke in \"x-Richtung\" von links nach rechts an, `y` und `yend` die Strecke in \"y-Richtung\". Mit `color`, `size` und `linetype` wird die Farbe, die Größe und den Linientyp angepasst.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 3) + \n  theme_minimal() +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) +\n  geom_hline(aes(yintercept = mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = mean), col = \"darkorange\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = mean), color = \"red\", size = .65, \n               linetype = \"dotted\")  \n```\n:::\n\n\n### Regressionsgerade einzeichnen\nDie Regressionsgerade aus `lm` können wir mit `geom_smooth(method = \"lm\")` einzeichnen:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + geom_point(size = 3) +   \n  theme_minimal() +\n  expand_limits(x = c(0,8),y=c(0,8)) +\n  scale_y_continuous(breaks = seq(0,8,2)) +\n  scale_x_continuous(breaks = seq(0,8,2)) +\n  geom_hline(aes(yintercept = mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = mean), col = \"darkorange\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = mean), color = \"red\", size = .65, \n               linetype = \"dotted\")  +\n  geom_smooth(method = \"lm\", color = \"darkblue\" , se = FALSE) \n```\n:::\n\n\n\n### Residuen aus Regression einzeichnen\nSchließlich können wir auch die Residuen aus `lm` einzeichnen, wiederum mit `geom_segment`:\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 3) + theme_minimal() +\n  geom_hline(aes(yintercept = mean), color = \"#4F5CB3\", size = .75, linetype = \"dashed\") +\n  geom_point(aes(x = var1, y = mean), col = \"darkorange\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = mean), color = \"red\", size = .65, \n               linetype = \"dotted\")  +\n  geom_smooth(method = \"lm\", color = \"darkblue\" , se = FALSE) +\n  geom_point(aes(x = var1, y = lm_vorhersagen), color = \"dodgerblue3\", size = 3) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = lm_vorhersagen), \n               color = \"dodgerblue3\", size = .65, linetype = 1) \n```\n:::\n\n\n\n\n\n### Annahmen checken\n[model dashboard](https://easystats.github.io/easystats/reference/model_dashboard.html)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n ## install.packages('see')\nlibrary(performance)\ndata(mtcars)\nmtcars$gear <- factor(mtcars$gear) ## \nm1 <- lm(mpg ~ qsec, mtcars)\nm2 <- lm(mpg ~ qsec + gear, mtcars)\n\ncheck_model(m2,panel = F)\n```\n:::\n\n\n### Regressionsmodelle vergleichen\n\nMit dem Paket `{performance}` können wir auch einen umfassenden Modellvergleich bekommen:\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_performance(m1,m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# Comparison of Model Performance Indices\n\nName | Model |     AIC | AIC weights |     BIC | BIC weights |    R2 | R2 (adj.) |  RMSE | Sigma\n------------------------------------------------------------------------------------------------\nm1   |    lm | 204.588 |    7.00e-04 | 208.985 |       0.003 | 0.175 |     0.148 | 5.387 | 5.564\nm2   |    lm | 190.061 |       0.999 | 197.390 |       0.997 | 0.538 |     0.488 | 4.033 | 4.312\n```\n:::\n:::\n",
    "supporting": [
      "09_reg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}